Add possibility for themes to change text color in header
piwik/piwik pull request #12204
Opened 2017-10-18 03:27 UTC by tsteur

fixes #12201 If I understand it correctly, the color in the header should be changeable which I totally agree to in order to make it useful.

Expecting UI tests to fail for the theming part with black menu text color. 

For the variable I used the ending `-text` even though they are technically links (`-link`) to be consistent with the menu.

2017-10-18 06:22 UTC, tsteur commented
UI test failures are not from this PR

2017-10-18 18:57 UTC, sgiehl requested changes
Left a comment. Besides that, looks good

2017-10-18 18:57 UTC, sgiehl commented on CHANGELOG.md
> + * Themes can now customer the header text color using `@theme-color-header-text`
guess that should be `customize`

2017-10-25 19:39 UTC, sgiehl approved these changes
Fixed the typo. Now LGTM

2017-11-19 22:22 UTC, merged