Phpunit speedtrap
piwik/piwik pull request #12763
Opened 2018-04-23 09:50 UTC by szepeviktor

Was #12760

2018-04-23 10:39 UTC, szepeviktor commented
# Results

### SystemTests

```
You should really fix these slow tests (>500ms)...
 1. 215204ms to run Piwik\Tests\System\ArchiveCronTest:testArchivePhpCron
 2. 59605ms to run Piwik\Tests\System\TwoVisitorsTwoWebsitesDifferentDaysTest:testApi with data set #7
 3. 54062ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #92
 4. 51416ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #96
 5. 51372ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #90
 6. 50215ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #74
 7. 48881ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #72
 8. 48671ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #94
 9. 47777ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #66
 10. 47513ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #58
...and there are 202 more above your threshold hidden from view
Time: 32.84 minutes, Memory: 368.00MB
```

2018-04-23 10:51 UTC, szepeviktor commented
Something very fundamental takes ~50 per unit test

2018-05-08 21:25 UTC, mattab commented
Thank you @szepeviktor for creating your first PR, that's really useful :+1: making our tests faster has become top priority as the System tests often fail as they exceed 40min. 

From this output it looks like possibly `Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi` should be tackled first as this causes probably 15+min or more in itself. (these tests check that each dimension can be used as segment, and have at least a visit matching in the fixture.)

```
You should really fix these slow tests (>500ms)...
 1. 215204ms to run Piwik\Tests\System\ArchiveCronTest:testArchivePhpCron
 2. 59605ms to run Piwik\Tests\System\TwoVisitorsTwoWebsitesDifferentDaysTest:testApi with data set #7
 3. 54062ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #92
 4. 51416ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #96
 5. 51372ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #90
 6. 50215ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #74
 7. 48881ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #72
 8. 48671ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #94
 9. 47777ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #66
 10. 47513ms to run Piwik\Tests\System\AutoSuggestAPITest:testAnotherApi with data set #58
```

2018-05-08 21:30 UTC, szepeviktor commented
@mattab Do you have a 1 page summary on how to get from cloning matomo repo to running a test?
Maybe a Dockerfile??

2018-05-08 21:31 UTC, sgiehl commented
this might help: https://github.com/matomo-org/matomo/blob/3.x-dev/tests/README.md

2018-05-08 22:16 UTC, szepeviktor commented
I think I need to create a Dockerfile to be able to *breath*

2018-05-08 22:46 UTC, szepeviktor commented
Could you help me how `piwik_tests` gets populated on Travis?

2018-05-08 23:04 UTC, szepeviktor commented
Adding comments to the testing system (travis.yml, shell scripts) may help a lot.

2018-05-18 02:27 UTC, diosmosis commented
@szepeviktor I use docker half of the time for development: https://github.com/diosmosis/matomo-docker-dev . It's definitely not official, so it may or may not work for you, I can't promise any real support and I will make changes to it as I need them.

Use `docker-compose up` to start it up (and all the other containers I use when developing). Install matomo by visiting `localhost:3000`, and run commands via the `console` script in the readme, eg, `/path/to/matomo-docker-dev/console tests:run ./tests/PHPUnit/System/OneVisitorTwoVisitsTest.php` (this will run the `console` php script in the matomo container).

As for how the test database is populated, it is created, setup & filled by the https://github.com/matomo-org/matomo/blob/3.x-dev/tests/PHPUnit/Framework/Fixture.php class and its descendants. (Fair warning, it sets up the entire matomo test environment, and so is a very large, hard to read class, and may make your eyes bleed.) Some test setup code is located elsewhere like in the https://github.com/matomo-org/matomo/blob/3.x-dev/tests/PHPUnit/Framework/TestingEnvironmentManipulator.php class.

2018-05-18 03:46 UTC, szepeviktor commented
Thank you.

2018-05-22 17:28 UTC, diosmosis requested changes
* The minimum execution time threshold needs to be increased for system tests, as they will always be slower than unit tests. Not sure what the best value is since some will always be long running. Perhaps it would be good to make the speed trap listener optional in some way.
* There's a conflict in the composer file that needs to be fixed.

2018-05-22 17:28 UTC, diosmosis commented on .travis.yml
> -      sudo: false
These changes need to be reverted before this PR can be merged.

2018-05-22 18:55 UTC, szepeviktor commented
Thank you @diosmosis!

This PR is a rather like a debugging session.
It's goal is to find out what takes ~50 second per test.
Up to now I wasn't able to find it out.

2018-05-24 03:13 UTC, diosmosis commented
@szepeviktor Gotcha, will remove this from the current milestone then, feel free to create PRs when you find some optimizations :)

2018-06-26 21:57 UTC, mattab commented
Thanks @szepeviktor for creating this PR. I've added a comment in the related issue here: https://github.com/matomo-org/matomo/issues/12691#issuecomment-400475879
I'll close this PR now, but feel free to re-open it as we could in theory add the speedtrap by default in Matomo.

2018-06-26 21:57 UTC, closed without merging