Do not show 'all' limit selector option for VisitorLog & default to 25 if filter_limit=-1 used
piwik/piwik pull request #12790
Opened 2018-04-30 02:11 UTC by diosmosis

Changes:
* added new `disable_all_rows_filter_limit` visualization property that can be used to disable the 'all' option from the limit selector.
* use in VisitorLog to disable the 'all' option.
* if -1 filter_limit found when trying to load VisitorLog, change it to another value.
* change default used in this case from 20 => 25 (since 25 is in the default values for `datatable_row_limits` and 20 is not).

Fixes #12789

2018-04-30 05:12 UTC, mattab requested changes
Looks good, just a minor feedback

2018-04-30 05:12 UTC, mattab commented on plugins/Live/Visualizations/VisitorLog.php
> +            $this->requestConfig->filter_limit = 25;
here let's use `General.datatable_default_limit`

2018-04-30 15:47 UTC, diosmosis commented
Oh whoops, didn't realize that would happen to the UI test viewer. I'll create a new branch to view tests results from

2018-04-30 16:52 UTC, diosmosis commented
Created branch to view build here: https://travis-ci.org/matomo-org/matomo/builds/373122394

2018-04-30 18:59 UTC, diosmosis commented
Some UI test failures, should be fixed on merge since they will likely conflict w/ other PRs.

2018-05-01 20:08 UTC, diosmosis commented
@mattab can you approve if this is good to go now? will update the UI tests & merge at that point

2018-05-02 09:48 UTC, mattab approved these changes

2018-05-04 00:17 UTC, merged