Allow hostnames to be configured in login whitelist
piwik/piwik pull request #13137
Opened 2018-07-04 22:23 UTC by tsteur

May be useful in combination with for example DynDNS providers. Or should we rather have a `login.whitelist.hostnames`?

2018-07-07 12:27 UTC, sgiehl requested changes
For me it would be fine to have the hostnames in the same setting, but we could also split it up.
Neverthless we should mention that in the config description: https://github.com/matomo-org/matomo/blob/3.x-dev/config/global.ini.php#L396-L406  and maybe the changelog as well

2018-07-08 20:43 UTC, tsteur commented
Good point 👍  Updated the global.ini.php. Not sure about the changelog as it is not directly developer related. I will update https://matomo.org/faq/how-to/faq_25543/ though.

2018-07-08 20:46 UTC, tsteur commented
fyi @mattab I slightly changed https://matomo.org/faq/how-to/faq_25543/ by adding the hostname part.

2018-07-09 08:10 UTC, sgiehl approved these changes

2018-07-09 08:27 UTC, merged