Add privacy policy/terms and conditions settings and display in bottom of certain pages.
piwik/piwik pull request #13219
Opened 2018-07-27 23:35 UTC by diosmosis

Login page:

![image](https://user-images.githubusercontent.com/125140/43350265-a78f4caa-91ba-11e8-9f93-87c0e0a6334e.png)

Dashboard (for anonymous user):

![image](https://user-images.githubusercontent.com/125140/43350298-d54aa0b8-91ba-11e8-84ae-5fb9e32be228.png)

Another normal page (for anonymous user):

![image](https://user-images.githubusercontent.com/125140/43350304-ecd66118-91ba-11e8-947e-8705cdaee5b1.png)

Widgetized (when enabled):

![image](https://user-images.githubusercontent.com/125140/43350310-fd07f312-91ba-11e8-8376-0967cf5870ea.png)

Fixes #12938

2018-07-27 23:37 UTC, diosmosis commented
If just one link is defined:

![image](https://user-images.githubusercontent.com/125140/43350364-65627dba-91bb-11e8-8262-a36a97be51d3.png)

2018-07-28 01:54 UTC, tsteur commented
Looks pretty good. I wonder if at some point we also might want to add "Powered by Matomo" there :) Off topic though :)

2018-07-30 09:30 UTC, sgiehl requested changes

2018-07-30 09:30 UTC, sgiehl commented on plugins/PrivacyManager/PrivacyManager.php
> +        }
Actually that check is redundant, as all users on the login pages are `anonymous`. But guess we could leave it there for a better understanding

2018-07-30 09:30 UTC, sgiehl commented on plugins/PrivacyManager/SystemSettings.php
> +namespace Piwik\Plugins\PrivacyManager;
Can't use that license header here. Maybe we should rebase that branch, so it isn't anywhere in the history

2018-07-30 21:16 UTC, diosmosis commented
@sgiehl updated

2018-07-31 21:16 UTC, mattab approved these changes

2018-08-01 21:13 UTC, merged