In piwik.updatePeriodParamsFromUrl() get period/date values from hash or URL.
piwik/piwik pull request #13268
Opened 2018-08-09 18:34 UTC by diosmosis

MultiSites dashboard does not use a hash so the date/period values were not found. So the currentDateString was not set correctly but only for range periods.

UI tests did not pick this up because MultiSites isn't tested w/ every type of period in the URL (doing so would add a lot of time to the tests). I added unit tests for the function in question in this PR.

Fixes #13266

2018-08-10 04:07 UTC, diosmosis commented
Note: found another issue while testing, don't merge yet

2018-08-10 06:55 UTC, mattab requested changes
* add UI test for period=range use case on All Websites dashboard (this is not the first time this breaks)

2018-08-10 06:56 UTC, mattab commented
please let me know also when this is finished testing and can be merged?

2018-08-10 22:10 UTC, diosmosis commented
@mattab can be merged.

2018-08-11 07:17 UTC, mattab commented
Looks good, thanks @diosmosis

2018-08-11 07:17 UTC, merged