Use placeholder for unsubscribe link and place it near the normal email footer content.
piwik/piwik pull request #13421
Opened 2018-09-13 02:40 UTC by diosmosis

Fixes #13330

@sgiehl can you review?

Here's what it looks like:

![image](https://user-images.githubusercontent.com/125140/45463996-53773780-b6c3-11e8-96cf-4a7283cb182f.png)

w/ WhiteLabel enabled:

![image](https://user-images.githubusercontent.com/125140/45464023-83bed600-b6c3-11e8-8670-9b6a4ee6fc49.png)

2018-09-13 02:46 UTC, diosmosis commented
Fixed the issue making the unsubscribe link not underlined, here's what it looks like now:

![image](https://user-images.githubusercontent.com/125140/45464249-9554ad80-b6c4-11e8-8e25-505a279af142.png)

2018-10-01 15:45 UTC, sgiehl commented
@diosmosis  could you do a rebase?

2018-10-01 23:17 UTC, diosmosis commented
@sgiehl Rebased.

2018-10-03 15:14 UTC, sgiehl requested changes
Besides the little comment, looks good and works (also with Whitelabel)

2018-10-03 15:14 UTC, sgiehl commented on plugins/CoreHome/templates/_htmlEmailFooter.twig
> +c{% set styleParagraph = 'font-size:15px;line-height:24px;margin:0 0 16px;' %}
there's a `c` in front of that line that should be removed again

2018-10-03 18:37 UTC, sgiehl approved these changes

2018-10-03 19:58 UTC, merged