Allow throwing exceptions for HTTP error codes to better check query param input.
piwik/piwik pull request #14023
Opened 2019-01-25 00:29 UTC by diosmosis

Added two new exceptions `HttpCodeException` and `BadRequestException` that allows changing the HTTP code returned for an exception (in both controller & API).

This allows us to avoid certain failures caused by invalid input and correctly report the error, w/o triggering a 500 HTTP code (that could potentially also create an email alert?).

Used in ScheduledReports API to check for multiple periods.

Fixes #13752

2019-01-28 08:05 UTC, sgiehl requested changes

2019-01-28 08:05 UTC, sgiehl commented on plugins/CoreVisualizations/Visualizations/HtmlTable.php
> +use Piwik\Http\BadRequestException;
guess that could be removed again

2019-02-23 18:58 UTC, sgiehl commented
@diosmosis  this one needs a rebase / merge to solve the conflicts

2019-04-11 01:17 UTC, tsteur commented on core/API/ResponseBuilder.php
> +        if ($this->sendHeader && $e instanceof HttpCodeException) {
would you need to check if a code is set?

2019-04-11 01:17 UTC, tsteur commented on core/ExceptionHandler.php
> +        if ($exception instanceof HttpCodeException) {
same here maybe we better check if a code is set?

2019-04-11 01:22 UTC, tsteur commented
Left 2 comments, otherwise good to merge when tests pass 👍

2019-05-15 01:16 UTC, merged