Add spans to visitor log tooltips.
piwik/piwik pull request #14050
Opened 2019-01-30 02:36 UTC by diosmosis

Refs #14005

2019-02-15 11:02 UTC, sgiehl requested changes
Note: rebased the branch and resolved the conflicts...

2019-02-15 11:02 UTC, sgiehl commented on plugins/Live/templates/getLastVisitsStart.twig
> -                                    <img class='iconPadding' src="{{ action.icon }}" title="{% if action.url|trim is not empty %}{{ action.url|e('html_attr') }}<br/>{% endif %}{{- title -}}"/>
Actually the `<br/>` between url and title got lost with adding the `<span>`s. But guess it would be better to solve the line break with CSS now.

2019-02-17 20:52 UTC, diosmosis commented
@sgiehl, updated. the tooltip code in JS replaces multiple newlines w/ `<br/>`s so thought that would be simpler than CSS.

2019-02-18 11:12 UTC, sgiehl approved these changes

2019-02-18 11:16 UTC, merged