Set segments for folder branches in page urls/page titles report
piwik/piwik pull request #14076
Opened 2019-02-06 21:35 UTC by diosmosis

Only way to get full path for subfolders is to set new metadata in Actions report. Which means this won't work for old data. I did add some code paths however that add the segment for top level folders. 

Fixes #9229

2019-02-25 12:46 UTC, sgiehl requested changes

2019-02-25 12:46 UTC, sgiehl commented on plugins/Actions/DataTable/Filter/Actions.php
> +            $urlPrefix = $dataTable->getMetadata('site')->getMainUrl();
When viewing an existing report **flattened** this throws a `Call to a member function getMainUrl() on boolean`

2019-02-26 01:26 UTC, diosmosis commented
Updated the PR.

2019-03-06 20:20 UTC, sgiehl approved these changes
Seems to work as expected now. Good to merge if tests pass

2019-03-07 01:29 UTC, merged