Switch from bower to npm and update JS libraries
piwik/piwik pull request #14082
Opened 2019-02-09 23:00 UTC by diosmosis

Still a WIP.

Fixes #12961

2019-02-10 08:26 UTC, Findus23 commented
@diosmosis Thanks for starting this work
See also #12067 for an old example package.json

It also seems like this doesn't really solve #12961 as jQuery <3 is still used.

2019-02-10 16:21 UTC, diosmosis commented
Currently just getting tests to pass w/ npm libs, some of whom required an update (eg, materializecss < 1.0 includes some node dependencies which we can't include in the repo, & some repos don't have the versions we use available). Then I'll upgrade libs and get tests to pass again.

Thanks for the warning about dotdotdot!

2019-02-10 19:23 UTC, tsteur commented
@diosmosis fyi changing the bower_components folder will be a BC break. They are used in various of our extra plugins and premium features. I assume also other plugins use it. Ideally we would keep the same directory structure and change it in Matomo 4 if possible. 

Also just to confirm we still commit the files to the repository right? Just making sure as it really does make installing and updating easier as you wouldn't need node.js to install it and makes sure everyone is using the same version. I would even go so far and commit the vendor directory eventually. Personally, I rarely run composer install after a branch change and things might not always be tested properly because of this. Just makes things easier and more consistent.

2019-02-10 21:34 UTC, diosmosis commented
> fyi changing the bower_components folder will be a BC break. They are used in various of our extra plugins and premium features. I assume also other plugins use it. Ideally we would keep the same directory structure and change it in Matomo 4 if possible.

Unfortunately, npm doesn't support specifying a different node_modules folder (though yarn does, so npm might in the future). I think for this we'd have to either change premium plugins to use the correct folder based on the matomo version, or give up until Matomo 4.

> Also just to confirm we still commit the files to the repository right?

Yes, so far no complications. If a library decides to include dependencies then it could get annoying, but I don't think it would be a real blocker.

2019-02-10 21:47 UTC, tsteur commented
> Unfortunately, npm doesn't support specifying a different node_modules folder (though yarn does, so npm might in the future). I think for this we'd have to either change premium plugins to use the correct folder based on the matomo version, or give up until Matomo 4.

Was thinking a symlink but reckon that might not be working on all systems. I reckon we could otherwise - if needed - have a little to do the npm update and manually move `node_modules` to `bower_components` as we commit it anyway? may be bit too annoying though.

It's likely not only premium features that use it but all plugins. Ideally we check the plugins on the marketplace to see if any of them use it (I think we used to have a search engine for that but don'T remember URL or if it still works). Most plugins won't be on the marketplace though...

Actually just thought of a better solution: We can rewrite the path in the asset manager and it'll be no problem :)

2019-02-10 22:18 UTC, diosmosis commented
> I reckon we could otherwise - if needed - have a little to do the npm update and manually move `node_modules` to `bower_components` as we commit it anyway? may be bit too annoying though.

This could be put into a command and a test added to ReleaseCheckListTest (since we have the list of files we use in the getJavaScriptFiles hook).

> Actually just thought of a better solution: We can rewrite the path in the asset manager and it'll be no problem :)

I see you beat me to it :) I was thinking of creating symlinks when merging assets, but using a map of bower_components => node_modules links works better. Will do this.

2019-05-21 16:57 UTC, diosmosis commented
Moved this to 3.11 since it should probably be in a beta.

2019-05-21 17:03 UTC, Findus23 commented
I agree. As much as I am for updating all JS libraries, this might introduce quite a few subtle bugs and we should especially get as many people as possible to beta-test this.

2019-10-01 00:59 UTC, diosmosis commented
Moving to 4.0 as discussed in #12961

2020-05-20 01:56 UTC, diosmosis commented
@tsteur / @sgiehl this should be ready for a review. This PR was meant to just be a switch to npm, but some libraries we use don't have the versions we use in npm, so it included several upgrades to the minimum version on npm (including materialize & jquery-ui). So after it's merged, another PR will have to be done which runs npm update. There are also some libraries in libs/ I didn't replace, but probably could be.

2020-05-20 08:09 UTC, sgiehl requested changes
Roughly looked through the code changes and left a few comments.
Will now do some local testing and add some more comments if anything is broken.
Btw. there are some smaller changes in colors and margins. Doesn't look bad to me, so should imho be fine.
~Also the changes to `plugins/Overlay/tests/UI/expected-screenshots/Overlay_page_link_clicks.png` doesn't seem correct. The test is failing on 4.x-dev. Not sure why that part isn't shown anymore.~ see #16016

2020-05-20 08:20 UTC, sgiehl commented
Visitor profile doesn't opened centered anymore, and there are some pixels overlapping on the grey headers:
![image](https://user-images.githubusercontent.com/1579355/82422667-07c58580-9a83-11ea-9831-f03de335e590.png)

All other popovers are centered when they are opened, but are not repositioned anymore after the content was loaded.

2020-05-20 08:24 UTC, sgiehl commented
Hovering row actions on subtable rows now show both tooltips:

![image](https://user-images.githubusercontent.com/1579355/82423444-0a74aa80-9a84-11ea-889a-bc50a0bad47a.png)

2020-05-20 08:33 UTC, sgiehl commented
Browsing the marketplace though normal menu looks bit broken (looks better when visiting though admin menu):
![image](https://user-images.githubusercontent.com/1579355/82424207-1c0a8200-9a85-11ea-8ed2-15111fbab7a9.png)
Also the button text color was white for disabled buttons before.

2020-05-20 08:35 UTC, sgiehl commented
Drop down for compare periods looks broken:
![image](https://user-images.githubusercontent.com/1579355/82424457-80c5dc80-9a85-11ea-9204-a006c343f43d.png)

2020-05-20 09:37 UTC, sgiehl commented
spacing between combined input fields in CustomAlerts plugin is broken:

![image](https://user-images.githubusercontent.com/1579355/82430951-50367080-9a8e-11ea-8835-92102ed55dbf.png)

2020-05-20 09:43 UTC, sgiehl commented
GoTo links on tracking code page don't work anymore:

![image](https://user-images.githubusercontent.com/1579355/82431617-26317e00-9a8f-11ea-8d87-3c0b406b1a2c.png)

2020-05-20 10:10 UTC, sgiehl commented
@diosmosis that's all I found so far by clicking through the UI. There might be some more regressions maybe, but imho it should be fine to merge this once those I already found are fixed. We can fix anything else later to avoid more merge conflicts with this PR

2020-05-20 22:54 UTC, diosmosis commented on libs/HTML/QuickForm2/Element/InputCheckable.php
> +            return '<label>' . parent::__toString() . '<span>' . $this->data['content'] . '</span></label>';
Only way it works w/ new materialize is w/ the input nested in the label.

2020-05-20 23:34 UTC, diosmosis commented on package.json
> +    "jscrollpane": "^2.2.1",
👍

2020-05-20 23:43 UTC, diosmosis commented on plugins/CoreHome/angularjs/period-selector/period-selector.directive.html
> +            <!-- TODO: missing some translations -->
👍

2020-05-20 23:46 UTC, diosmosis commented on plugins/CoreHome/javascripts/materialize-bc.js
> + * @link http://piwik.org
👍

2020-05-20 23:47 UTC, diosmosis commented on plugins/CorePluginsAdmin/angularjs/form-field/field-field-array.html
> +         name="formField.name"
It's because we're binding a value to the matomo-field-array directive rather than setting the name attribute.

2020-05-21 01:29 UTC, diosmosis commented
> Hovering row actions on subtable rows now show both tooltips:

I'm not sure how best to fix this one. It's due to the tooltips being nested, only way around it I can see is to add the tooltip to the label column. However if there's no cell tooltip, then it won't display over other columns...

2020-05-25 09:43 UTC, sgiehl commented on package.json
> +    "jscrollpane": "^2.2.1",
package-lock.json might still need an update

2020-06-02 09:54 UTC, sgiehl commented
Another note that came up to my mind: In the original issue we discussed if it might make sense to add the node_module files to git, so they are included in the checkout. Otherwise guess we need to adjust some guides about how using Matomo from git and also adjust the build script, as the files need to be included in the release package

2020-06-03 15:34 UTC, sgiehl commented
@diosmosis I've updated branch and also fixed some of the tiny issues I had mentioned before.
Did you already have time to look at the tooltip issue? Should imho be the last remaining one...

2020-06-03 20:02 UTC, diosmosis commented
@sgiehl the fix for the tooltip issue is to switch to materialize, which I haven't looked into yet. The archiving PRs are currently my focus.

2020-06-05 09:19 UTC, sgiehl commented
@diosmosis I've tried switching to materialize tooltips. But it's a bit more work to do as I thought. We are using callbacks in some cases to determine the content of the tooltips and whether they should be shown or not. That is not supported by materialize tooltips. So we would need to change that. Also materialize uses the same jQuery wrapper for tooltips as jquery ui, so we can't use the `.tooltip()` method anymore or would need to use a custom jquery ui build without the tooltips...

I've now pushed a hackish solution that only fixes the issue for the datatable row actions. Might be enough for the moment, as I didn't find any other overlapping tooltip yet. Maybe we can go with this solution for now and create a follow up issue to maybe even remove jquery ui completely with a later release.

2020-06-05 11:36 UTC, diosmosis commented
> I've now pushed a hackish solution that only fixes the issue for the datatable row actions. 

If it works, this sounds good to me, whatever takes the least amount of time at this point.

2020-06-07 23:46 UTC, merged