If more than one yaxis in a jqplot graph, make sure there is space on right for it.
piwik/piwik pull request #14111
Opened 2019-02-18 01:41 UTC by diosmosis

evolution graph:

![image](https://user-images.githubusercontent.com/125140/52923119-eb182c00-32da-11e9-849c-4b1495686ef0.png)

bar graph:

![image](https://user-images.githubusercontent.com/125140/52923110-d6d42f00-32da-11e9-910c-f4f79be7a585.png)

Fixes #13488

2019-02-18 11:05 UTC, sgiehl requested changes
besides the debug statement, looks good to merge

2019-02-18 11:05 UTC, sgiehl commented on plugins/CoreVisualizations/javascripts/jqplot.js
> +                    console.log(tickFormatted, $tempAxisElement.width());
debug statement should be removed

2019-02-19 06:34 UTC, diosmosis commented
Can't merge yet, some regressions in UI tests.

2019-02-25 11:49 UTC, sgiehl approved these changes

2019-02-25 11:50 UTC, sgiehl commented
Guess https://builds-artifacts.matomo.org/matomo-org/matomo/13488-right-legend/32902/EvolutionGraph_bounce_rate.png needs an update. All other UI failures seem unrelated

2019-02-26 03:25 UTC, merged