Display a warning if using an EOL version of PHP
piwik/piwik pull request #14201
Opened 2019-03-13 21:40 UTC by katebutler

Warn the user if their version of PHP is < 7.1

![image](https://user-images.githubusercontent.com/4185912/54316422-8df76800-4645-11e9-8a5b-b38299245dac.png)

Fixes #14174

2019-03-17 19:38 UTC, diosmosis approved these changes
UI tests will need to be updated before merge

2019-03-29 09:44 UTC, simivar requested changes

2019-03-29 09:44 UTC, simivar commented on core/Plugin/ControllerAdmin.php
> +        return '7.1';
Wouldn't it be better to move this to `const` and use it in line 371 as well?

2019-03-29 09:44 UTC, simivar commented on core/Plugin/ControllerAdmin.php
> +    private static function isPhpVersionAtLeast71()
What do you think about renaming that method to `isMinimalSupportedPhpVersion()` or something along this line? There will be no need to rename it in the future.

2019-03-29 21:11 UTC, tsteur approved these changes

2019-03-29 23:19 UTC, merged