Ask users to leave a review for Matomo
piwik/piwik pull request #14432
Opened 2019-05-09 04:27 UTC by katebutler

Fixes #14086 

Still to do:

- Add content (message to user and links to ProductHunt, Capterra etc) in the popup template
- Add similar content to the help page
- Prompt users to leave a review after they rate a feature with a thumbs up

2019-05-12 23:02 UTC, katebutler commented
Sample screenshot below. @Findus23 Thomas has suggested that you may be able to help with the logos for the review sites - the Product Hunt one is OK as they provide official branding resources, but the others I've just taken off the internet. They need transparent backgrounds and we may need to play around with the size a bit as well, particularly for SaasWorthy.

![](https://files.slack.com/files-pri/T97GVJVNZ-FJ85UBAUA/review-matomo-popup.png)

2019-05-28 09:08 UTC, Findus23 requested changes
Hi @katebutler,

Could you please update the images with the SVGs I sent you?
Thanks

2019-06-10 09:46 UTC, mattab commented
@katebutler can you check @Findus23 comment from 13 days ago?

2019-06-11 22:41 UTC, katebutler commented
Have replaced the icons with the SVGs. Has caused quite a few UI tests to fail because of the popup showing up over the top of the expected dashboard. My own test that the popup doesn't show up when it's not expected is also failing so hopefully once I fix that it will sort the others out.

2019-06-18 00:13 UTC, katebutler commented
Ready for review/merge

2019-06-18 01:00 UTC, mattab commented on plugins/Feedback/Controller.php
> +        if ((int)$nextReminder !== -1) {
maybe could use a const named appropriately and remove the comment?

2019-06-18 01:02 UTC, mattab commented on plugins/Feedback/angularjs/feedback-popup/feedback-popup.directive.html
> +            <input type="button" value="Remind me later" role="yes"/>
this string is not translated yet (line below as well)

2019-06-18 01:04 UTC, mattab commented on plugins/Feedback/Controller.php
> +        $nextReminder = Common::getRequestVar('nextReminder');
maybe add auth check, that user is not anonymous?

2019-06-18 03:15 UTC, mattab commented
@katebutler noticed tests are failing with:

```
There were 3 errors:
1) Piwik\Plugins\Feedback\tests\Unit\FeedbackTest::test_shouldPromptForFeedback_nextReminderDateInPast
Exception: General_ExceptionInvalidDateBeforeFirstWebsite: 2019
/home/travis/build/matomo-org/matomo/core/Date.php:161
/home/travis/build/matomo-org/matomo/plugins/Feedback/Feedback.php:96
/home/travis/build/matomo-org/matomo/plugins/Feedback/tests/Integration/FeedbackTest.php:100
2) Piwik\Plugins\Feedback\tests\Unit\FeedbackTest::test_shouldPromptForFeedack_nextReminderDateToday
Exception: General_ExceptionInvalidDateBeforeFirstWebsite: 2019
/home/travis/build/matomo-org/matomo/core/Date.php:161
/home/travis/build/matomo-org/matomo/plugins/Feedback/Feedback.php:96
/home/travis/build/matomo-org/matomo/plugins/Feedback/tests/Integration/FeedbackTest.php:108
3) Piwik\Plugins\Feedback\tests\Unit\FeedbackTest::test_shouldPromptForFeedack_nextReminderDateInFuture
Exception: General_ExceptionInvalidDateBeforeFirstWebsite: 2019
/home/travis/build/matomo-org/matomo/core/Date.php:161
/home/travis/build/matomo-org/matomo/plugins/Feedback/Feedback.php:96
/home/travis/build/matomo-org/matomo/plugins/Feedback/tests/Integration/FeedbackTest.php:116

```

2019-06-18 03:16 UTC, mattab commented
PR looks good otherwise, looking forward to merging this :+1:

2019-06-18 04:37 UTC, katebutler commented
`FeedbackTest` is now fixed.

2019-06-18 04:45 UTC, merged