Renames CustomPiwikJs plugin to CustomTrackerJs
piwik/piwik pull request #15505
Opened 2020-02-03 11:05 UTC by sgiehl

2020-02-03 19:39 UTC, tsteur commented
@sgiehl there used to be a plugin on the marketplace named `CustomTrackerJs`... just wondering if someone updates from Piwik 2.X to Matomo 4.X if this could cause any issues? I suppose that plugin would be simply overwritten? (which be kind of good since it would also automatically remove an outdated / not compatbile plugin) or is easier to rename it to `CustomJsTracker`?

2020-02-04 06:58 UTC, sgiehl commented
Guess it would be overwritten, but not sure if some old files might remain 🤷‍♂ 
Not having a preference here. Can also rename it...

2020-02-04 20:07 UTC, tsteur commented
Up to you. If we keep the name, might be worth testing what happens when upgrading from Piwik 2 and such a plugin existed. Might be easier to maybe rename it?

2020-02-05 17:39 UTC, sgiehl commented
renamed it again. Need to update the UI tests again, I guess. But should be ready for another review

2020-02-06 22:00 UTC, tsteur requested changes
Left a few minor comments, nothing major. Mostly around docs.

Adjusted already 6 or so internal plugins. Be good to make the changes in tag manager and resolve the open issues then be good to merge

2020-02-07 08:12 UTC, sgiehl commented on core/Updates/4.0.0-b1.php
> +        $this->renameTrackerJsPluginInConfig();
I'll adjust the old update script to activate `CustomJsTracker` instead. That way it should be activated if someone updates from an older version

2020-02-07 08:44 UTC, sgiehl commented on core/Updates/4.0.0-b1.php
> +        $config = Config::getInstance();
Not that easy. The plugin `CustomPiwikJS ` won't be reported as active as soon as it is missing on file system. But an `uninstall` should work. Will build a migration for that

2020-02-07 08:46 UTC, sgiehl commented
@tsteur applied the feedback

2020-02-09 20:47 UTC, tsteur commented
Looks good in general @sgiehl some tests will need fixing though

2020-02-10 08:56 UTC, sgiehl commented
Guess tests are failing because the changes in tagmanager are needed. will push a submodule change to prove that.

2020-02-10 10:36 UTC, sgiehl commented
Tests seem to pass again. Before merging we need to merge https://github.com/matomo-org/tag-manager/pull/220 and update the submodule ref here.

2020-02-11 08:05 UTC, merged