Add movers and shakers widget to dashboard
piwik/piwik pull request #15578
Opened 2020-02-16 23:27 UTC by tsteur

fix https://github.com/matomo-org/matomo/issues/13153

2020-02-17 08:37 UTC, sgiehl commented on plugins/Insights/tests/Integration/ApiTest.php
> +        $this->true($this->api->canGenerateInsights('2012-11-11,2012-12-12', 'range'));
```suggestion
        $this->assertTrue($this->api->canGenerateInsights('2012-11-11,2012-12-12', 'range'));
```

2020-02-17 08:41 UTC, sgiehl requested changes
One test is failing and the UI tests will need some updates

2020-02-17 21:10 UTC, tsteur commented
Tests should hopefully be fixed now @sgiehl

2020-02-18 08:09 UTC, sgiehl approved these changes

2020-02-18 08:09 UTC, merged