Prevent server gone away error in CronArchive
piwik/piwik pull request #15619
Opened 2020-02-24 20:08 UTC by tsteur

What happens is basically eg some archive requests run for 6 hours, then it returns back into the `CronArchive` scripts, it tries to execute a query, and results in a server gone away error because the DB connection wasn't used for hours.

Fixes only when a CronArchive happens directly in CronArchive.php script. We've tested this in production for one month and worked nicely.

2020-02-25 09:32 UTC, sgiehl requested changes

2020-02-25 09:32 UTC, sgiehl commented on core/CronArchive.php
> +        }
That seems to be dead code. `$this->lastDbReset = time();` is already done in `__construct`, so the value can't ever be empty

2020-02-25 21:24 UTC, tsteur commented
@sgiehl updated

2020-02-26 07:50 UTC, sgiehl approved these changes

2020-02-26 07:50 UTC, merged