Fixes lot of things
piwik/piwik pull request #15648
Opened 2020-03-02 16:32 UTC by tolbon

Convert certain Tabs to Spaces,
Fix PHP Docs
Type declaration in function
Fix potential php errors

2020-03-02 16:59 UTC, sgiehl requested changes
Left a couple of comments. Not sure if any type hint might cause any problems, but we'll see if the tests are still passing...

2020-03-02 16:59 UTC, sgiehl commented on core/Period.php
> +     * @param string $period string The **period** query parameter value.
```suggestion
     * @param string $dateString The **date** query parameter value.
     * @param string $period The **period** query parameter value.
```

2020-03-02 16:59 UTC, sgiehl commented on libs/upgradephp/upgrade.php
> + * @author Andrew Sohn <asohn (at) aircanopy (dot) net>
moving the author blocks and adding an empty line between them doesn't make things better...

2020-03-02 16:59 UTC, sgiehl commented on libs/upgradephp/upgrade.php
> + * @author BigueNique AT yahoo DOT ca
same as above

2020-03-02 16:59 UTC, sgiehl commented on plugins/CoreHome/DataTableRowAction/RowEvolution.php
> +        $unmodifiedSeriesLabels = [];
Guess the exact same line can then be removed a few lines below

2020-03-02 16:59 UTC, sgiehl commented on plugins/CoreVisualizations/Visualizations/Sparklines.php
>              $comparisonRows = [];
That line can be removed then, I guess
```suggestion
```

2020-03-02 16:59 UTC, sgiehl commented on plugins/Installation/FormFirstWebsiteSetup.php
> +            $location = [];
not necessarily needed, but doesn't hurt...

2020-03-03 09:13 UTC, tolbon commented
I see lot of failing compilation introduce by my modification I fix this asap

2020-03-03 15:44 UTC, tolbon commented
I need help a test don't pass but I don't see where I need to revert 
https://travis-ci.org/matomo-org/matomo/jobs/657749446#L877
https://travis-ci.org/matomo-org/matomo/jobs/657749446#L925

I didn't find where this xml is generated

2020-03-03 19:17 UTC, sgiehl commented
you can ignore the both tests mentioned. They are failing on 4.x-dev as well. Guess that's a sorting issue between PHP 7.2 and PHP 7.3 or something like that.

2020-03-03 20:26 UTC, tolbon commented
I know it’s too late but ...
My commit is very big, Very hard for you to reviews this no ? Can I do something 
Do you want I close this PR and do more little  PR ?

2020-03-04 08:50 UTC, sgiehl commented
Having smaller PRs makes it a lot easier to review and check why tests are failing. This PR has still a lot failing tests, but it's hard to say which change made them fail. So might be better to split the changes

2020-03-04 09:17 UTC, tolbon commented
Yeah I close this and make little Pull Request, sorry for this

2020-03-04 09:17 UTC, closed without merging