idsegments as option
piwik/piwik pull request #15753
Opened 2020-03-30 16:15 UTC by mikkeschiren

2020-04-06 13:35 UTC, diosmosis requested changes
Thanks @mikkeschiren for creating your first contribution! I left some comments in the review, let me know if you have any questions or need some help.

2020-04-06 13:35 UTC, diosmosis commented on plugins/CoreAdminHome/Commands/InvalidateReportData.php
> +        }
I think the code here can be simplified. `$segments = $this->getSegmentsToInvalidateFor($input, $sites);` is executed no matter what but can be called twice if `--segment` is supplied. And the `if (isset($idsegments)) {` block could be located next to `$idsegments` w/o the `if`. Can you make these changes?

2020-04-06 13:35 UTC, diosmosis commented on plugins/CoreAdminHome/Commands/InvalidateReportData.php
> +        $idSegments = preg_replace('/\s/', '', $idSegments);
`trim` and `preg_replace` are redundant here. Only the preg_replace is needed.

2020-04-06 13:35 UTC, diosmosis commented on plugins/CoreAdminHome/Commands/InvalidateReportData.php
> +        $idSegments = array_map('trim', $idSegments);
W/ the preg_replace above, this call isn't necessary.

2020-04-06 13:35 UTC, diosmosis commented on plugins/CoreAdminHome/Commands/InvalidateReportData.php
> +                return $e->getMessage();
Since this method should return an array of segments, if an error is encountered, can you just output a warning/error and ignore the segment?

2020-04-06 13:35 UTC, diosmosis commented on plugins/CoreAdminHome/Commands/InvalidateReportData.php
> +        }
What's the reason for returning `[null]`? Should it instead return an empty array so nothing is invalidated? Given it's unexpected we could also output a warning here.

2020-05-08 02:45 UTC, tsteur commented
@mikkeschiren thanks a lot for this PR. Very appreciated. Do you mind looking at the comments from @diosmosis ?

2020-08-27 03:43 UTC, tsteur commented
@mikkeschiren as mentioned in previous comment could you look at the comments from @diosmosis ?

2020-08-31 03:24 UTC, tsteur commented
@mikkeschiren I'll close this PR for now as there has been no response to the comments in quite a while but we'll be very happy to do another review should you continue with this PR

2020-08-31 03:24 UTC, closed without merging