Send onboarding email during installation
piwik/piwik pull request #15894
Opened 2020-05-01 04:50 UTC by tsteur

Refs MAR-777

![image](https://user-images.githubusercontent.com/273120/80782750-84bfb680-8bcb-11ea-9ebc-c14c237de7f2.png)

In my case it went into spam since the sender was basically `foo@mbp.localdomain`. Not sure how often sending the mail actually works when no proper SMTP is configured and how often it would go to spam? Any thoughts @mattab @Findus23 

I'm catching any error that happens so hopefully this doesn't influence

2020-05-02 08:22 UTC, Findus23 commented
In theory it should never matter if you are using SMTP or PHP mail (and therefore `sendmail`), at least once we are using PHPMailer for both.

But maybe we should make the fact that the from address can not be detected automatically and this FAQ more prominently. Maybe even add a system check that looks up if the from mail ends with `.localdomain` or something like this.

https://matomo.org/faq/how-to/faq_109/

2020-05-11 13:22 UTC, sgiehl requested changes

2020-05-11 13:22 UTC, sgiehl commented on plugins/Installation/Onboarding.php
> +        if (!$testMode) {
That should actually not be needed, as it's already done in the mail class. See 
https://github.com/matomo-org/matomo/blob/da92367838fa85b806dfd2486b6e91c308cb5e46/core/Mail.php#L127-L135

2020-05-11 13:22 UTC, sgiehl commented on plugins/Installation/Onboarding.php
> + * Piwik - free/libre analytics platform
```suggestion
 * Matomo - free/libre analytics platform
```

2020-05-11 21:34 UTC, tsteur commented
Made the changes @sgiehl

2020-05-13 23:21 UTC, tsteur commented
@sgiehl I suppose it is good to merge now?

2020-05-13 23:23 UTC, Findus23 commented
I still think that the subject line looks like a random SPAM mail.

2020-05-14 19:51 UTC, tsteur commented
@Findus23 changed it 👍

2020-05-15 14:00 UTC, sgiehl approved these changes
Tested that locally again and it seems to work as expected

2020-05-17 20:24 UTC, merged