Offer feature to anonymise or shorten the referrer
piwik/piwik pull request #16376
Opened 2020-09-03 20:10 UTC by tsteur

refs #15426

2020-09-16 23:00 UTC, tsteur commented on plugins/PrivacyManager/Diagnostic/PrivacyInformational.php
> +            $results[] = DiagnosticResult::informationalResult('Anonymize Referrer', $config->anonymizeReferrer);
not translated as it's mostly info for us

2020-09-30 16:01 UTC, sgiehl requested changes

2020-09-30 20:55 UTC, tsteur commented on plugins/PrivacyManager/templates/privacySettings.twig
> +             inline-help="{{ 'PrivacyManager_AnonymizeReferrerNote'|translate|e('html_attr') }}">
I reckon it's not needed cause you can't control what kind of referrer information gets sent to you so there could be any kind of url parameter coming

2020-09-30 20:56 UTC, tsteur commented on plugins/PrivacyManager/PrivacyManager.php
> +                $view->config->show_footer_message .= sprintf('Some referrer information may be missing because referrer anonymisation is enabled as following: %s', $methods[$config->anonymizeReferre
Definitely, updated

2020-09-30 20:56 UTC, tsteur commented
@sgiehl applied the changes

2020-10-01 06:49 UTC, sgiehl approved these changes

2020-10-01 20:13 UTC, merged