Rename login whitelist to allowlist
piwik/piwik pull request #16413
Opened 2020-09-09 19:56 UTC by tsteur

2020-09-30 09:33 UTC, sgiehl requested changes

2020-09-30 19:23 UTC, tsteur commented on config/global.php
> +    'login.allowlist.ips' => function (ContainerInterface $c) {
DI configs aren't API currently and AFAIK not documented anywhere etc. They are basically just for us so far

2020-09-30 19:33 UTC, tsteur commented on plugins/CoreHome/tests/Integration/LoginAllowlistTest.php
>          $this->setGeneralConfig('login_whitelist_apply_to_reporting_api_requests', '0');
I'll commit this separately. I partially left some with whitelist to make sure we still support the previous setting re BC  but will rather add an extra test for it

2020-09-30 19:34 UTC, tsteur commented on core/API/Request.php
>              // to not expose any information in case the IP is not whitelisted.
will commit it separately

2020-09-30 19:35 UTC, tsteur commented on config/global.ini.php
>  ; Set this setting to "0" to allow HTTP Reporting API requests from any IP address.
will do 👍

2020-09-30 19:48 UTC, tsteur commented
@sgiehl applied the review comments. replaced the word also in few other places but not in places like the validator or so when it requires changes across plugins as it's not as easy to do and needs a separate PR anyway

2020-10-01 10:59 UTC, sgiehl commented on plugins/CoreHome/LoginAllowlist.php
> +        return !empty($general['login_allowlist_apply_to_reporting_api_requests']) || !empty($general['login_whitelist_apply_to_reporting_api_requests']);
The fallback to the old name might actually not work as expected in all cases as the default value of those setting is `1`.
Lets say someone does not configure `login_allowlist_apply_to_reporting_api_requests`, but uses `login_whitelist_apply_to_reporting_api_requests = 0`. That would actually not work, as `login_allowlist_apply_to_reporting_api_requests` defaults to `1`.

I guess that might be fine, as `login_allowlist_apply_to_reporting_api_requests` will be set on update if needed, but actually I think we could remove the fallback here then...

2020-10-01 10:59 UTC, sgiehl commented
Seems you added the screenshot directly, and not to LFS...

2020-10-01 20:12 UTC, tsteur commented
fixed

2020-10-01 20:12 UTC, merged