Improve handling of current user information for Filechecks
piwik/piwik pull request #16941
Opened 2020-12-12 17:29 UTC by aragon999

### Description:
I had a PHP Notice:
```
PHP Notice:  Trying to access array offset on value of type bool in Filechecks.php:205
```
while the actual problem was, that I was inside a docker container and had the wrong group-id assigned.

I only had a notice, since the user permissions still worked, but I think that place needs better handling. This PR is a first try to improve the situation.

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

2020-12-14 00:04 UTC, diosmosis requested changes
Thanks for the first contribution @aragon999 ! I requested some changes, but in general I think this change is fine to include given the new logic is only meant to be used if we cannot find a user/group through existing methods. 👍

2020-12-14 00:04 UTC, diosmosis commented on core/Filechecks.php
> +            if (is_array($group)) {
Instead of is_array, it would be better to use `!empty($group['name'])` (same for the other similar if statements).

2020-12-14 00:04 UTC, diosmosis commented on core/Filechecks.php
> +        if (empty($currentUser) && function_exists('posix_getegid') && function_exists('posix_getgrgid')) {
I think `$currentUser` here is meant to reference `$user`, correct?

2020-12-14 09:48 UTC, aragon999 commented on core/Filechecks.php
> +        if (empty($currentUser) && function_exists('posix_getegid') && function_exists('posix_getgrgid')) {
No it actually should be `$group` :-) But that was a typo, thank you!

2020-12-14 09:49 UTC, aragon999 commented on core/Filechecks.php
> +            if (is_array($group)) {
Okay, changed that.

2020-12-15 00:14 UTC, merged

2020-12-15 00:14 UTC, diosmosis commented
I merged this, @aragon999, thanks again for the contribution!