Introduce new config setting to set a contact email address
piwik/piwik pull request #17916
Opened 2021-08-24 14:35 UTC by sgiehl

### Description:

There are currently a few places where a user is suggested to contact the administrator of the Matomo instance. In most cases there is a `mailto` link that contains the email addresses of all super users.

In some scenarios it might be unexpected that in this places the (possibly private) mail addresses are disclosed.
To avoid this, this PR introduces as new config setting to set a contact email address, that will be used for those links instead.
By default this config setting isn't set and it falls back to use all super users emails.

In companies for example it might be more helpful to send an email to a support mailbox instead of sending an email to some specific persons.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-08-27 14:23 UTC, Schwuuuuup commented
As the author of the mail to security@matomo.org, that lead to this PR, I just wanted to say thank you. And I hope that the build and Merge Issues can be fixed

2021-10-18 18:48 UTC, tsteur requested changes
looks generally good. A UI test will need fixing though https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/50182/UIIntegrationTest_admin_diagnostics_configfile.png

Could you also create an FAQ for this? And where else would we mention this? Maybe in security guide?

2021-10-18 18:48 UTC, tsteur commented on plugins/CorePluginsAdmin/templates/safemode.twig
> +                <a href="mailto:{{ contactEmail }}?subject={{ 'Fatal error in Matomo ' ~ piwikVersion|e('url') }}&body={{ lastError.message|e('url') }}%20in%20{{ lastError.file|e('url') }}%20{{ lastE
does it need to be `|e('html_attr')` for contactEmail?

2021-10-18 18:48 UTC, tsteur commented on plugins/CorePluginsAdmin/templates/safemode.twig
> +                <a href="mailto:{{ contactEmail }}?subject={{ 'Fatal error in Matomo ' ~ piwikVersion|e('url') }}&body={{ lastError.message|e('url') }}%20in%20{{ lastError.file|e('url') }}%20{{ lastE
below in other ones we use `url` strategy, not sure if that's right

2021-10-18 18:48 UTC, tsteur commented on plugins/Morpheus/templates/ajaxMacros.twig
> +                {{ 'General_ErrorRequest'|translate('<a href="mailto:' ~ contactEmail ~ '">', '</a>')|raw }}
same here should maybe also escape?

2021-10-20 14:17 UTC, sgiehl commented on plugins/CorePluginsAdmin/templates/safemode.twig
> +                <a href="mailto:{{ contactEmail }}?subject={{ 'Fatal error in Matomo ' ~ piwikVersion|e('url') }}&body={{ lastError.message|e('url') }}%20in%20{{ lastError.file|e('url') }}%20{{ lastE
tested it a bit and seems `e('url')` works as expected for that case.

2021-10-28 02:46 UTC, tsteur commented
@sgiehl if tests pass this should be good to merge

2021-10-28 07:31 UTC, merged