add http to https error message on nonce check
piwik/piwik pull request #18051
Opened 2021-09-23 04:25 UTC by peterhashair

### Description:

Add HTTP to HTTPS error message on nonce check

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-10-04 09:41 UTC, Findus23 commented
Honestly I meant in #16607 that we should log or output more precisely which one of the many checks in https://github.com/matomo-org/matomo/blob/679e73f1236969db0c2d767655cb84456a727d24/core/Nonce.php#L70 and https://github.com/matomo-org/matomo/blob/06d43857c48ada2fa7f1ad18a8309e8826c0e413/core/Url.php#L547 fails instead of leaving the user guessing and debugging Matomo code. 

Adding the sentence by @Starker3 is also fine, but doesn't affect the core issue I meant.

@peterhashair unrelated, but it would be great if you could link issues in the PR description, so one can directly jump back to them instead of searching for the linked issue in the sidebar. And if you use something like `fixes #1234`, you don't need to manually link them either.

2021-10-05 00:11 UTC, peterhashair commented
@Findus23 add the fixes number, I don't even know that, thanks for the hints :). If I understand correctly, we want to split the verifyNonce into details with their own error messages, instead of combining them into one error log?

2021-10-08 04:40 UTC, tsteur commented on core/Nonce.php
> +    public static function verifyNonce($id, $cnonce, $expectedReferrerHost = null, bool $withErrorMessage = false)
@peterhashair could we maybe rather have two different methods `verifyNonceWithErrorMessage` (there's likely better wording for it) and `verifyNonce`? That will reduce the complexity of the method a bit and often boolean parameters indicate that it should be maybe two methods. You can still reuse the code like 


```
public static function verifyNonce($id, $cnonce, $expectedReferrerHost = null){
    $error = self::verifyNonceWith...($id, $cnonce, $expectedReferrerHost);
    return empty($error);
}
```

2021-10-10 22:01 UTC, tsteur commented on core/Nonce.php
> +            return Piwik::translate('Login_InvalidNonceReferrer');
@peterhashair is there any chance we can slightly tweak the two same `InvalidNonceReferrer` messages to have them bit different? when users report us that they have a problem we'll then better know what the problem is.

2021-10-11 02:47 UTC, peterhashair commented
@tsteur split the error message,  but I don't think $expectedReferrerHost is used anywhere.  Should we set a variable in config.ini.php that reflected that value?

2021-10-11 03:09 UTC, tsteur requested changes
@peterhashair left a comment as there's an issue with a translation.

Also the method `getMessageExceptionNoAccess` method in the login controller seems to be no longer used and we could remove it now?

The translation key `Login_InvalidNonceOrHeadersOrReferrer` seems to be still used in the `TwoFactorAuth/Controller`. Maybe in that controller we could similarly use the new method in the `loginTwoFactorAuth` to get the reason why the nonce check fails? Then we could remove the translation key `Login_InvalidNonceOrHeadersOrReferrer`.
![image](https://user-images.githubusercontent.com/273120/136728027-56370ae9-9e09-412d-bbfc-56e8aeeb6526.png)

2021-10-11 03:09 UTC, tsteur commented on plugins/Login/lang/en.json
> +        "InvalidNonceReferrer": "Form security failed, invalid referrer header, If you use a proxy server, you must %1$s configure Matomo to accept the proxy header%2$s that forwards the Host header.
There are placeholders used but no value is actually passed to them in the translate method. When this error happens it looks like this:

![image](https://user-images.githubusercontent.com/273120/136727144-687cccf7-f2a3-4a33-bb27-4d7704a79f7b.png)
There should be also a dot (`.`) after `invalid referrer header` instead of a comma (`,`).

2021-10-11 03:09 UTC, tsteur commented on plugins/Login/lang/en.json
> +        "InvalidNonceUnexpectedReferrer" : "Form security failed, the referrer header is different from the expected referrer header, check that your Referrer header is sent correctly.",
I wonder how someone would check if the referrer header is sent correctly. But let's ignore this for now as I suppose we can ignore it a bit for now as `$expectedReferrerHost` isn't used there so far. Nothing to do for now I reckon. Seems to be indeed not used in the code base.

2021-10-11 03:09 UTC, tsteur commented on plugins/Login/lang/en.json
> +        "InvalidNonceOrigin": "Form security failed, invalid origin, If you previously connected using https, please ensure you are connecting over a secure (SSL/TLS) connection and try again",
Can we use a dot after `invalid origin` instead of a comma?

2021-10-11 04:55 UTC, peterhashair commented
- deprecated getMessageExceptionNoAccess Login/controller
- deprecated  InvalidNonceOrHeadersOrReferrer in lang
- move getMessageExceptionNoAccessWhenInsecureConnectionMayBeUsed from Login/controller to core/Nonce
- fix missing 2 variables in translation.

2021-10-12 02:51 UTC, tsteur commented
@peterhashair just tested it when `Url::isSecureConnectionAssumedByPiwikButNotForcedYet== true`

It now shows this 
![image](https://user-images.githubusercontent.com/273120/136882904-6820d471-8505-41a3-99b8-6c6a96faa9cb.png)

it doesn't look quite correct? I think previously it was appended to any error message.

2021-10-12 03:06 UTC, peterhashair commented
@tsteur sorry, I thought that was a generic error. Changed it back, now should only appear when the error appears.

2021-10-12 03:51 UTC, tsteur requested changes
@peterhashair last 2 comments to add a `dot` at the end of sentences. Then it should be good to merge.

2021-10-12 03:51 UTC, tsteur commented on plugins/Login/lang/en.json
> +        "InvalidNonceToken": "Form security failed, token miss match. Please reload the form and check that your cookies are enabled",
here we need to add a dot at the end
![image](https://user-images.githubusercontent.com/273120/136888159-a7aa1e9c-8dc4-4cfb-9af2-6219d7fa09b6.png)

2021-10-12 03:51 UTC, tsteur commented on plugins/Login/lang/en.json
> +        "InvalidNonceOrigin": "Form security failed, invalid origin. If you previously connected using https, please ensure you are connecting over a secure (SSL/TLS) connection and try again",
same here we need to add a dot here

2021-10-12 03:51 UTC, tsteur commented on core/Nonce.php
> +     * @param null $expectedReferrerHost The expected referrer host for the HTTP referrer URL.
not too important, could change this to `null|string`

2021-10-13 00:54 UTC, merged