add last seen to the UserManager Api
piwik/piwik pull request #18053
Opened 2021-09-23 07:58 UTC by peterhashair

### Description:

add the last seen field to the UserManager.getUsers Api. 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-09-24 11:12 UTC, peterhashair commented
For the api date_last_seen maybe is not a propery word, if we addt ime onto as its value.  Suggest use last_seen if we want to use time, or we can remove the time, date_last_seen=date. Also for the time zone , should I use gmdate or just use date.

2021-09-24 15:38 UTC, sgiehl requested changes

2021-09-24 15:38 UTC, sgiehl commented on plugins/UsersManager/API.php
> +        {
minor coding style improvement, so it matches the other code
```suggestion
        if ($lastSeen = LastSeenTimeLogger::getLastSeenTimeForUser($user['login'])) {
```

2021-09-24 15:38 UTC, sgiehl commented on plugins/UsersManager/tests/Integration/UsersManagerTest.php
> +     * @todo
Is anything still left to do, or is this comment outdated?

2021-09-24 15:38 UTC, sgiehl commented on plugins/UsersManager/API.php
> +            $user['date_last_seen'] =  gmdate("Y-m-d\TH:i:s\Z", $lastSeen);
I guess we use to return the date format `Y-m-d H:i:s` in other places. See https://github.com/matomo-org/matomo/blob/c973567705a0065fdd7d7c7b11b80f1f0f1be350/core/Date.php#L389-L398

2021-09-27 08:22 UTC, sgiehl commented on plugins/UsersManager/API.php
> +            $user['last_seen'] = date("Y-m-d H:i:s", $lastSeen);
Guess we could use this here:
```suggestion
            $user['last_seen'] = Date::getDatetimeFromTimestamp($lastSeen);
```

2021-09-27 15:56 UTC, sgiehl approved these changes

2021-09-27 15:56 UTC, merged