[Vue] Adding a "build vue" github action to build vue files
piwik/piwik pull request #18080
Opened 2021-09-29 21:51 UTC by diosmosis

### Description:

I haven't used github actions before so this is mostly a guess. @sgiehl can you take a look and see if there's anything off? I'm also not entirely sure how to test this. Unless I can invoke the action in this PR w/o merging into 4.x-dev?

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-09-30 10:08 UTC, sgiehl commented
It can only be executed/tested when it's in the base branch. But you could create a fork where you add the action in the base branch to test it on the fork.

2021-10-12 01:45 UTC, diosmosis commented
@sgiehl / @tsteur this is ready for review. The action will now always run for every PR, build vue files, and if there are changes, will push to the PR so the files are always up to date.

2021-10-13 01:30 UTC, tsteur commented
@diosmosis looks overall good to me. Might wait with merging until @sgiehl is back from holidays.

Sometimes there might be merge conflicts when different PR changed files in a same plugin etc. In that case we simply need to rebase 4.x-dev into the branch, possibly resolve merge conflicts manually (probably would need to call the build command ourselves) and commit again? 

Not sure if I fully understand what the action does.

2021-10-13 01:43 UTC, diosmosis commented
> Not sure if I fully understand what the action does.

It just runs `vue:build` every time a PR is updated, and if there are changes, commits them (in case a developer forgets to re-compile).

> Sometimes there might be merge conflicts when different PR changed files in a same plugin etc. In that case we simply need to rebase 4.x-dev into the branch, possibly resolve merge conflicts manually (probably would need to call the build command ourselves) and commit again?

Mostly, yes. The UMD files don't need to be looked at, other merge conflicts have to be handled, then either run build manually, or push and this command would build again. It doesn't solve the case where the merge is fine *except* for the UMD files which we just want to build again. Not sure there's a way around that.

2021-10-18 09:33 UTC, sgiehl requested changes

2021-10-18 09:33 UTC, sgiehl commented on .github/workflows/buildvue.yml
> +on: pull_request
Should we restrict the types here? Currently it would run for any change of a pull request (including the change of labels,  assignee, review state or when closing a pull request). See https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request

2021-10-18 09:33 UTC, sgiehl commented on .github/workflows/buildvue.yml
> +        if: steps.vars.outputs.branch != ''
As this command is executed automatically when a pull request is changed, I wonder if we should add an additional check if a vue file was actually changed in this pull request and abort the execution otherwise.

2021-10-18 15:15 UTC, diosmosis commented on .github/workflows/buildvue.yml
> +on: pull_request
:+1: only done on synchronize now

2021-10-18 15:15 UTC, diosmosis commented on .github/workflows/buildvue.yml
> +        if: steps.vars.outputs.branch != ''
:+1: done

2021-10-18 15:17 UTC, diosmosis commented
@sgiehl updated the pr

2021-10-19 14:58 UTC, sgiehl commented on .github/workflows/buildvue.yml
> +          VUE_FILES_MODIFIED=$(git diff HEAD^ --name-only plugins/*/vue/**/* | wc -l)
wouldn't this only look at the last commit? So if someone pushes multiple commits including some vue files, but the last commit doesn't contain any it would abort here?

2021-10-19 16:51 UTC, diosmosis commented on .github/workflows/buildvue.yml
> +          VUE_FILES_MODIFIED=$(git diff HEAD^ --name-only plugins/*/vue/**/* | wc -l)
Ok, checking the base branch now. So it will always rebuild even if the last set of commits doesn't modify vue file, but somewhere the PR does.

2021-10-19 16:54 UTC, diosmosis commented on .github/workflows/buildvue.yml
> +          VUE_FILES_MODIFIED=$(git diff HEAD^ --name-only plugins/*/vue/**/* | wc -l)
ping @sgiehl

2021-10-19 17:03 UTC, diosmosis commented on .github/workflows/buildvue.yml
> +          VUE_FILES_MODIFIED=$(git diff HEAD^ --name-only plugins/*/vue/**/* | wc -l)
actually, nvm, it seems non-trivial to be able to reference commits/branches before the checkout command is run

2021-10-19 23:18 UTC, diosmosis commented
@sgiehl ok, it's working now

2021-10-20 06:38 UTC, sgiehl commented on .github/workflows/buildvue.yml
> +on:
Might make sense to make it possible to manually trigger that action for a branch maybe:

```suggestion
on:
  workflow_dispatch:
```

2021-10-20 06:39 UTC, sgiehl reviewed
Left another comment. Otherwise I guess it looks fine. Hard to test though. So guess we should merge and adjust it later if anything doesn't work as expected.

2021-10-20 16:46 UTC, diosmosis commented on .github/workflows/buildvue.yml
> +on:
I don't think this makes sense, since right now it will always run. I think it's better not to have to think about when it should be run? Especially since this is a safeguard for when people have already forgotten. If the command doesn't work for some reason, we can always build manually until its fixed.

2021-10-20 16:47 UTC, diosmosis commented
@sgiehl left a reply above. @tsteur do you want to take a look at this as well?

2021-10-20 19:19 UTC, tsteur commented
@diosmosis had a very quick look and looks all good to me. Looks good to merge to me and we can always change things as needed IMO

2021-10-20 20:15 UTC, merged