set table head sticky
piwik/piwik pull request #18124
Opened 2021-10-11 01:02 UTC by peterhashair

### Description:

Fixes: #3513 

update table heads to sticky.

The sticky head will trigger on the first time load, not on screen resize, if you change screen size probably needs to reload the page. let me know if we want to have that on-screen resize. 

On normal screen ![image](https://user-images.githubusercontent.com/3783072/136719761-f3914c0e-0674-4586-ba53-82b0ff912abe.png)

On the smaller device, I used to set the table body to scroll so the header stick on top,  but doesn't seems really good, and failed lots of UI test, so when the table x-axis is overflowed sticky head won't work. Let me know if we want to enable this. 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-10-11 21:41 UTC, bx80 submitted a review, later dismissed
Works well for me. Probably not important but I noticed that with this change Firefox now shows a console warning "Relative positioning of table rows and row groups is now supported. This site may need to be updated because it may depend on this feature having no effect."

2021-10-11 22:19 UTC, peterhashair commented
@bx80 good spot, update a little bit, should stop the warning now.

2021-10-12 01:34 UTC, tsteur commented
@peterhashair the tests are failing see https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/49914/ this also happens for me locally

![image](https://user-images.githubusercontent.com/273120/136876006-3f619707-ac76-40e7-97f6-dbf905a156e7.png)
![image](https://user-images.githubusercontent.com/273120/136876027-6e6797af-9ac7-4121-9798-238fdda4d59b.png)

2021-10-12 02:26 UTC, peterhashair commented
@tsteur right, sorry the firefox warning fix broken it, revert it back. should be fine now.

2021-10-13 22:04 UTC, tsteur commented
@peterhashair I haven't tested yet but looking at the tests there might be still issues? eg https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/49937/UIIntegrationTest_dashboard2.png 
![image](https://user-images.githubusercontent.com/273120/137218953-dc952722-280b-410d-a107-71a6c926e5c4.png)

2021-10-14 22:55 UTC, peterhashair commented
@tsteur  should work now 😬

2021-10-15 02:58 UTC, tsteur commented
I've tested this in few different browsers and mostly worked well. It's pretty awesome! 🚀 

I think it's expected it doesn't work on mobile?

There are still few issues though like this one below:

![image](https://user-images.githubusercontent.com/273120/137425037-b4174df0-f545-43de-a928-a38a0d97601b.png)

I see the same still in the UI test failures: eg in https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/50077/UIIntegrationTest_metric_tooltip.png

There is also https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/50077/UIIntegrationTest_goals_overview.png

Not sure if this is because of this PR? It doesn't seem related but then the test worked in another 4.x-dev build. Maybe it's a random build failure.

2021-10-15 04:00 UTC, peterhashair commented
@tsteur  it doesn't work on mobile, to work on mobile probably needs to restructure the entire table to a div, quite a big change. Let me know if we want to do that.

2021-10-18 21:30 UTC, tsteur commented
> to work on mobile probably needs to restructure the entire table to a div, quite a big change. Let me know if we want to do that.

Not needed  for now 👍 

Do you know why eg this screenshot test is failing now https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/50151/UIIntegrationTest_goals_overview.png ?

@sgiehl if you could give this one a test too that be great

2021-10-18 23:58 UTC, peterhashair commented
@tsteur I am not too sure why this [https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/50151/UIIntegrationTest_goals_overview.png](https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/50151/UIIntegrationTest_goals_overview.png ) failed, on my local it's fine.

2021-10-20 09:33 UTC, sgiehl commented on plugins/CoreHome/stylesheets/dataTable/_dataTable.less
>  }
Is there any specific reason for this "complexity"? Wondering why `overflow-x: scroll;` can't be set globally for `div.dataTableScroller` as before. If it needs to be changed for `.card-content`, guess it can be overwritten only there?
Btw. not having it globally causes the "regression" that the right border in widgetized reports isn't correct anymore. Which is visible in the UI screenshot changes.

2021-10-20 13:18 UTC, sgiehl commented on plugins/CoreHome/stylesheets/dataTable/_dataTable.less
>  }
Ah, I see. That's partially needed for the sticky header to work. But Imho the result now looks ugly if the table is too big:

![image](https://user-images.githubusercontent.com/1579355/138100486-278eade8-3565-4e75-8247-0b63258a2437.png)

2021-10-20 20:55 UTC, peterhashair commented
@sgiehl yeah, not the best appoach, I am trying to find those table looks ugly and not apply stick header, I was trying javascript find the width wider than the card, then apply stick header, but doesn't really work so well. Most people use scroll body instead of the scroll the whole page, but that means users need to hover the table to scroll. Here is a example
[https://codepen.io/pen?&editors=101](https://codepen.io/pen?&editors=101)

2021-10-21 08:39 UTC, sgiehl commented
Yes. Having the body scroll y combined with an scroll x in the table seems not to work with sticky headers. I'm not sure what the best approach would be, but having overlapping or completely hidden content doesn't sound like a good solution. We for sure could try to implement sticky headers using javascript, but not sure if that would be out of scope for now. ping @tsteur

2021-10-22 01:23 UTC, tsteur commented
How much time would it take to get a JS solution to work roughly?

As it's more complex than expected I'm thinking maybe we just don't do it.

2021-10-23 00:32 UTC, peterhashair commented
@tsteur I don't think it will take long, the first commit is a javascript solution it works, but it failed the UI test, maybe just need to alter the UI test

2021-10-25 21:57 UTC, tsteur commented
👍  @peterhashair sounds good to give it a try then. Let's restrict it to spend max 4 hours for now and then re-assess if needed.

2021-10-27 02:48 UTC, peterhashair commented
@tsteur I think this is working, but needs to update a submodule screenshots

2021-10-28 10:24 UTC, sgiehl requested changes
The new solution actually doesn't make sticky headers work in all cases. It kind of disables them for a table that is too wide and only works if the table fits. But imho that approach would be better than having nothing. ping @tsteur

2021-10-28 10:24 UTC, sgiehl commented on plugins/CoreHome/javascripts/dataTable.js
> +        console.log(tableWidth);
```suggestion
```

2021-10-28 10:24 UTC, sgiehl commented on plugins/CoreHome/javascripts/dataTable.js
> +      $(window).resize(function () {
This needs to be triggered at least once when the table was loaded/rendered. Otherwise the table will overlap per default, but fit, once the window is resized.

2021-11-02 10:10 UTC, sgiehl commented on plugins/CoreHome/stylesheets/dataTable/_dataTable.less
> +.widgetContent,.reportContainer {
This actually prevents the sticky header from working in the goals reports, even if there would be enough space.
It's actually not needed anymore as the javascript will add the scrollbar if needed.
```suggestion
.widgetContent {
```

2021-11-02 10:13 UTC, sgiehl approved these changes
This should be good to merge now. Will wait for the tests before merging. Maybe they need another update.

2021-11-02 10:57 UTC, sgiehl commented
Failing tests are unrelated, so merging now.

2021-11-02 10:57 UTC, merged