Added functionality to filter getReportMetadata and getSegmentsMetada in SystemTestCase
piwik/piwik pull request #18141
Opened 2021-10-12 06:32 UTC by AltamashShaikh

Added functionality to filter getReportMetadata and getSegmentsMetada in SystemTestCase 
Issue: #DEV-2366

### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-10-13 04:56 UTC, AltamashShaikh commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        if (!isset(static::$fixture)) {
@tsteur is this the correct way to initialise and use $fixture ?

2021-10-13 20:15 UTC, tsteur commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        if (!isset(static::$fixture)) {
Each system test case would usually initalise the fixture themselves and usually at this point the fixture should already exist.

Maybe ideally we don't put any of that logic into the fixture as the fixture shouldn't be needed for this. So we could just have two methods in here that can be called. So a system test could do something like this:

```php
  public function setUp(): void
  {
      parent::setUp();
      $this->onlyAllowCategoryForApiMetadataReport('....');
  }
```

There's a chance these extra observers that may be added during the test may not be removed between the system tests so it's possible that the same action/filter is executed multiple times but that shouldn't be an issue. Alternatively, this could be done probably in the `static setUpBeforeClass` method in the test class.

2021-10-14 03:20 UTC, AltamashShaikh commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        if (!isset(static::$fixture)) {
Updated logic and moved code from fixtures to systemTestCase

Plugins would add code like this
```
public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
        self::setAllowedCategoryToFilterApiResponse('API.getSegmentsMetadata', 'ALLOWED_CATEGORYNAME');
    }
```

Is this fine?
Choose this since setUpBeforeClass is called before setUp and we need this data to be present before adding action

2021-10-14 03:24 UTC, tsteur commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        if (!isset(static::$fixture)) {
I haven't tested it but reckon this could work. 👍

2021-10-18 14:30 UTC, sgiehl commented
@AltamashShaikh I think it might be useful to add or change a test in core that uses that new possibility so we can directly see how and if it works. That might also prevent future regressions. You could for example change the custom dimension tests: https://github.com/matomo-org/matomo/blob/d7dced0928c7457f4e14fb571d897ac927b95134/plugins/CustomDimensions/tests/System/ApiTest.php#L162

2021-10-19 09:17 UTC, sgiehl requested changes

2021-10-19 09:17 UTC, sgiehl commented on plugins/CustomDimensions/tests/System/ApiTest.php
> +        self::setAllowedModuleToFilterApiResponse('API.getReportMetadata', 'CustomDimensions');
I guess this needs to be reset in `tearDownAfterClass`, otherwise other tests running afterwards might be affected by this. Could maybe also be done in `SystemTestCase`

2021-10-19 09:17 UTC, sgiehl commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        }
I think this needs to be moved to the `setUpBeforeClass` method. Calling it in `setUp` causes each test to add a new observer. So running 10 tests would end up having 10 event observers in the last test.
If the event observer is added in the `setUpBeforeClass`, you could also always add it like:
```php
Piwik::addAction('API.getReportMetadata.end', function (&$reports, $info) {
    $allowedModuleForApiMetadataReport = self::getAllowedModuleToFilterApiResponse('API.getReportMetadata');
    if ($allowedModuleForApiMetadataReport) {
        self::filterReportsCallback($reports, $info, $allowedModuleForApiMetadataReport);
    }
 });

Piwik::addAction('API.API.getSegmentsMetadata.end', function (&$reports, $info) {
    $allowedModuleForApiSegmentsReport = self::getAllowedModuleToFilterApiResponse('API.getSegmentsMetadata');
    if ($allowedModuleForApiSegmentsReport) {
        self::filterReportsCallback($reports, $info, $allowedModuleForApiSegmentsReport);
    }
});
```

Note: EvenObserver will be cleared when a Fixture is teared down, so the shouldn't be a need to remove the observers manually.

2021-10-20 07:24 UTC, sgiehl commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        }
As mentioned in a comment before, I think it would be better to always add the Event, but do the check if any allowed modules are set in the action function.
That way it doesn't matter if a class that overwrites the `setUpBeforeClass` calls it's parent before or after calling `setAllowedModuleToFilterApiResponse`. In theory it would then even be possible to call that in a single test only and reset it afterwards

2021-10-20 07:27 UTC, AltamashShaikh commented on tests/PHPUnit/Framework/TestCase/SystemTestCase.php
> +        }
makes sense :+1:

2021-10-20 13:47 UTC, sgiehl commented on plugins/CustomDimensions/tests/System/ApiTest.php
> +        self::setAllowedModuleToFilterApiResponse('API.getReportMetadata', 'CustomDimensions');
You could also add a filter for segments here. `API.getSegmentsMetadata` is also tested below

2021-10-21 03:33 UTC, AltamashShaikh commented on plugins/CustomDimensions/tests/System/ApiTest.php
> +        self::setAllowedModuleToFilterApiResponse('API.getReportMetadata', 'CustomDimensions');
Added

2021-10-21 07:46 UTC, sgiehl commented on plugins/CustomDimensions/tests/System/ApiTest.php
> +        self::setAllowedCategoryToFilterApiResponse('API.getSegmentsMetadata', 'Visitors');
Might be good if we could filter by multiple values here. The Custom Dimensions plugin adds Segments to `Visitors` and `Behaviour`

2021-10-21 08:23 UTC, AltamashShaikh commented on plugins/CustomDimensions/tests/System/ApiTest.php
> +        self::setAllowedCategoryToFilterApiResponse('API.getSegmentsMetadata', 'Visitors');
Moved to array instead of string

2021-10-21 08:41 UTC, sgiehl approved these changes
Looks good to me now. Once travis tests are running again and we can see if all tests are still passing, this should be good to merge

2021-10-26 08:27 UTC, merged