[Vue] Migrate content-block, enriched-headline, rate-feature + related
piwik/piwik pull request #18166
Opened 2021-10-17 06:30 UTC by diosmosis

### Description:

Changes:
* add static AjaxHelper.fetch method to make it seem more like piwikApi service
* migrate RateFeature component
* modify MatomoDialog to use v-model so it's simpler to use from vue
* made `vue:` property optional in scope mapping in createAngularAdapter
* migrate enrichedheadline
* allow translate function to take variadic args OR array of strings like _pk_translate
* migrate contentblock component
* (not related to vue) fix anchor links in trackingcodegenerator page (linking to `#anchor` instead of `#/anchor` causes angularjs to fail, happens on 4.x-dev too)
* fix nested transclude issue w/ createAngularAdapter

Notes:
* There is a cyclic dependency in terms of plugins here, with Feedback's RateFeature component depending on CoreHome's MatomoDialog, but CoreHome's EnrichedHeadline depending on Feedback's RateFeature. This was not a problem w/ angularjs since it was all just files depending on other files, but now there are UMD modules that depend on each other. This is mostly an issue for existing code, for new code it will be noticed early on. I was able to work around it like this: https://github.com/matomo-org/matomo/pull/18166/files#diff-0bb6c3fc35d58a5d2477dd55edaf3478e41bbf44ee5d0c051ff60c11f31123bbR79-R88

![image](https://user-images.githubusercontent.com/125140/137672805-2c0c0457-aca9-4677-b9c4-86ae0ca9eb43.png)

![image](https://user-images.githubusercontent.com/125140/137672741-4e8b98f9-4bc6-49e2-bfab-2327c273aa5d.png)

![image](https://user-images.githubusercontent.com/125140/137673234-4bb65d12-273e-40ca-b92d-08ef40996779.png)

**Note: it seems adding components does bump the the JS payload a bit. The 4 new vue component templates add about 2kb to the gzipped content.** It might be good to set a threshold for when it would be good to explore either using async components or loading plugin UMD's lazily. Both are doable, but it would be easier to manage the latter option in the long run.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-10-18 06:42 UTC, diosmosis commented on plugins/CoreHome/templates/_dataTable.twig
> +    <div class="reportDocumentation" data-content="{{ properties.documentation|e('html_attr') }}">
Note: this is for EnrichedHeadline so it can grab the HTML. In the angularjs directive, it gets it from ng-bind-html, but for vue we don't want to reference an angularjs directive like this.

2021-10-21 15:23 UTC, sgiehl commented on plugins/CoreHome/templates/_dataTable.twig
> +    <div class="reportDocumentation" data-content="{{ properties.documentation|e('html_attr') }}">
does this need a `|default` like below, so it doesn't fail when `properties.documentation` is not defined for any reason?

2021-10-21 18:01 UTC, diosmosis commented on plugins/CoreHome/templates/_dataTable.twig
> +    <div class="reportDocumentation" data-content="{{ properties.documentation|e('html_attr') }}">
:+1:

2021-10-22 07:14 UTC, sgiehl commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +        v-if="contentTitle && actualFeature || helpUrl || actualHelpText"
Is the operator precedence correct here? In the old template it had been `contentTitle && (feature || helpUrl || helpText)`

2021-10-22 07:19 UTC, diosmosis commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +        v-if="contentTitle && actualFeature || helpUrl || actualHelpText"
:+1: missed that, i'll double check the templates

2021-10-22 07:56 UTC, diosmosis commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +        v-if="contentTitle && actualFeature || helpUrl || actualHelpText"
@sgiehl fixed it, couldn't find any other occurrences. thanks for catching that!

2021-10-22 15:44 UTC, sgiehl commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +    let contentTopPosition: number;
I'm actually not familiar with how this is interpreted. Will `contentTopPosition` be initialized with `null` here or with `0` as it's a number?

2021-10-22 15:49 UTC, sgiehl commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +      const parents = root.closest('[piwik-widget-loader]');
This used to be `var parents = element.parentsUntil('.col', '[piwik-widget-loader]');`, which selects all `.col` elements up the tree till `[piwik-widget-loader]`. But now it directly looks for the closest `[piwik-widget-loader]`, which ihmo is something different. Or am I wrong here? 🤔

2021-10-22 16:02 UTC, sgiehl requested changes
Left some more comments. Besides that, the code already looks fine. Will do some cross browser testing next week and hopefully travis tests will then run again, so we can see if all tests are passing or not.

2021-10-22 17:40 UTC, diosmosis commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +    let contentTopPosition: number;
It should be initialized as `undefined`.

2021-10-22 17:44 UTC, diosmosis commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +      const parents = root.closest('[piwik-widget-loader]');
It does, then it only uses the top most. So it's the first .col under [piwik-widget-loader]. I found it overly complicated, and the tests passed, so I was hoping we didn't need complicated select. Do you think it should look for .col?

2021-10-23 02:21 UTC, diosmosis commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +    let contentTopPosition: number;
Though it seems sometimes typescript complains about this, sometimes not...

2021-10-25 08:07 UTC, sgiehl commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +      const parents = root.closest('[piwik-widget-loader]');
Had a closer look at the code and that actually only seems to affect the admin widgets, where it seems to work correctly that way. So should be good to keep that simpler 👍

2021-10-25 08:10 UTC, sgiehl commented on plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
> +    let contentTopPosition: number;
The reason for the question actually was to clarify if the default value would pass the condition below:
`contentTopPosition || contentTopPosition === 0`. 
Before it was initialized with `false`. Guess `undefined` should work correctly as well then.

2021-10-25 09:56 UTC, sgiehl approved these changes
Seems to work as expected. Once we have tests running again and they pass this would be good to merge.

2021-10-25 10:01 UTC, sgiehl commented
@diosmosis Unrelated to this PR, I get the following notice in the browser console
```
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: webpack:////home/dizzy/Projects/matomo/node_modules/dompurify/dist/purify.js?
```
Seems the path is your local one...

2021-10-25 17:15 UTC, diosmosis commented
@sgiehl I grepped for it and its in the source map for the polyfill build... not sure why it's using absolute paths, the build config might be wrong there... I'll take a look, thanks for mentioning it!

2021-10-25 17:38 UTC, diosmosis commented
@sgiehl should be fixed

2021-10-25 18:10 UTC, diosmosis commented
Actually it seems the recommended approach is to not include the sourcemap in production: https://webpack.js.org/configuration/devtool/, but since we distribute unminified javascript with plugins (and much of Matomo is open source), perhaps this isn't something we need to care about... cc @sgiehl @tsteur

2021-10-25 18:13 UTC, diosmosis commented
Actually, actually, since we just merge everything into one big JavaScript asset, the sourcemaps are useless in production.

2021-10-26 01:08 UTC, diosmosis commented
@sgiehl some test failures but they don't seem related

2021-10-26 11:58 UTC, sgiehl commented
> Actually, actually, since we just merge everything into one big JavaScript asset, the sourcemaps are useless in production.

Should we remove them from the build then, so they aren't included in the release zip?

2021-10-26 12:00 UTC, sgiehl commented
Tests seem to pass. Will merge this now.

2021-10-26 12:00 UTC, merged

2021-10-26 18:39 UTC, diosmosis commented
@sgiehl 

> Should we remove them from the build then, so they aren't included in the release zip?

I guess we could, they're only really useful for development, and they'll be generated when we develop. I'll make a PR.