update big int on cookie expire time to datatime format
piwik/piwik pull request #18179
Opened 2021-10-19 09:30 UTC by peterhashair

### Description:

Fixes: #18019 

 add a function in cookies. it accepts timestamp (int) and string eg: `+ 30 years` to avoid big int in PHP 32 bit

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-10-19 10:11 UTC, sgiehl commented on core/Cookie.php
> +    public function extendExpireByYears($years = 30)
This name might be a bit misleading. Based on the name I would expect that an existing expire time would be extended if already set. But the method actually sets the expire time to a date X years in the future.

2021-10-19 14:10 UTC, sgiehl commented on core/Cookie.php
> +        }
You maybe should readd the checks for `null` and `<0`. Not sure if there are any cases where that happens, but the behavior changed...
`DateTime::modify(null)`, doesn't do anything and also doesn't throw an exception, so the expire time remains to the current time. Instead it should use the default I guess.
Same applies for a negative value. `DateTime::setTimestamp(-50)` doesn't throw an exception but returns a time far in the past, so the cookie would be removed I guess. Before the default expire time was used as well.

2021-10-19 14:11 UTC, sgiehl commented
Seems there are also various tests failing...

2021-10-19 20:41 UTC, peterhashair commented
@sgiehl sorry, that's my bad, it actually fired a warning instead of an error.

2021-10-19 23:27 UTC, peterhashair commented
Not sure that's the best approach, it actually throws a warning to an exception enters the catch. Then reset it back. 
[https://github.com/matomo-org/matomo/blob/393bfa78d4c6e14eb8a30c6989248b27c70712ac/core/Cookie.php#L478](https://github.com/matomo-org/matomo/blob/393bfa78d4c6e14eb8a30c6989248b27c70712ac/core/Cookie.php#L478)

2021-10-20 08:03 UTC, sgiehl commented on core/Cookie.php
> +            ErrorHandler::registerWarningException();
Personally I think it might be a bit over bloated to use a custom error handler to catch some special cases.
Even with the error handler the case of a negative value is still not handled as before and doesn't result in the default expiration time.
If you want to validate if the value given to `modify` was valid, simply check the return value. Afaik it should return a boolean that indicates that.

2021-10-20 20:09 UTC, tsteur commented on core/Tracker/IgnoreCookie.php
> +        $cookie = new Cookie($cookie_name, "+ 30 years", $cookie_path, false);
@peterhashair  we can maybe simplify this a bit like pass the date we want to set here like in https://3v4l.org/RB5Lp

```php
$date = gmdate('D, d-M-Y H:i:s', time()) . ' GMT';
$year = gmdate('Y', time());
echo str_replace($year, $year+30, $date);
```

Then in the `formatExpireTime` could be like 

```php
if (is_numeric($expire)) {
  // old logic
 $expire = gmdate('D, d-M-Y H:i:s', (int) $Expires) . ' GMT';
} 
 // in other cases we already get the full date
```

not sure that makes sense but could work maybe?

2021-10-20 20:11 UTC, tsteur commented on core/Tracker/IgnoreCookie.php
> +        $cookie = new Cookie($cookie_name, "+ 30 years", $cookie_path, false);
Please ignore the comment if you can make it work otherwise as @sgiehl suggested to remove the error handler and checking return value or so

2021-10-22 07:45 UTC, sgiehl requested changes

2021-10-22 07:45 UTC, sgiehl commented on tests/PHPUnit/Unit/Tracker/RequestTest.php
> +use DateTime;
Guess the changes to this file are actually unneeded?

2021-10-22 07:45 UTC, sgiehl commented on core/Cookie.php
> +        }
Guess this still doesn't have the same behavior as before. Maybe something like this would work better:

```php
if (is_null($time) || (is_int($time) && $time < 0)) {
    $expireTime->modify("+2 years");
} else if (is_int($time)) {
    $expireTime->setTimestamp($time);
} else if (!$expireTime->modify($time)) {
    $expireTime = new DateTime(); // might be unneeded, not sure if modify might change the object even if it fails...
    $expireTime->modify("+2 years");
}
```

2021-10-23 00:33 UTC, peterhashair commented
@sgiehl that's looks great, let me update it.

2021-10-26 09:48 UTC, sgiehl commented on tests/PHPUnit/Unit/Tracker/RequestTest.php
> +use DateTime;
```suggestion
```

2021-10-26 09:53 UTC, sgiehl commented on core/Cookie.php
> +use Piwik\Exception\Exception;
```suggestion
use Piwik\Container\StaticContainer;
```

2021-10-26 09:55 UTC, sgiehl approved these changes
Code looks good to merge for me now. Will wait for the tests before merging

2021-10-26 11:27 UTC, merged