Fixing unsafe comparison warnings (`==` => `===`, `!=` => `!==`)
piwik/piwik pull request #18195
Opened 2021-10-21 10:31 UTC by hywak

### Description:

https://github.com/matomo-org/matomo/issues/17686

Lot's of files are changed, but those are cosmetics changes only.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [x] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] Existing documentation updated if needed

2021-10-21 12:00 UTC, sgiehl commented on core/API/DataTablePostProcessor.php
> +        if ($formatMetrics === '0') {
This might change the logic, unless we change the second parameter in the line above to `'0'`

2021-10-21 12:02 UTC, sgiehl commented on core/API/DocumentationGenerator.php
> +        if (strpos($moduleToCheck, '@hide') === true) {
This needs to be changed as well. `strpos` actually never returns true. Might be more correct to check for `!== false` instead

2021-10-21 12:12 UTC, hywak commented on core/API/DataTablePostProcessor.php
> +        if ($formatMetrics === '0') {
Good catch. Changed

2021-10-21 12:14 UTC, hywak commented on core/API/DocumentationGenerator.php
> +        if (strpos($moduleToCheck, '@hide') === true) {
Changed as well.

2021-10-21 12:53 UTC, sgiehl requested changes
Left a couple of comments. In general it might not be that easy to change `==` to `===` in all cases. Unfortunately our travis tests are currently not running as expected. As soon as they will work again we can trigger a new build to see how many tests are failing...

2021-10-21 12:53 UTC, sgiehl commented on core/API/DataTableManipulator/LabelFilter.php
> +        if ($this->apiModule == 'Actions' && in_array($this->apiMethod, $pageTitleReports)) {
```suggestion
        if ($this->apiModule === 'Actions' && in_array($this->apiMethod, $pageTitleReports)) {
```

2021-10-21 12:53 UTC, sgiehl commented on core/ArchiveProcessor/Loader.php
> +        if ($value === ArchiveWriter::DONE_INVALIDATED
Looking at the code it might happen tat `$value` could be of type string, as it is returns from a database query. Therefore you might need to cast it to int before doing that kind of compare.

2021-10-21 12:53 UTC, sgiehl commented on core/AssetManager.php
> +        if (Config::getInstance()->Development['disable_merged_assets'] === 1) {
Values returned from Config might be of type string.

2021-10-21 12:53 UTC, sgiehl commented on core/AssetManager.php
> +        if (isset($_GET['disable_merged_assets']) && $_GET['disable_merged_assets'] === 1) {
I guess GET parameters might be of type string as well

2021-10-21 12:53 UTC, sgiehl commented on core/CliMulti.php
> +        if (Config::getInstance()->General['force_ssl'] === 1) {
Config values might be strings

2021-10-21 12:53 UTC, sgiehl commented on core/Concurrency/LockBackend/MySqlLockBackend.php
> +            if ($e->getCode() === 23000
Not fully sure if those database error codes are always of type int.

2021-10-21 12:53 UTC, sgiehl commented on core/CronArchive.php
> +        $this->isArchiveProfilingEnabled = Config::getInstance()->Debug['archiving_profile'] === 1;
Config values might be strings

2021-10-21 12:53 UTC, sgiehl commented on core/CronArchive.php
> +        return Config::getInstance()->General['maintenance_mode'] === 1;
Config values might be strings

2021-10-21 12:53 UTC, sgiehl commented on core/DataAccess/Model.php
> +                if ($value !== ArchiveWriter::DONE_PARTIAL) {
Values returned from database queries might be strings or integers depending on the use database adapter

2021-10-21 12:53 UTC, sgiehl commented on core/DataArray.php
> +            if (round($revenue) === $revenue) {
I guess this won't work in all cases. `$revenue` is defined as Integer and as long as no float values will be added, it might remain as integer. calling `round` on an integer will return a float. And comparing a float with an integer holding the same value would still return false.

2021-10-21 12:53 UTC, sgiehl commented on core/DataTable/Filter/Pattern.php
> +        return preg_match($patternQuoted . "i", $string) === 1 ^ $invertedMatch;
Even though it shouldn't happen, this compare won't any longer handle the error case when `preg_match` returns false.

2021-10-21 12:53 UTC, sgiehl commented on core/Date.php
> +        if ($n !== round($n)) {
This will always be true when `$n` is given as `int` as `round` always returns `float`

2021-10-21 12:53 UTC, sgiehl commented on core/Db.php
> +            || @Config::getInstance()->Debug['log_sql_queries'] !== 1
Config value might be strings or ints

2021-10-21 12:53 UTC, sgiehl commented on core/Db.php
> +            if ($result === '1') {
Values coming from database queries might be strings or ints depending on the database adapter

2021-10-21 12:53 UTC, sgiehl commented on core/Db.php
> +        return $db->fetchOne($sql, array($lockName)) === '1';
same as above

2021-10-21 12:53 UTC, sgiehl commented on core/Db/Adapter/Mysqli.php
> +                return $match[1] === $errno;
This and the compare below will only work if `$errno` is given as string. Not sure if this might be called with an integer at some places.

2021-10-21 12:53 UTC, sgiehl commented on core/Db/Adapter/Pdo/Mysql.php
> +            return $match[1] === $errno;
Depending of given `$errno` the types might differ here, too.

2021-10-21 12:53 UTC, sgiehl commented on core/FileIntegrity.php
> +            } elseif (filesize($file) !== $props[0]) {
The Manifest file contains the filesize as strings, so this compare will fail

2021-10-21 12:53 UTC, sgiehl commented on core/FileIntegrity.php
> +                    if ((strlen($content) !== $props[0])
same as above

2021-10-21 12:53 UTC, sgiehl commented on core/FrontController.php
> +        if ((Config::getInstance()->General['maintenance_mode'] !== 1) || Common::isPhpCliMode()) {
Config values might be strings

2021-10-21 12:53 UTC, sgiehl commented on core/FrontController.php
> +        $profilerEnabled = Config::getInstance()->Debug['enable_php_profiler'] === 1;
Config values might be strings

2021-10-21 12:53 UTC, sgiehl commented on core/FrontController.php
> +            $mainRun = $_GET['xhprof'] === 1; // core:archive command sets xhprof=2
GET parameters might be strings

2021-10-21 12:53 UTC, sgiehl commented on core/FrontController.php
> +        if ($generalConfig['enable_framed_pages'] === '1' || $generalConfig['enable_framed_settings'] === '1') {
Config values can be string or ints.

2021-10-21 12:53 UTC, sgiehl commented on core/Http.php
> +            if (@ini_get('allow_url_fopen') !== '1') {
Not sure if `ini_get` may also return an integer 🤔

2021-10-21 12:53 UTC, sgiehl commented on core/Http.php
> +            if ($contentLength > 0 && $fileSize !== $contentLength) {
`$contentLength` might come from `@curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_DOWNLOAD)`, not sure if that always returns an integer like `filesize`

2021-10-21 12:53 UTC, sgiehl commented on core/IP.php
> +        $shouldReadLastProxyIp = Config::getInstance()->General['proxy_ip_read_last_in_list'] === 1;
Config values can be strings or ints

2021-10-21 12:53 UTC, sgiehl commented on core/Nonce.php
> +            if ($port !== 443) {
`$port` is the result from a `preg_match` and therefor likely is a string

2021-10-21 12:53 UTC, sgiehl commented on core/NumberFormatter.php
> +        if ($newValue === round($newValue)) {
the types might differ here, causing different results as before.

2021-10-21 12:53 UTC, sgiehl commented on core/Period/Month.php
> +            || $startDate === $endDate
I don't think that will work, as both variables are an instance of `Piwik\Date` but aren't the same instance. This might work though
```suggestion
            || $startDate->toString() === $endDate->toString()
```

2021-10-21 12:53 UTC, sgiehl commented on core/Period/Month.php
> +            } elseif ($startOfWeek === $startDate) {
same here:
```suggestion
            } elseif ($startOfWeek->toString() === $startDate->toString()) {
```

2021-10-21 12:53 UTC, sgiehl commented on core/Period/Month.php
> +        while (($startDate->isEarlier($endDate) || $startDate === $endDate)) {
here as well:
```suggestion
        while (($startDate->isEarlier($endDate) || $startDate->toString() === $endDate->toString())) {
```

2021-10-21 12:53 UTC, sgiehl commented on core/Piwik.php
> +        if ($divisor === 0) {
I'm not sure here if `$divisor` might not be a numeric string in some cases.
```suggestion
        if ((int) $divisor === 0) {
```

2021-10-21 12:53 UTC, sgiehl commented on core/Piwik.php
> +        if ($dividend === 0 || $dividend === '-') {
```suggestion
        if ((int) $dividend === 0 || $dividend === '-') {
```

2021-10-21 12:53 UTC, sgiehl commented on core/Plugin/ControllerAdmin.php
> +        if ($statsEnabled === "0") {
A config value might also be an integer.

2021-10-21 12:53 UTC, sgiehl commented on core/ProxyHeaders.php
> +        if (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] === 443) {
I guess `$_SERVER['SERVER_PORT']` is more likely returned as a string, but not sure if can also be an integer.

2021-10-21 12:53 UTC, sgiehl commented on core/Settings/Storage/Backend/MeasurableSettingsTable.php
> +            if ($e->getCode() !== 42) {
Not sure if database exception codes might not be strings instead.

2021-10-21 12:53 UTC, sgiehl commented on core/Tracker/Model.php
> +            if ($e->getCode() === 23000 ||
Database exception codes might possibly also be strings...

2021-10-21 12:59 UTC, hywak commented on core/Db.php
> +            if ($result === '1') {
@sgiehl Do you think it's safe to cast the result to string and compare `(string) $result === '1'` ?

2021-10-21 13:03 UTC, hywak commented on core/AssetManager.php
> +        if (Config::getInstance()->Development['disable_merged_assets'] === 1) {
@sgiehl Correct me if I'm wrong. It should be enough If I cast Config value to a string and compare it with the string `'1'`?

2021-10-21 13:14 UTC, sgiehl commented on core/AssetManager.php
> +        if (Config::getInstance()->Development['disable_merged_assets'] === 1) {
Yes, I guess it should be enough that way.

2021-10-21 13:16 UTC, hywak commented on core/Tracker/Model.php
> +            if ($e->getCode() === 23000 ||
Changing condition to `if ((string) $e->getCode() === '23000'`

2021-10-21 13:17 UTC, hywak commented on core/Settings/Storage/Backend/MeasurableSettingsTable.php
> +            if ($e->getCode() !== 42) {
Changing condition to `if ((string) $e->getCode() !== '42') {`

2021-10-21 13:17 UTC, hywak commented on core/ProxyHeaders.php
> +        if (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] === 443) {
Changing condition to `(string) $_SERVER['SERVER_PORT'] === '443'`

2021-10-21 13:18 UTC, hywak commented on core/Plugin/ControllerAdmin.php
> +        if ($statsEnabled === "0") {
Changed to `if ((string) $statsEnabled === '0') {`

2021-10-21 13:18 UTC, hywak commented on core/CliMulti.php
> +        if (Config::getInstance()->General['force_ssl'] === 1) {
Changed to `if ((string) Config::getInstance()->General['force_ssl'] === '1')`

2021-10-21 13:19 UTC, hywak commented on core/AssetManager.php
> +        if (Config::getInstance()->Development['disable_merged_assets'] === 1) {
Changing to `if ((string) Config::getInstance()->Development['disable_merged_assets'] === '1') {`

2021-10-21 13:19 UTC, hywak commented on core/AssetManager.php
> +        if (isset($_GET['disable_merged_assets']) && $_GET['disable_merged_assets'] === 1) {
Changing to `(string) $_GET['disable_merged_assets'] === '1')`

2021-10-21 13:20 UTC, hywak commented on core/Concurrency/LockBackend/MySqlLockBackend.php
> +            if ($e->getCode() === 23000
Changed to `if ((string) $e->getCode() === '23000'`

2021-10-21 13:20 UTC, hywak commented on core/CronArchive.php
> +        $this->isArchiveProfilingEnabled = Config::getInstance()->Debug['archiving_profile'] === 1;
Changed to `$this->isArchiveProfilingEnabled = (string) Config::getInstance()->Debug['archiving_profile'] === '1';`

2021-10-21 13:21 UTC, hywak commented on core/CronArchive.php
> +        return Config::getInstance()->General['maintenance_mode'] === 1;
Changed to `return (string) Config::getInstance()->General['maintenance_mode'] === '1';`

2021-10-21 13:22 UTC, hywak commented on core/DataAccess/Model.php
> +                if ($value !== ArchiveWriter::DONE_PARTIAL) {
Casting to int `if ((int) $value !== ArchiveWriter::DONE_PARTIAL) {` as `DONE_PARTIAL` value is `5`

2021-10-21 13:22 UTC, sgiehl commented on core/Db.php
> +            if ($result === '1') {
yes. should be

2021-10-21 13:24 UTC, hywak commented on core/DataArray.php
> +            if (round($revenue) === $revenue) {
It seems like this condition is to detect whether `$revenue` is int or float, depending on the value it's forced to be float. 🤔

2021-10-21 13:26 UTC, hywak commented on core/Db.php
> +            || @Config::getInstance()->Debug['log_sql_queries'] !== 1
Changed to `@(string) Config::getInstance()->Debug['log_sql_queries'] !== '1') {`

2021-10-21 13:27 UTC, hywak commented on core/Db.php
> +            if ($result === '1') {
Changing to `if ((string) $result === '1') {`

2021-10-21 13:27 UTC, hywak commented on core/Db.php
> +        return $db->fetchOne($sql, array($lockName)) === '1';
Changed to `return (string) $db->fetchOne($sql, [$lockName]) === '1';`

2021-10-21 13:32 UTC, hywak commented on core/Db/Adapter/Mysqli.php
> +                return $match[1] === $errno;
It seems like it can be. `mysqli_connect_errno()` and `mysqli_errno` return int, while `preg_match` returns string.  

I'm wondering whether below casting wouldn't do the job?
```        if (is_null($connection)) {
            if (preg_match('/(?:\[|\s)([0-9]{4})(?:\]|\s)/', $e->getMessage(), $match)) {
                return $match[1] === (string) $errno;
            }

            return mysqli_connect_errno() === (int) $errno;
        }

        return mysqli_errno($connection) === (int) $errno;
```

2021-10-21 13:33 UTC, hywak commented on core/Db/Adapter/Pdo/Mysql.php
> +            return $match[1] === $errno;
Changing to `            return $match[1] === (string) $errno;`

2021-10-21 13:33 UTC, sgiehl commented on core/DataArray.php
> +            if (round($revenue) === $revenue) {
Actually I'm not sure what that check is supposed to do. Guess simply casting `$revenue` to `float` would do the same, wouldn't it? 🤔

2021-10-21 13:35 UTC, hywak commented on core/FrontController.php
> +        $profilerEnabled = Config::getInstance()->Debug['enable_php_profiler'] === 1;
Changed to `$profilerEnabled = (string) Config::getInstance()->Debug['enable_php_profiler'] === '1';`

2021-10-21 13:35 UTC, hywak commented on core/FrontController.php
> +            $mainRun = $_GET['xhprof'] === 1; // core:archive command sets xhprof=2
Changed to `$mainRun = (string) $_GET['xhprof'] === '1';`

2021-10-21 13:36 UTC, hywak commented on core/FrontController.php
> +        if ($generalConfig['enable_framed_pages'] === '1' || $generalConfig['enable_framed_settings'] === '1') {
Changed to
 ```
        if ((string) $generalConfig['enable_framed_pages'] === '1' 
            || (string) $generalConfig['enable_framed_settings'] === '1'
        ) {
```

2021-10-21 13:37 UTC, hywak commented on core/IP.php
> +        $shouldReadLastProxyIp = Config::getInstance()->General['proxy_ip_read_last_in_list'] === 1;
Changed to `$shouldReadLastProxyIp = (string) Config::getInstance()->General['proxy_ip_read_last_in_list'] === '1';`

2021-10-21 13:37 UTC, hywak commented on core/Nonce.php
> +            if ($port !== 443) {
changed to `if ((string) $port !== '443') {`

2021-10-21 14:02 UTC, hywak commented on core/DataArray.php
> +            if (round($revenue) === $revenue) {
`$revenue` field is being set to 0 in line 385. It's being modified later in line 389, theoretically, it can be either int or float depending on `$goalValues[Metrics::INDEX_GOAL_REVENUE];` result. So it seems like `round($revenue)` is done just for making sure that `$revenue` fill be float at the end.

But this condition doesn't make sense to me even before my change.
```
var_dump(round(25.00)); // float(25)

var_dump(round(25)); // float(25)
```

2021-10-22 08:15 UTC, sgiehl commented on core/DataArray.php
> +            if (round($revenue) === $revenue) {
`$goalValues[Metrics::INDEX_GOAL_REVENUE];` might also hold integer or float values I guess. Logically it seems that condition is nothing else than a "complexe" cast.
There can actually only be this two cases:
- `$revenue` is an integer like `18`. `round($revenue) == $revenue` would be `true` and `$revenue` would be changed to a `float` (by using round).
- `$revenue` is an float like `12.34`. `round($revenue) == $revenue` would be `false` and `$revenue` would stay a `float`

So imho simply writing `$revenue = (float) $revenue;` should be the same.

2021-10-22 08:22 UTC, sgiehl commented on core/Db.php
> +        if (self::$logQueries === false || @(string) Config::getInstance()->Debug['log_sql_queries'] !== '1') {
I guess the `@` shouldn't be needed though

2021-10-22 08:22 UTC, sgiehl commented on core/Db/Adapter/Mysqli.php
> +                return $match[1] === $errno;
should be fine that way 👍

2021-10-22 08:44 UTC, hywak commented on core/DataArray.php
> +            if (round($revenue) === $revenue) {
Thinking the same. Changing to `$values[Metrics::INDEX_REVENUE] = (float) $revenue;`

2021-10-22 08:44 UTC, hywak commented on core/Db.php
> +        if (self::$logQueries === false || @(string) Config::getInstance()->Debug['log_sql_queries'] !== '1') {
Removing then

2021-10-22 08:55 UTC, hywak commented on core/FileIntegrity.php
> +            } elseif (filesize($file) !== $props[0]) {
Casting `filesize($file)` to string should be safe, ` } elseif ((string) filesize($file) !== $props[0]) {`

2021-10-22 08:56 UTC, hywak commented on core/FrontController.php
> +        if ((Config::getInstance()->General['maintenance_mode'] !== 1) || Common::isPhpCliMode()) {
Changing to `if ((string) (Config::getInstance()->General['maintenance_mode'] !== '1') || Common::isPhpCliMode()) {`

2021-10-22 08:57 UTC, hywak commented on core/FileIntegrity.php
> +                    if ((strlen($content) !== $props[0])
Changing to `if ((strlen($content) !== (int) $props[0]) || (@md5($content) !== $props[1])) {`

2021-10-22 08:59 UTC, hywak commented on core/Http.php
> +            if (@ini_get('allow_url_fopen') !== '1') {
According to documentation it should be string or false https://www.php.net/manual/en/function.ini-get.php. I can cat it to be 100% sure, what do you think?

2021-10-22 09:44 UTC, hywak commented on core/Http.php
> +            if ($contentLength > 0 && $fileSize !== $contentLength) {
$contentLength is being casted to `integer` in `core/Http.php:511`. I'm adding casting in `core/Http.php:761` as well `$contentLength = (int) @curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_DOWNLOAD);`

2021-10-22 09:54 UTC, hywak commented on core/NumberFormatter.php
> +        if ($newValue === round($newValue)) {
Accepting your chnges

2021-10-22 09:54 UTC, hywak commented on core/DataTable/Filter/Pattern.php
> +        return preg_match($patternQuoted . "i", $string) === 1 ^ $invertedMatch;
Reverting this change. I don't understand the logic here, don't want to mess up

2021-10-22 10:02 UTC, sgiehl requested changes
Had another look through the changes.

2021-10-22 10:02 UTC, sgiehl commented on core/Settings/Storage/Backend/MeasurableSettingsTable.php
> +            if ($e->getCode() !== 42) {
```suggestion
            if ((string) $e->getCode() !== '42') {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Settings/Storage/Backend/PluginSettingsTable.php
> +            if ($e->getCode() !== 42) {
```suggestion
            if ((string) $e->getCode() !== '42') {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Settings/Storage/Backend/PluginSettingsTable.php
> +            if ($e->getCode() !== 42) {
```suggestion
            if ((string) $e->getCode() !== '42') {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Tracker/Model.php
> +        return $val === $idSite;
Database query might return a string, while the value given to that method could actually be string or int I guess
```suggestion
        return (string) $val === (string) $idSite;
```

2021-10-22 10:02 UTC, sgiehl commented on core/Tracker/GoalManager.php
> +            if ($convertedGoal['allow_multiple'] === 0) {
Not sure if we can assume this one to be an integer
```suggestion
            if ((int) $convertedGoal['allow_multiple'] === 0) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Tracker/GoalManager.php
> +        if (round($revenue) !== $revenue) {
I guess this is another check if we have fraction digits. To also handle integers correctly I think it would need to be
```suggestion
        if (round($revenue) !== (float) $revenue) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Tracker/GoalManager.php
> +            if ($goal['idgoal'] === $idGoal) {
$goals is coming from database, so the values might be integer or string. Same applies for the value given to that method:
```suggestion
            if ((int) $goal['idgoal'] === (int) $idGoal) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Profiler.php
> +            $output .= "Executed <b>$count</b> time" . ($count === 1 ? '' : 's') . " in <b>" . $timeMs . "ms</b> $avgTimeString <pre>\t$query</pre>";
Not sure if `$count` is always an integer. Might be good to simply cast it a few lines above.

2021-10-22 10:02 UTC, sgiehl commented on core/NumberFormatter.php
> +        if ($newValue === round($newValue)) {
```suggestion
        if ((float) $newValue === round($newValue)) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/Http.php
> +            if ($contentLength > 0 && $fileSize !== $contentLength) {
```suggestion
            if ($contentLength > 0 && $fileSize !== (int) $contentLength) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/FrontController.php
> +        if ((Config::getInstance()->General['maintenance_mode'] !== 1) || Common::isPhpCliMode()) {
```suggestion
        if (((string) Config::getInstance()->General['maintenance_mode'] !== '1') || Common::isPhpCliMode()) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/FileIntegrity.php
> +            } elseif (filesize($file) !== $props[0]) {
```suggestion
            } elseif (filesize($file) !== (int) $props[0]) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/FileIntegrity.php
> +                    if ((strlen($content) !== $props[0])
```suggestion
                    if ((strlen($content) !== (int) $props[0])
```

2021-10-22 10:02 UTC, sgiehl commented on core/Date.php
> +        if ($n !== round($n)) {
```suggestion
        if ((float) $n !== round($n)) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataTable/Filter/ExcludeLowPopulation.php
> +        if ($minimumValue === 0) {
based on the doc block `$minimumValue` can be `false`. This case was covered here as well. So guess this would be better:
```suggestion
        if ((int) $minimumValue === 0) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataTable/Filter/CalculateEvolutionFilter.php
> +        if ($value === 0) {
I guess we can't assume `$value` to be an integer. Could also be a `float`.
```suggestion
        if ((float) $value === 0.0) {
```

Note: Casting to integer instead would be incorrect as `(int) 0.25` would result in `0`

2021-10-22 10:02 UTC, sgiehl commented on core/DataTable/Filter/CalculateEvolutionFilter.php
> +        } elseif ($divisor === 0) {
```suggestion
        } elseif ((float) $divisor === 0.0) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataArray.php
>              }
```suggestion
            $revenue = (float) $revenue;
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataAccess/ArchiveWriter.php
> +        if ($doneValue === self::DONE_PARTIAL && strpos($this->doneFlag, '.') === false) {
`$doneValue` might be string though.

```suggestion
        if ((int) $doneValue === self::DONE_PARTIAL && strpos($this->doneFlag, '.') === false) {
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataAccess/ArchiveSelector.php
> +            if ($row['value'] === ArchiveWriter::DONE_PARTIAL
```suggestion
            if ((int) $row['value'] === ArchiveWriter::DONE_PARTIAL
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataAccess/ArchiveSelector.php
> +                && $result['value'] !== ArchiveWriter::DONE_PARTIAL
```suggestion
                && (int) $result['value'] !== ArchiveWriter::DONE_PARTIAL
```

2021-10-22 10:02 UTC, sgiehl commented on core/DataAccess/ArchiveSelector.php
> +                        && $value !== ArchiveWriter::DONE_PARTIAL
```suggestion
                        && (int) $value !== ArchiveWriter::DONE_PARTIAL
```

2021-10-22 10:02 UTC, sgiehl commented on core/CronArchive/Performance/Logger.php
> +        $this->isEnabled = $config->Debug['archiving_profile'] === 1;
```suggestion
        $this->isEnabled = (string) $config->Debug['archiving_profile'] === '1';
```

2021-10-22 10:02 UTC, sgiehl commented on core/API/DataTablePostProcessor.php
> +        if (1 === Common::getRequestVar('totals', '1', 'integer', $this->request)) {
```suggestion
        if (1 === Common::getRequestVar('totals', 1, 'integer', $this->request)) {
```

2021-10-22 10:33 UTC, hywak commented on core/Date.php
> +        if ($n !== round($n)) {
Accepting your changes

2021-10-22 15:32 UTC, sgiehl requested changes
Found a couple more things. But besides that it's looking fine. We may need to wait until mid of next week till the travis tests are running again. Once we had them running we can check if anything causes problems....

2021-10-22 15:32 UTC, sgiehl commented on core/API/DataTablePostProcessor.php
> +        if (0 === Common::getRequestVar('disable_generic_filters', '0', 'string', $this->request)) {
```suggestion
        if ('0' === Common::getRequestVar('disable_generic_filters', '0', 'string', $this->request)) {
```

2021-10-22 15:32 UTC, sgiehl commented on core/API/DataTablePostProcessor.php
>          $compare = Common::getRequestVar('compare', '0', 'int', $this->request);
```suggestion
        $compare = Common::getRequestVar('compare', 0, 'int', $this->request);
```

2021-10-22 15:32 UTC, sgiehl commented on core/Http.php
> +            if (@ini_get('allow_url_fopen') !== '1') {
We can keep it as is for now.

2021-10-22 15:32 UTC, sgiehl commented on core/Http.php
> +            if ($contentLength > 0 && $fileSize !== (int) $contentLength) {
`$contentLength` is now casted before, so this is obsolete

```suggestion
            if ($contentLength > 0 && $fileSize !== $contentLength) {
```

2021-10-26 12:35 UTC, sgiehl commented
@hywak would you mind merging in the latest changes from 4.x-dev branch. Travis builds should be up and running again, so we hopefully can see afterwards if all those changes break anything or not.

2021-10-28 07:39 UTC, sgiehl commented
@hywak Seems there are a plenty of tests failing. Might be good to first looking into why the Unit tests are failing, maybe fixing those might also fix some of the other test suites:
https://app.travis-ci.com/github/matomo-org/matomo/jobs/545181203
I'm not sure when I will find some time to have a quick look myself to maybe identify some first issues, but will try to do that soon.

2021-10-28 07:55 UTC, sgiehl commented on core/Common.php
> +                if ($value === (string)(int)$value) {
Maybe this is causing some issues:
```suggestion
                if ((string)$value === (string)(int)$value) {
```

2021-10-28 08:22 UTC, hywak commented
@sgiehl I will take a look at it tomorrow or at the weekend :)

2021-10-29 06:56 UTC, hywak commented
@sgiehl Is there documentation on how to run tests locally?

2021-10-29 08:06 UTC, sgiehl commented
@hywak sure. See https://developer.matomo.org/guides/tests
If you have any problems with that, feel free to ask.

2021-10-29 10:50 UTC, hywak commented
Pushed changes where all unit tests were passing locally: https://github.com/matomo-org/matomo/pull/18195/commits/45a3aa5bbf1efc65f061e05b5659e571c5d97c6a

2021-10-29 12:39 UTC, sgiehl commented
The System tests are still failing though. Seems to be caused by some kind of rounding issue. Guess some check doesn't do the same as before...

2022-02-18 08:44 UTC, sgiehl commented
@hywak I will close this one now. I don't think we will be able to easily get this PR into a state where we can safely merge. The number of changes is simply to high to identify which are causing the test failures.
If you are still keen on contributing to Matomo, it would be very helpful to create smaller pull requests with the same changes instead. If only a couple of files are changed in each it's a lot easier to find the cause for failing tests and we will be a lot more faster in merging it...

2022-02-18 08:44 UTC, closed without merging