Fix CSP issue when viewing marketplace plugin details
piwik/piwik pull request #18215
Opened 2021-10-25 10:15 UTC by sgiehl

### Description:

When viewing the admin page, which contains a widget showing details on new plugins, or when opening the plugin details of a plugin, there is currently a CSP report shown:

```
[Report Only] Refused to load the image 'https://plugins.matomo.org/RerUserDates/images/4.0.1/RerUserDates-cal.png?w=400' because it violates the following Content Security Policy directive: "img-src 'self' 'unsafe-inline' 'unsafe-eval' data:".
```

To avoid this I've added `*.matomo.org` to `img-src`.

In addition premium plugins are loading the reviews from shop.matomo.org. This would also fail in the future, so added `*.matomo.org` to `default-src` as well.

refs #17923

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-10-25 20:02 UTC, tsteur requested changes

2021-10-25 20:02 UTC, tsteur commented on plugins/CoreAdminHome/Controller.php
> +        if ($isInternetEnabled && $isMarketplaceEnabled) {
should this be done directly in the widget? I suppose similar issue would happen when adding a marketplace widget to the dashboard? I suppose it might not work as the widget is rendered in a separate request?

We might need to also check if the marketplace is being viewed in the reporting UI eg in a dashboard

2021-10-25 20:56 UTC, sgiehl commented on plugins/CoreAdminHome/Controller.php
> +        if ($isInternetEnabled && $isMarketplaceEnabled) {
Exactly. That doesn't work as it's another request. We could actually always add it if such a widget can be added to dashboard

2021-10-26 13:01 UTC, sgiehl commented on plugins/CoreAdminHome/Controller.php
> +        if ($isInternetEnabled && $isMarketplaceEnabled) {
I have checked the marketplace widgets for the dashboard. Both don't seem to show any images. So shouldn't be needed to add a CSP there.

2021-10-27 01:27 UTC, tsteur commented on plugins/CoreAdminHome/Controller.php
> +        if ($isInternetEnabled && $isMarketplaceEnabled) {
![image](https://user-images.githubusercontent.com/273120/138984253-f3a851e4-9b8c-457a-b2a9-54abc8b151f2.png)
@sgiehl they show for me eg when clicking on "more details"

Also when clicking on the left menu on "Marketplace" then there may be screenshots shown when getting details 
![image](https://user-images.githubusercontent.com/273120/138984319-7ad11f3c-f574-45c0-a426-e34d3e68a9dc.png)

Maybe when Marketplace is enabled, then *.matomo.org always need to be allowed in the reporting page?

2021-10-27 14:25 UTC, sgiehl commented on plugins/CoreAdminHome/Controller.php
> +        if ($isInternetEnabled && $isMarketplaceEnabled) {
ah. sure. Should be fixed now.

2021-10-27 19:29 UTC, tsteur commented
works 👍

2021-10-27 19:30 UTC, merged