Ensure DNS records are only requested for IP allowlist when needed
piwik/piwik pull request #18285
Opened 2021-11-09 19:21 UTC by sgiehl

### Description:

- only request dns records if it's not an IP range
- cache DNS results for 30 seconds to reduce DNS requests

Note: Tracking requests never go through the allow-list, as that's excluded here: https://github.com/matomo-org/matomo/blob/bc75f9dafc9287a7864f3ecd556a5ae6b699546a/plugins/CoreHome/CoreHome.php#L78-L81

fixes #18244

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-11-09 20:14 UTC, tsteur requested changes
Works overall @sgiehl . Few tweaks be needed though.

2021-11-09 20:14 UTC, tsteur commented on config/global.php
> +            if (filter_var($ip, FILTER_VALIDATE_IP) || \Matomo\Network\IPUtils::getIPRangeBounds($ip) !== null) {
can we add a test for this one @sgiehl ?

2021-11-09 20:14 UTC, tsteur commented on config/global.php
> +                    $lazyCache = \Piwik\Cache::getLazyCache();
Can we also cache `gethostbyname` as I would assume it's equally "slow" and can add load for DNS when it resolves IPv4 there?

2021-11-09 20:14 UTC, tsteur commented on config/global.php
> +                    if ( !$lazyCache->contains($cacheKey) ) {
Using the `contains` can maybe cause a bit of a race condition. As when we fetch the entry, the cache might be already outdated. Also `contains` already does a `fetch` I believe (not 100% sure) so we might actually fetch the cache twice in the end. I wonder if we can fetch the cache here using `$entry = $lazyCache->fetch($cacheKey);` and then only get the value if none is there yet?

2021-11-10 08:22 UTC, sgiehl commented
@tsteur Thanks for the suggestions. I've updated the code accordingly.

2021-11-10 19:14 UTC, tsteur commented
Works 🚀

2021-11-10 19:14 UTC, merged