invite user replace add user
piwik/piwik pull request #18351
Opened 2021-11-19 04:33 UTC by peterhashair

### Description:

fixes: #13321 
- Add User status (pending, active)
- Add two additional fields into the user table. invite_token_expired, invite_token
- Add resend the invite

Missing: 
- New UI Test

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-11-19 04:48 UTC, peterhashair commented
sorry to bother you, 3 questions. And find one bug. 

**Bug:**

- If you come from a `quick link` URL it appends `showadduser=1`, after that you will always stay add user form. even refresh. simple fix, I will in this PR. 

**Questions**

- To addColumn to exiting database table. do I use `4.7.0-b1?
- Introduce user status, currently depending on the `invite_token` field, just checking, do we want to introduce this field as an individual field not relied on `invite_token`. So it accepts pending, suspended, disabled, etc. 

- Resend invites,  after people send invites do we need a status said sent, and the next send can only be done after 15mins? Otherwise, it maybe adds a mail server to span?

2021-11-21 19:22 UTC, tsteur commented
@peterhashair I saw your questions in the email but they are removed in the comment here. I'll comment quick anyway

> To addColumn to exiting database table. do I use `4.7.0-b1?

Likely yes, it depends when we merge it and whether by then maybe already a b1 has been released. Likely it will be -b1 though.

> Introduce user status, currently depending on the invite_token field, just checking, do we want to introduce this field as an individual field not relied on invite_token. So it accepts pending, suspended, disabled, etc.

Not 100% sure. It really depends whether it's needed or not. It might not be needed as I think we delete a user if we withdraw the invite etc. We probably won't have a suspended. I'd say it's probably not needed, but it's hard to say without being too much into it.

> Resend invites, after people send invites do we need a status said sent, and the next send can only be done after 15mins? Otherwise, it maybe adds a mail server to span?

Yes that be good 👍

2021-11-22 05:07 UTC, peterhashair commented
@tsteur sorry to bother you, I am trying to implement integration tests, but it seems like the database missing the new field I happened to, do I need to add a `install()` function inside of UserManager other than `4.7.0-b1.php`

2021-11-22 19:26 UTC, tsteur commented
@peterhashair you will also need to adjust the schema in https://github.com/matomo-org/matomo/blob/4.6.0-rc2/core/Db/Schema/Mysql.php#L47 which is used for new installs

2021-11-22 22:10 UTC, peterhashair commented
@tsteur  it seems like the tests still don't apply that database extends fixture on my local does not update the database. It's there a way I can manually run updates, I mean manually run `4.7.0-b1.php`

2021-11-22 23:35 UTC, tsteur commented
@peterhashair you will also need to set the version number in the version class to 4.7.0-b1

2021-11-28 20:34 UTC, peterhashair commented
Not sure if how we test the email templates.

2021-12-14 15:51 UTC, sgiehl commented on tests/resources/OmniFixture-dump.sql
> +  `invite_at` timestamp NULL DEFAULT NULL,
That should actually not be needed. When the fixture is set up it tries to perform any available updates that were added after the Omnifixture was last created (based on the version in the option table). So as long as you have added an update script and the version in `core\Version.php` has been increased, the columns should be added automatically

2021-12-15 02:34 UTC, peterhashair commented
the question I have for that one is are we missing an email Screenshot test, still thinking about how we implement this.

2021-12-15 02:40 UTC, tsteur commented
@peterhashair do you want to test what the email looks like? In that case we could create an integration test and check that the created email content matches the expected HTML or text content. And basically not have a visual test for the email content.

2021-12-15 04:33 UTC, peterhashair commented
@tsteur that make more sense, Will do a HTML code comparison

2022-01-18 20:49 UTC, justinvelluppillai commented
What's needed here to move this PR along @peterhashair? Can you update and request review?

2022-01-18 21:05 UTC, peterhashair commented
@justinvelluppillai nothing needed here, just code review :)

2022-01-19 23:52 UTC, tsteur commented
* In the Invite User UI before the "Invite" button can we show some text what will happen after clicking on the button? Like we can mention that the user will receive an email, that the user has X days to confirm this email. And we can also inform them they can reject an unaccepted invite by doing xyz? What else would be important?

![image](https://user-images.githubusercontent.com/273120/150234212-8c068ac1-da57-42b3-b369-2c06e97372ac.png)

* The email contains `%s` text 
![image](https://user-images.githubusercontent.com/273120/150234555-59465eea-bc04-4e97-b935-5a3bcd33f0c6.png)


* Can we disable maybe the "Password" form field (maybe also in the API) until a user confirmed the invite? Currently a super user can set the password for a person who was invited but has not accepted anything yet. I checked it wasn't possible to log in but may be still good to prevent this? 

* I'm not sure but it looks like I was automatically logged in if after accepting the invite without having to confirm the password. Possible that this was the case because the super user set a password on my behalf but doesn't look like it. I tested it with another user as well and I did not have to configure any password I was directly logged in and could click around in the UI and it counted as accepted.
Instead it was accepted that we're showing the user a screen where the user confirms the invite, configures password, and also we need to make sure that they'll know what their login is. They won't be automatically logged in. If a privacy or terms or imprint URL is configured in general settings then they would need to agree to the configured terms and policy to confirm the invite. And if an Imprint URL is configured, then we would need to show this URL too but they would not need to agree to it. This could be shown at the bottom.

I stopped for now with reviewing as it looks like there may be still some bigger things left to do

2022-01-20 00:10 UTC, peterhashair commented
@tsteur will do an update. :)

2022-02-09 10:19 UTC, sgiehl requested changes
Had rough look through the code and left various comments. Didn't go on with the review and UI testing as actually various requirements aren't obviously met (by looking at the code only). Please review the requirements here https://github.com/matomo-org/matomo/issues/13321#issuecomment-964729030 and adjust the implementation accordingly.

2022-02-09 10:19 UTC, sgiehl commented on plugins/UsersManager/lang/en.json
> +        "AddUser": "Invite a new user",
Please use new translation keys in case the sense of the message changed to ensure existing translations won't be used anymore.

2022-02-09 10:19 UTC, sgiehl commented on core/Updates/4.7.0-b1.php
> +class Updates_4_7_0_b1 extends PiwikUpdates
This needs to be changed to 4.8.0-b1

2022-02-09 10:19 UTC, sgiehl commented on plugins/CoreAdminHome/lang/en.json
> +        "UserInviteNotes": "This invitation was intended for %1$s access, If you were not expecting this invitation, you can ignore this email. If %2$s is sending you too many emails, you can block t
```suggestion
        "UserInviteNotes": "This invitation was intended for %1$s access. If you were not expecting this invitation, you can ignore this email. If %2$s is sending you too many emails, you can block them or report abuse. The invitation expire in 7 days."
```

2022-02-09 10:19 UTC, sgiehl commented on plugins/UsersManager/Controller.php
> +    public function activeInviteUser()
`activeInviteUser` sounds like a bad method name to me. It actually doesn't really say what it does. I guess something like `acceptInvitation` would be a lot more meaningful.

2022-02-09 10:19 UTC, sgiehl commented on plugins/UsersManager/Controller.php
> +        $token = Common::getRequestVar('token');
When using request variables we should try to always provide the expected type to avoid possible issues when using them later. This can be easily achieved using the correct parameters. Would be good to keep that in mind for future PRs as well.

```suggestion
        $userLogin = Common::getRequestVar('login', null, 'string');
        $token = Common::getRequestVar('token', null, 'string');
```

2022-02-09 10:19 UTC, sgiehl commented on core/Db/Schema/Mysql.php
> +                          invite_status varchar(40) DEFAULT NULL,
Is there any benefit and storing the invite_status at all? Actually if there is an `invited_at` timestamp that means, that the user has been invited. And after he accepted, we can simply remove the timestamp and it indicates the users is active.

2022-02-09 10:19 UTC, sgiehl commented on plugins/UsersManager/API.php
> +        }
Does that mean that a super user can invite someone without any initial access to a website?
Btw. might also be good to check if a site with the id `$initialIdSite` actually exists.

2022-02-09 10:19 UTC, sgiehl commented on plugins/UsersManager/API.php
> +
Why should that be needed? Adding a new user shouldn't change anything on the currents user auth. Not should it cause any changes to the tracker, so no need to clear the cache.

2022-02-09 10:19 UTC, sgiehl commented on plugins/UsersManager/API.php
> +        $this->model->addTokenAuth($userLogin, $generatedToken, "Invite Token", Date::now()->getDatetime(),  Date::now()->addDay(7)->getDatetime());
The following requirements aren't fulfilled here:
> By default, the invite is valid for 7 days. This needs to be configurable using the API parameter and as a configuration option.

2022-02-09 11:26 UTC, peterhashair commented
@sgiehl that one is not ready yet :) , but will do a update

2022-02-10 00:02 UTC, peterhashair commented
Just a note, I think this PR will be put on pause for now, currently is on the transaction from angular to VUE. Once the Vue implementation is finished, will transfer it to VUE and fix the remaining task.

2022-04-26 13:17 UTC, sgiehl commented
closing in favor of #18868

2022-04-26 13:17 UTC, closed without merging