[Vue] migrate piwik-period-selector angularjs component
piwik/piwik pull request #18382
Opened 2021-11-26 03:10 UTC by diosmosis

### Description:

**This PR is based off of #18352.**

Changes:

* Migrate piwik-period-selector directive.
* Modify initialization of material selects in corehome.js to exclude ui datepicker controls.
* Add new MatomoUrl.updateLocation() method that updates the hash or whole URL depending on whether we are in a widgetized context or not. Refactor comparisons store to use this method.
* Modify ExpandOnClick/ExpandOnHover to allow string values for `expander` that reference Vue $refs. Without something like this, the directive will be initiated before the rest of the component is mounted, so refs for child elements will be undefined.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-12-02 13:34 UTC, sgiehl requested changes
Left a comment. Otherwise the code is looking fine.
While clicking through the UI I found this regressions:
* The compare dropdown has an incorrect z-index:
![image](https://user-images.githubusercontent.com/1579355/144430645-561f484b-4b48-4273-be95-726d7c75ce6a.png)

* In range selection: when changing a date in the input fields above the date chooser are the choosers only updated when the input field looses the focus. Before it was triggered with each change (guess on keypress or so)

2021-12-02 13:34 UTC, sgiehl commented on matomo.js
> +/* GENERATED: tracker.min.js */
Guess you accidentally committed the changes to the tracker js files.

2021-12-03 10:27 UTC, diosmosis commented
@sgiehl 

> The compare dropdown has an incorrect z-index:

This happens on 4.5.0 too, it's a materialize issue.

> In range selection: when changing a date in the input fields above the date chooser are the choosers only updated when the input field looses the focus. Before it was triggered with each change (guess on keypress or so)

Fixed + another related bug (will now only change the date if it is a full YYYY-MM-DD date).

> Guess you accidentally committed the changes to the tracker js files.

Undid those changes.

2021-12-03 10:38 UTC, sgiehl requested changes
Left a comment. Besides that the CustomAlerts submodule was changed in this PR as well. This should be reverted before merging. When that is changed and tests are passing, feel free to merge this one.

2021-12-03 10:38 UTC, sgiehl commented on plugins/CoreHome/vue/src/DateRangePicker/DateRangePicker.vue
> +          @change="onRangeInputChanged('to', $event)"
Guess this should be `keydown` as well.
```suggestion
          @keydown="onRangeInputChanged('to', $event)"
```

2021-12-03 12:38 UTC, diosmosis commented
There are a couple unrelated failures, one is fixed in another branch, but I'll create a new branch for it just so it's there. I'll look into the other one.

2021-12-03 12:38 UTC, merged

2021-12-03 14:14 UTC, tassoman commented
Hello there, does this migration Vue makes possible to override/modify the period selector calendar? 
My [Plugin RerUserDates](https://github.com/RegioneER/RerUserDates) rely on this but using angular, cannot hook in it .. 🤔

2021-12-04 01:30 UTC, diosmosis commented
@tassoman how specifically do you override/modify it? I can't see any angularjs code in the plugin.

2021-12-06 15:12 UTC, diosmosis commented
Hi @tassoman, I took another look and if you mean the HTML element removal your plugin does then it won't work with Vue anymore. Vue uses a virtual DOM and keeps HTML in sync with it, so if you remove an element, it will just be put back again. I would suggest a different approach:

1. when you determine the element should not be there, add a css class to `html` (eg, `remove-period-option`)
2. then in a LESS file hide the element based on that, eg:

    ```
    html.remove-period-option {
        #periodString ... {
            display: none;
        }
    }
    ```

2021-12-06 15:27 UTC, tassoman commented
Thanks for inspecting my code. I was stuck after the adoption of Angular. 
I'm going to try this trick, looks like quite short and straight. Whithout involving diving deep in the ui frontend.