Rendering performance improvement for reports with many rows
piwik/piwik pull request #18405
Opened 2021-11-30 03:14 UTC by bx80

### Description:

Fixes #18394

Removes the obsolete handleColumnHighlighting() method which causes a significant performance hit when rendering a datatable with many rows.

Column width and row highlighting is now handled by CSS so this method should no longer be needed.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-11-30 18:43 UTC, sgiehl requested changes
This one can't be simply removed. The row highlight is covered by CSS. But when you hover a column, that column receives a class in each row. I don't think this can be covered by CSS. Now the ratio values aren't displayed (e.g. for visits or page views) anymore as it relies on that class. See 
https://github.com/matomo-org/matomo/blob/8066b3536c2399e1c2992c9ee4607b3985b94b42/plugins/CoreHome/stylesheets/dataTable/_dataTable.less#L36-L38

2021-12-01 01:57 UTC, bx80 commented
The 'give all values consistent width' part of handleColumnHighlighting() is the real performance hit, adding mouse event handlers to add/remove classes doesn't really impact loading speed. So I've restored the method and tested again with just the width setting code disabled and performance is basically the same as with the handleColumnHighlighting() method disabled.
![image](https://user-images.githubusercontent.com/88810029/144157166-d705a640-3127-4647-a0d4-2f3b8fb90310.png)
This means the ratio values will work and any other code that relies on the column highlight class being set.

2021-12-01 04:01 UTC, bx80 commented
@sgiehl Following the theme of naively deleting random datatable functions... :wink:

I think the performance heavy setFixWidthToMakeEllipsisWork() method can be replaced with a small CSS tweak. Setting the table cell width to calc(80%) should allow the ellipsis to be applied to the table label column using pure CSS without needing javascript to calculate and set a fixed cell width both initially and every time the table is resized. 

I've committed this change for review and it seems to work well in the tests I've done. Can you think of any problems with this approach or anything I should specifically test?

2021-12-02 14:04 UTC, sgiehl requested changes
Oh dear. I would really love to get rid of that method. Struggling with it already for a while in #18386. The "problem" with all those methods is, that they are doing a lot more, than the name would let you think. The method `setFixWidthToMakeEllipsisWork` is actually also used to limit the width of a datatable to `1200px` (if it's not widgetized), but it also ensures that a datatable doesn't always take all the space that would be available, but only what it really needs. In addition if fixes the size of the tables in "reportByDimension" view, which can be seen in the goal reports (the one with the additional dimension menu on the left). And I'm pretty sure it's responsible for some more stuff I don't see right now.

Removing that method actually broke most of the additional stuff...
Maybe for now remove that again, so we can already merge the other improvement. If needed you can then create new PRs with further improvements.

2021-12-02 14:04 UTC, sgiehl commented on plugins/CoreHome/stylesheets/dataTable/_dataTable.less
> +    width: calc(80%);
Why is that `calc` needed here? Isn't `80%` a fixed value? Also `calc` is a less method used here, to use a css `calc` it would need to be `width: ~"calc(80%)"`

2021-12-02 21:10 UTC, bx80 commented on plugins/CoreHome/stylesheets/dataTable/_dataTable.less
> +    width: calc(80%);
My mistake, I was thinking CSS. Ellipsis need a fixed width in order to work, calc() outputs a fixed width but handles resizing etc without javascript. Clearly there is a lot more going on with `setFixWidthToMakeEllipsisWork` than I'd initially realized, thanks for pointing it out. I'll revert the change and back away slowly.

2021-12-03 09:56 UTC, sgiehl requested changes
The code changes look fine. But there are actually a lot failures in the UI tests. Once the new build is finished you may need to look through all those changes, and check if they are actually expected, or if there are some regressions, where the table sizing maybe doesn't work correctly anymore.

2021-12-06 01:14 UTC, bx80 commented
I've updated all the screenshots for UI tests that failed from this change.

2021-12-06 12:56 UTC, sgiehl approved these changes
Looks got to merge now. 
Btw. you forgot to create PR in submodule plugin to update the screenshots. I've done that for you. Also changing any submodule to another branch than 4.x-dev always needs to be reverted before a PR is merged. I'll do that once I saw if all related screenshot tests are passing.

2021-12-06 13:36 UTC, merged