convert sparkline api to one request - fixes archive
piwik/piwik pull request #18493
Opened 2021-12-12 22:09 UTC by peterhashair

### Description:

Description:
Fixes: #18088.

Follow the fix on UI tests

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-12-15 01:28 UTC, peterhashair commented
this is the follow-up on the UI failed fixes. Should pass the test now.

2021-12-15 02:05 UTC, bx80 commented
@peterhashair The only remaining failing UI screenshot `UIIntegrationTest_dashboard2.png` is expecting the goals overview widget goal titles to be wrapped in single quotes, where as the processed screenshot has them without.
![image](https://user-images.githubusercontent.com/88810029/146109047-2ba9c060-1bfa-4d97-94f9-d53196351d82.png)
It seems like it might be related to this change?

2021-12-16 03:34 UTC, bx80 approved these changes
UI tests are now all passing. 

I noticed that because the `GetMetrics` report is a now a descendant of the `Get` report that the view is configured slightly differently with overview Goal Names shown as `Goal 'Something'` instead of `Goal Something`. This would seem to be more consistent, what do you think @sgiehl ?

2021-12-16 22:29 UTC, sgiehl requested changes
Generally seems to work now. Left a couple of comments for code improvements

2021-12-16 22:29 UTC, sgiehl commented on plugins/Goals/Pages.php
>          foreach ($goals as $goal) {
I guess this `foreach` is no obsolete. As `$widgets` isn't used afterwards anymore, there is no sense it filling it more.

2021-12-16 22:29 UTC, sgiehl commented on plugins/Goals/Controller.php
> +        $queryString = $_SERVER['QUERY_STRING'];
seems unused
```suggestion
```

2021-12-16 22:29 UTC, sgiehl commented on plugins/Goals/Controller.php
> +        $goals = Request::processRequest('Goals.getGoals', ['idSite' => $idSite, 'filter_limit' => '-1'], []);
```suggestion
        $goals = Request::processRequest('Goals.getGoals', ['idSite' => $this->idSite, 'filter_limit' => '-1'], []);
```

2021-12-16 22:29 UTC, sgiehl commented on plugins/Goals/Controller.php
> +        $apiAction = $apiProxy->buildApiActionName($module, $action);
Can't see much value in checking and building the API action name using those methods. Guess you could also simply use `Goals.getMetrics`. If that one gets deleted somewhen, this method will throw an exception nevertheless, as the report can't be found at another point while processing the view.

2021-12-17 13:34 UTC, sgiehl requested changes
Had another idea for further code improvement. Otherwise this should be good to merge, if tests are passing.

2021-12-17 13:34 UTC, sgiehl commented on plugins/Goals/Controller.php
> +            $content .= $view->render();
Here you could use `Context::executeWithQueryParameters`, which will ensure the request parameters are reset afterwards.
```suggestion
            $params = [
                'idGoal' => $goal['idgoal'],
                'allow_multiple' => (int) $goal['allow_multiple'],
                'only_summary' => 1,
            ];

            \Piwik\Context::executeWithQueryParameters($params, function() use (&$content) {
                //load Visualisations Sparkline
                $view = ViewDataTableFactory::build(Sparklines::ID, 'Goals.getMetrics', 'Goals.' . __METHOD__, true);
                $view->config->show_title = true;
                $content .= $view->render();
            });
```

2021-12-19 12:39 UTC, merged