add enable browser detection and some tests
piwik/piwik pull request #18633
Opened 2022-01-17 04:25 UTC by peterhashair

### Description:

Fixes: #18448 
add enable browser detection and some tests

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-01-17 04:25 UTC, peterhashair commented
build js

2022-01-17 06:27 UTC, peterhashair commented
@sgiehl sorry to bother, just checking what would be the best approach for piwik.js _pag.push tests I found here, https://github.com/matomo-org/plugin-AnonymousPiwikUsageMeasurement/pull/68 add it here. not sure if that's correct.

2022-01-17 16:24 UTC, sgiehl requested changes
@peterhashair seems there are some JSLint errors, that need to be fixed. Otherwise looks good.
@tsteur would that be something that should be included in 4.7.0 release?

2022-01-17 19:00 UTC, tsteur commented
Very low risk of breaking something so that could be included.

Be also good to add more tests. We could make sure no browser resolution and detected plugins information is in the tracking request when disabled. Seems the other usages of `detectBrowserFeatures` might be less testable because they are partially including random uids etc.

We'd also need to update the previously FAQ to mention the new method.

We also need to update https://developer.matomo.org/api-reference/tracking-javascript to mention the new methods.

BTW are these new methods mentioned in the developer changelog?

This is documented in https://developer.matomo.org/guides/jstracker-core#adding-a-new-public-js-tracker-method

2022-01-19 01:12 UTC, peterhashair commented
@tsteur regarding the tests, I was thinking this test include the browser resolution check. Should I do a fake tracking in Integration tests? 
```javascript 
    test("Browser detector feature Disable and enable", function() {
      var pattern = /res/;
      var tracker = Piwik.getTracker();
      tracker.disableBrowserFeatureDetection();
      var request = tracker.getRequest('hello=world');
      equal(pattern.test(request), false, 'Disable browser fingerprint');

      tracker.enableBrowserFeatureDetection();
      var request = tracker.getRequest('hello=world');
      equal(pattern.test(request), true, 'Enable browser fingerprint set');

    });
```

2022-01-19 01:15 UTC, tsteur commented
Above test looks good. You'll also want to check this for the other tracking parameters. And could also adjust the messages like `Disable browser fingerprint'` change it to `When browser fingerprint is disabled the request should not include browser resolution'`

2022-02-03 09:29 UTC, sgiehl commented
@peterhashair There are still some JSLint errors to be fixed. If you need help with that, let me know.

2022-02-03 23:04 UTC, peterhashair commented
@sgiehl found it, fixed it. 😀

2022-02-04 10:04 UTC, sgiehl requested changes
Left some minor comments. Otherwise looks good.

2022-02-04 10:04 UTC, sgiehl commented on tests/javascript/index.php
> +        equal(pattern.test(requestWithFingerprint), true, 'When browser fingerprint is enabled the request should include browser resolution and cookie');
Doesn't the pattern actually tests if the string contains resolution or cookie?

2022-02-04 10:04 UTC, sgiehl commented on tests/javascript/index.php
> +
maybe try to avoid too many useless empty lines

2022-02-08 21:43 UTC, peterhashair commented on tests/javascript/index.php
> +        equal(pattern.test(requestWithFingerprint), true, 'When browser fingerprint is enabled the request should include browser resolution and cookie');
@sgiehl ah should I change this part ` var pattern = /(res=)|(cookie=)/;`

2022-02-14 07:06 UTC, merged