invite user replace add user - draft version
piwik/piwik pull request #18868
Opened 2022-03-02 01:28 UTC by peterhashair

### Description:

SInce we move UsersManager to VUE. 

invite user replace add user - draft version

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-03-04 00:35 UTC, peterhashair commented
@sgiehl I got a question for the structure, is that ok for me to move some of the `API.php` private methods to a different class, just the public method remains in the API.php. In this case, is the UsersManager/API.php

2022-03-07 09:58 UTC, sgiehl commented
> @sgiehl I got a question for the structure, is that ok for me to move some of the API.php private methods to a different class, just the public method remains in the API.php. In this case, is the UsersManager/API.php

If private API methods could be reused somewhere else, it makes sense to move them to another class.

2022-04-21 00:00 UTC, peterhashair commented
@diosmosis sorry to bother, just checking for the Build Vue, I keep getting errors from plugin `MobileMessaging ` any idea, what causing that one?

2022-04-21 00:08 UTC, diosmosis commented
@peterhashair ScheduledReports isn't in MobileMessaging's umd.metadata.json so it's not being built first. Rebuilding locally adds it back for me. Or you can add it manually, the file should look like:

```
{
  "dependsOn": [
    "CoreHome",
    "CorePluginsAdmin",
    "ScheduledReports"
  ]
}
```

I'm not sure why it isn't there, though.

2022-06-01 03:22 UTC, bx80 requested changes
@peterhashair Looking good overall :+1: 

I noticed a couple of issues: 

The `Resend Invite` action shows for all users even if they haven't been invited, this could be confusing and an error is shown when attempting to reinvite existing users. It would be good to hide `Resend Invite` if the user hasn't been invited.
![image](https://user-images.githubusercontent.com/88810029/171319685-e79ef288-6560-4435-bc59-d35a6e020542.png)

After creating an invite for a new user, following the accept link and entering a new password an error is shown:
![image](https://user-images.githubusercontent.com/88810029/171319541-e53e4031-fc8b-4c2d-a728-d30f0c6b0bda.png)
This happens when already logged in as one user who creates the invite, then the accept link is opened in the same browser. Probably not a common scenario but it could happen, especially when testing.

2022-06-02 02:34 UTC, peterhashair commented
@bx80 fixed it.

2022-06-06 23:46 UTC, bx80 approved these changes
The resend invite action is only showing when an invite has been sent :+1:

The `defaultReportDate` was due to an out of date plugin I had installed - no issue once the plugin was deactivated :+1:

2022-06-06 23:47 UTC, merged

2022-06-07 13:14 UTC, sgiehl reviewed
Here would have really a lot changes been required before I would have considered this PR as mergeable.

The most important ones are:
- Using a token_auth as invite token is kind of a security problem, as it allows using the API without even accepting the invite
- The tests are not covering the whole process. It's nice that all screens are covered by a UI test, but it would also be important to really click the `accept` or `decline` button and see what happens afterwards. Not having tests for that has the risk, that this might regress in the future and we won't see that.
- The user experience of this new feature is quite bad, as in a lot places the success notifications are missing and the users doesn't see if his action actually worked or not.
- ~Some~ Most of the requirements of the original issue aren't fulfilled. To mention some important ones of the list here: https://github.com/matomo-org/matomo/issues/13321#issuecomment-964729030
   - Activity log should recognise "invite user" and "invite user accepted".
     --> see comments about missing / changed events
   - A user can also decline the invite in which case the person that created the invite is being notified by email and we remove the user entry to have no personal data in there. (we might need to store in the user table who invited the user, if that user login no longer exists then we don't notify anyone)
   --> currently the user remains in the database
   - When a user clicks on accept invite, they enter their password. If privacy policy or terms is configured, then we show these links. We say eg if privacy policy is configured: By signing up, I accept the Privacy Policy. If terms is configured we say it similarly for terms. If both are configured then we mention both.
   --> currently there is always Terms & Conditions displayed.
   - In addition the UI currently doesn't allow to see when a invite expire, nor is it possible to show all invited users (e.g. by a filter).
   - Invited users can be seen by super users, and the person that invited that user.
   --> currently everyone who has permission can see the user, as invites are created as a normal users.

2022-06-07 13:14 UTC, sgiehl commented on core/Db/Schema/Mysql.php
> +                          invite_status enum('accept','pending','decline','expired') DEFAULT 'accept',
Using enums is not always the best choice. For this table it might not hurt too much, but for tables that might contain a lot data, we should never use enums, as it is a very expensive operation to change them again later. Personally I would have preferred using a simple integer column and assigning the logical values in PHP only.

2022-06-07 13:14 UTC, sgiehl commented on core/Validators/Login.php
> +class Login extends BaseValidator
Is this Validator actually used anywhere? If I see that correct, it's also included in a similar way in the UsersManager plugin.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +        if ($user['invite_status'] !== 'pending') {
Won't this throw a notice if the user can't be found with the token? Guess `$user` would be `null` in that case.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +        if (!$user) {
This check would only make sense above the previous one, as it can't be reached here. But actually it doesn't make sense at all. There should be only "invalid token" error, if no user can't be found with the token, or the invite status isn't pending.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +
The try/catch is actually useless, as `safeSend` already catches any errors and doesn't throw any.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +        if ($user['invite_status'] !== 'pending') {
Like in the other action, this might trigger a notice/warning.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +        if (!$user) {
Like in the other action, this check can't be reached.

2022-06-07 13:14 UTC, sgiehl commented on tests/resources/OmniFixture-dump.sql
> +  `invite_status`  enum('accept','pending','decline','expired'),
Changes to the omnifixture sql are **NOT** needed. Once the SQL is set up for tests an update is performed, which will trigger all update scripts that were added after the omnifixture was last built (based on the version included in this sql).

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UsersManager/UsersManager.vue
> +      console.log(user);
that should be removed

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UsersManager/UsersManager.vue
> +        console.log(res);
Why is there a single `console.log` in the `then`? Is nothing supposed to happen after the resend was sent? Shouldn't there be some sort of success notification? The user currently does not get any feedback it it worked or not!

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/templates/inviteLayout.twig
> +{% block meta %}
Adding this file could have been avoided. It actually has the same content as `Login\loginLayout.twig`. Only the title differs, which can be simply overwritten in the files using the layout.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +            $this->redirectToIndex('Login', 'index');
Simply redirecting the user to the login, doesn't give them any feedback if the decline actually worked. Also does showing the login form not make any sense. The user just declined to be invited so why should he want to use the login form? Makes more sense to only show a message, that the invite was declined.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/templates/invitation.twig
> +                                        <span>{{ 'PrivacyManager_TermsAndConditions'|translate }}</span>
Sorry, but that checkbox is crap, this way:

![image](https://user-images.githubusercontent.com/1579355/172337281-a4275b9d-2355-4aed-8522-53ed48b97ac5.png)

If the user should accept any terms and conditions, it should be written that way. E.g. "I accept the Terms & Conditions". Also the terms and conditions should be linked. Why should anyone accept any terms, if he actually can't read them.

The PrivacyManager plugin has a setting for the Terms & Condition URL. If it is set, it should be linked here.
If it isn't set, I guess it doesn't make sense to have the checkbox at all.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/lang/en.json
> +        "Yes": "Yes",
There is already "General_Yes", which could have been used instead of adding a new translation with the same content & meaning"

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/API.php
> +        Piwik::checkUserIsNotAnonymous();
This check is redundant, as the anonymous user can't have super user access, which is checked below.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Emails/UserInviteEmail.php
> +          [$this->currentUser, $this->user['login']]);
The resulting sentence doesn't make much sense to me. It's currently something like
`admin sent you an invite to join Matomo Analytics for {newuser}.`
It should either be something like `admin sent you an invite to join Matomo Analytics as {newuser}.` Or the second placeholder should contain the site the user will have access to.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Emails/UserInviteEmail.php
> +          ["<strong>" . $this->currentUser . "</strong>", "<strong>" . $this->user['login'] . "</strong>"]);
Same as above

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Emails/UserInviteEmail.php
> +        $view->notes = Piwik::translate('CoreAdminHome_UserInviteNotes', [$this->user['login'], $this->currentUser]);
Using the login as placeholder doesn't seem to make sense here either:
`This invitation was intended for {newuser} access. If you...`
What should that actually tell the user?

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Repository/UserRepository.php
> +namespace Piwik\Plugins\UsersManager\Repository;
A general note: For new classes and methods it would be helpful if we can directly try to use more strict types. e.g. using type hints for method parameters as well as using return type hints where possible.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Model.php
> +    public function getPendingUser($userLogin)
That method should better be named `isPendingUser` as it returns the current state and not the user details. Also the return value might be better casted to boolean.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Model.php
> +        return $user;
Any reason for changing the return signature? Can't see that the return value is actually used somewhere

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +                //update pending user to active user
Shouldn't the invite token be removed at that point? Otherwise it will remain in the database.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/API.php
> -        Piwik::postEvent('UsersManager.addUser.end', array($userLogin, $email, $password));
Removing this event and using `UsersManager.inviteUser.end` instead is a breaking change as various of our plugins currently use that event and will fail in the future.
Also new or removed events should always be mentioned the in changelog.md

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Repository/UserRepository.php
> +              Date::now()->addDay($expired)->getDatetime());
Are you aware of the implications using a temporary token auth for this has?
The invite token can also be used to authenticate against the full API. That means a user can use the API with this token even if he didn't click on accept or decline. And even if he clicks, the token isn't removed and can be used until it expires. This might be a security problem.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Repository/UserRepository.php
> +    public function index($userLogin, $pending)
Is that method actually used anywhere? If so it could for sure have a better name.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/Repository/UserRepository.php
> +class UserRepository
Actually I wonder why you moved some of the methods to this new `Repository` class. Looking at the methods it actually does not much what I would expect from a repository pattern. Checking access for anything would be something I wouldn't expect for example. That should be done by methods using a repository pattern to access data.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +
It would be good to introduce new events like `Login.invitation.accept` and `Login.invitation.decline`, that we could listen on e.g. for plugins like `ActivityLog`

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/tests/UI/Decline_spec.js
> + * login & password reset screenshot tests.
either remove such comments when you copy a file or update it so it matches the content.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/tests/UI/Invite_spec.js
> + * login & password reset screenshot tests.
either remove such comments when you copy a file or update it so it matches the content.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +        }
the try/catch here is unneeded as well.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/lang/en.json
> +        "InvitationDeclineBody": "Are you sure you want to decline this Invitation?",
We should try to use correct english where possible. As far as I know in English most stuff should be written in lower case, unless it's a name or similar.
```suggestion
        "InvitationTitle": "Accept invitation",
        "InvitationDeclineTitle": "Decline invitation",
        "InvitationDeclineBody": "Are you sure you want to decline this invitation?",
```

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/templates/invitation.twig
> +                                           tabindex="1" required/>
Is there are reason for having `required` for the password, but not for the password confirmation. Actually it would make sense to have it on both, so the browser prevents sending an empty password confirmation.

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/Controller.php
> +                }
I guess those checks are actually not needed. Why should the password that was provided in the input fields be already hashed??

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/tests/Fixtures/PendingUsers.php
> + * This Simple fixture adds one website and tracks one visit with couple pageviews and an ecommerce conversion
no. it doesn't....

2022-06-07 13:14 UTC, sgiehl commented on plugins/Login/tests/UI/Invite_spec.js
> +
Wouldn't have a test made sense, where the user really accepts the invitation. The users should be logged in automatically, so we could check if he is afterwards showing the dashboard or similar. That prevent possible regressions in that process in the future.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/API.php
> +        Cache::deleteTrackerCache();
Why exactly should it be required to clear the tracker cache here?

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/tests/Integration/APITest.php
> +        $this->expectExceptionMessage('UsersManager_CurrentPasswordNotCorrect');
Why does this test result change? There shouldn't have been any changes in the addUser/updateUser methods that should cause this.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/tests/Integration/APITest.php
> +        $this->expectExceptionMessage('UsersManager_ExceptionLoginExists');
This also looks rather unintended.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/tests/Integration/UsersManagerTest.php
> +        $this->assertEquals($content, $view->render());
What exactly are you trying to test here? Testing if Twig is really able to fill in some placeholders doesn't really look like a useful test case for me. But it would make sense to check if inviting a user sends out an email...

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/tests/UI/UsersManager_spec.js
> +        expect(await page.screenshotSelector('.usersManager')).to.matchImage('resend_popup');
might have been enough to only take a screenshot of the confirmation popover, to avoid updating the screenshot something else on that page changes.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
> +               v-if="isPendingUser"
This doesn't seem to work. It is hidden after an user has been invited and the edit screen is displayed. But when I click in edit for a user in pending state in the users list, the password field will be shown.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
> +                          translate('UsersManager_InviteSuccessNotification', [7]))"></span>
This actually seems to be shown never. When a new user is invited there is a success message "The changes have been saved", but this message isn't shown.

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
> +      return this.user && (this.theUser.invited_at === '' || !this.theUser.invited_at);
shouldn't this check be based on the invite status?

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
> +}
What benefit has it to introduce a scope style here. The component already has it's own stylesheet, where that property could have been easily changed if needed:
https://github.com/matomo-org/matomo/blob/d036954668dcd4cf8cb4a5235cbed7519503d0f6/plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.less#L37-L41

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/tests/UI/UsersManager_spec.js
> +        });
Why should this be needed now? Can't see any change that should require this test change.
Also one of the ongoing tests now has a unexpected screenshot, where no users are shown at all. 
See https://github.com/matomo-org/matomo/blob/4b38727169e378c3fdc77a4a0ed3ede20cf00ab0/plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_bulk_access.png

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/User.ts
> +  invited_at?: string;
seems the `invitead_at` field, that existed in a previous version of this PR, was meanwhile removed. So this should be removed as well or changed to `invite_status`

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
> +        this.theUser.invited_at = 'xx';
What should that be good for 🤔

2022-06-07 13:14 UTC, sgiehl commented on plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
> +  invited_at: '',
This seems no valid user property anymore.

2022-06-08 00:30 UTC, bx80 commented
Thanks for that @sgiehl, you are right -  there are several issues here that should have been caught during review and will need to be addressed with a fix PR.

With the auth token issue, what do you think about adding a boolean flag  `invite_token` to the `user_token_auth` table to indicate that the token is only valid for user invitation, similar to the existing `system_token` option? Any attempt to use an `invite_token` for general API access could then be rejected in addition to removing the token entirely once the invite is accepted / rejected?

2022-06-08 06:51 UTC, sgiehl commented
@bx80 using the token auth table for that might not have been the best choice, as it will require to change all the existing code, that by default when checking for tokens it will need to ignore such special tokens. 

Personally I might have added two fields to the user table. `invite_token` and `invite_expire`
I'm not sure if we would need a status field at all.
If someone is invited, the generated token will be stored in `invite_token`, together with the expire datetime in `invite_expire`.
Every user where both fields are filled is in the state `pending`.
If the expire datetime passes, we can show `expired` as status.
If a user declines the request, the requirements actually defined, that the user should be removed, to avoid storing any personal data, so this status isn't needed.
If a user accepts the invite, both invite fields would be cleared and such users will have the status `active`.

2022-06-08 09:20 UTC, peterhashair commented
@sgiehl that makes sense, I will rework the table structure on that one.