[Vue] migrate manage gdpr directive to Vue
piwik/piwik pull request #19002
Opened 2022-03-26 21:04 UTC by diosmosis

### Description:

**This PR is based off of #18993.**

Changes:
* Migrate manage gdpr directive to Vue.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-04-05 17:03 UTC, sgiehl requested changes
Left some minor comments. Otherwise this looks good.

2022-04-05 17:03 UTC, sgiehl commented on plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.vue
> +        value="Find matching data subjects"
This one could be move to a translation

2022-04-05 17:03 UTC, sgiehl commented on plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.vue
> +              :title="`(ID ${dataSubject.idSite})`"
We could use `General_Id` instead of `ID` here.

2022-04-05 17:03 UTC, sgiehl commented on plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.vue
> +          this.hasSearched = true;
We should maybe reset the variable to `false` when a new search is triggered. Currently for each search done after the first one, the result display the no data message until the search finishes. Would be better to hide the message, so it's clearer if it is the actually result or not.

2022-04-05 23:08 UTC, diosmosis commented
@sgiehl applied the fixes

2022-04-06 01:39 UTC, peterhashair approved these changes

2022-04-06 08:24 UTC, merged