[Vue] migrate scheduled reports management from twig/angularjs to vue
piwik/piwik pull request #19012
Opened 2022-03-28 23:23 UTC by diosmosis

### Description:

Changes:
* Migrated scheduled reports management from twig/angularjs to vue.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-04-04 21:22 UTC, diosmosis commented
Converting to draft for a bit, might be possible to provide full BC.

2022-04-07 09:32 UTC, sgiehl requested changes
Left a couple of comments for smaller improvements / fixes. Otherwise looks good.

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/ScheduledReports.php
> +        $translationKeys[] = 'ScheduledReports_ReportFormat';
That one seems to be a duplicate
```suggestion
```

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/vue/src/ManageScheduledReport/ManageScheduledReport.vue
> +        this.fadeInOutSuccessMessage(
I guess it was already the same before, but `fadeInOutSuccessMessage` currently always does a page reload. At this point that is actually not needed, as no new information could be displayed anyway.

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/vue/src/ManageScheduledReport/ManageScheduledReport.vue
> +        this.fadeInOutSuccessMessage(
That method does a page reload, so guess we could remove the `redirectOnSuccess: true,` above, as the request caused by that gets aborted directly.

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/templates/index.twig
> +  title="{{ title|default(null)|json_encode|e('html_attr') }}"
Using an attribute named `title` causes a tooltip to be shown everywhere within that div. So might be better to use another name here.

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/templates/index.twig
> +  title="{{ title|default(null)|json_encode|e('html_attr') }}"
In addition the `json_encode` here also causes special charts like umlauts to be displayed encoded in the tooltip.
Does Vue always perform a json_decode on input attributes? Or might that happen for other parameters within vue as well?

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/vue/src/ListReports/ListReports.vue
> +                  ? report.format : undefined,
We maybe could use `original` here as default. Currently downloading a SMS report won't work, as the API request doesn't contain a format and uses `XML` as default.

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/vue/src/AddReport/AddReport.vue
> +              v-html="reportSegmentInlineHelp"
this misses a `$sanitize`

2022-04-07 09:32 UTC, sgiehl commented on plugins/ScheduledReports/vue/src/AddReport/AddReport.vue
> +        v-html="entityCancelText"
this misses a `$sanitize`

2022-04-07 15:08 UTC, diosmosis commented on plugins/ScheduledReports/templates/index.twig
> +  title="{{ title|default(null)|json_encode|e('html_attr') }}"
There's a JSON.parse() in the code that handles `vue-entry` in `piwikHelper`. Vue doesn't exist in HTML, all props in Vue are already instantiated, unserialized JavaScript values.

2022-04-07 15:29 UTC, sgiehl commented
@diosmosis just found one last regression on this one. If the description of the report contains a special char like `<` or `"` it will be displayed encoded. Guess the "problem" is that the title is already stored encoded in the database. Before it was using `rawSafeDecoded` in twig. Not sure if we already have something similar in vue to use.

2022-04-07 15:37 UTC, diosmosis commented
@sgiehl :+1: we'd just decode it client side. Vue just sets textContent/innerText so its safe (unless using v-html which uses innerHTML).

2022-04-08 12:44 UTC, sgiehl approved these changes

2022-04-08 12:45 UTC, merged