[CSS] add scroll to live visits table
piwik/piwik pull request #19273
Opened 2022-05-26 00:31 UTC by peterhashair

### Description:

Fixes: #19254 
add scroll to live table

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-05-30 05:39 UTC, bx80 requested changes
This solves the issue for my tests :+1: 

Since this issue is a regression it would be good to add a simple UI test screenshot of the dashboard with the window set to a size that causes the visits table header to overflow.

2022-06-01 08:28 UTC, sgiehl commented on plugins/Live/stylesheets/live.less
> +    overflow-x: scroll;
This will actually always add a scrollbar to the widget. Would be good to only have it, if it is needed.

2022-06-07 01:28 UTC, bx80 commented
I've bumped the UI tests to run again, just want to be sure that the Movers and Shakers widget overflow is a random test failure and not something else.

2022-06-07 02:36 UTC, bx80 commented
The small screen dashboard UI test movers and shakers overflow is still failing each time on Travis but it passes when run locally, I've increase the delay from 250ms to 500ms to see if that fixes it.

2022-06-07 03:55 UTC, bx80 approved these changes

2022-06-09 00:58 UTC, merged