[UI] goal overview conversion rate not showing correct on the graph
piwik/piwik pull request #19324
Opened 2022-06-09 01:57 UTC by peterhashair

### Description:

I found when you change the matrix it doesn't work, but after reloading the page, it shows correctly, only a quick fix, but the not perfect solution, trying to find the perfect solution here.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-06-13 22:26 UTC, bx80 requested changes
It looks like the conversion rate isn't being formatted as a percent on the graph. Here is a goal with a 10.22% conversion rate (as per the sparkline). 
![image](https://user-images.githubusercontent.com/88810029/173455944-5738b16c-9f20-4cda-83c6-272397ebc1c0.png)
When I click this goal on the goals overview screen the graph shows a 0.1% conversion rate 
![Screenshot_20220614_102037](https://user-images.githubusercontent.com/88810029/173457756-34d82372-2835-4de6-939c-b6a9bdd75f3c.png)

so the metric data is being loaded, but it's not formatted correctly.

2022-06-14 00:25 UTC, peterhashair commented
@bx80 ah I couldn't reproduce that on mine, can you check if the sparkline for Feb 2022 matches the data. Maybe the date selector was on Feb, not Jan.

2022-06-14 02:47 UTC, bx80 commented
@peterhashair, my mistake - formatting is working correctly after a cache refresh :+1:

2022-06-14 02:48 UTC, bx80 approved these changes

2022-06-14 03:03 UTC, merged