[Graphic]reload table if the default date changes
piwik/piwik pull request #19349
Opened 2022-06-13 05:36 UTC by peterhashair

### Description:
Fixes: #18781 
reload table if the default date changes

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-06-13 05:54 UTC, bx80 commented
@peterhashair I think the desired behavior should be to use the configured defaultLastN period unless there is a remembered lastN from a previous selection. 

It seems this is almost happening except that the lastN dropdown value is initialized as 90 days but the data table is loading data for 30 days. I think the initial data table load should match the value of the lastN dropdown (90 days in this case).

Forcing a reload of the data table when it already exists is going probably to be bad for performance as this will apply to every visualization in every circumstance so big data tables may be reloaded multiple times when they don't need to be.

It might be worth checking where both the evolution lastN dropdown and data table load are getting their initial values. Whatever logic is setting the lastN dropdown to 90days should also be instructing the data table initial load to be 90days too. It would be better to get the data table to load the correct lastN first time rather than having it load the wrong values and then do a second load for the correct values. Hope that makes some sense! :slightly_smiling_face:

2022-06-13 07:14 UTC, peterhashair commented
@bx80 yes, I add a flag in to the evolution, when the lastN is remember force the reload, otherwise, it won't reload.

2022-06-14 02:45 UTC, peterhashair commented
@sgiehl sorry try to understand this a little bit more, I believe we init load the data from this point
https://github.com/matomo-org/matomo/blob/0d8d469dd88c6aa3009182202e5bea20d31742ac/plugins/CoreHome/DataTableRowAction/RowEvolution.php#L153 

At this point the customer params are not loaded.  it's the possible we load evolution config before  this line`$url = Url::getQueryStringFromParameters($parameters);`.

2022-06-14 03:46 UTC, peterhashair commented
@bx80 fixed it, found how to load the data, and put it onto the first API loads. but it seems like the PHPCS started to fail on all my PRs.

2022-06-15 03:17 UTC, bx80 commented
This is works well for me, nice to catch the cached parameters and get the table loading the correct data first time :+1:

Other than the array key validation tweak, it should be good to go :slightly_smiling_face:

2022-06-15 03:18 UTC, bx80 requested changes

2022-06-15 03:18 UTC, bx80 commented on plugins/CoreHome/DataTableRowAction/RowEvolution.php
> +            $lastDay = !empty($cache) ? $cache['evolution_' . $this->period . '_last_n'] : null;
```suggestion
            $lastDay = (isset($cache['evolution_' . $this->period . '_last_n']) ? $cache['evolution_' . $this->period . '_last_n'] : null);
```
The cache object might be non-empty but still not contain `evolution_xxx_last_n` key

2022-06-15 04:35 UTC, bx80 approved these changes

2022-06-15 05:58 UTC, merged

2022-06-15 09:05 UTC, sgiehl commented on plugins/CoreHome/DataTableRowAction/RowEvolution.php
> +            $lastDay = (isset($cache['evolution_' . $this->period . '_last_n']) ? $cache['evolution_' . $this->period . '_last_n'] : null);
Just a small note: This could have been simplified to:
```php
$lastDay = $cache['evolution_' . $this->period . '_last_n']) ?? null;
```