[Vue] remove angularjs use from UserCountry
piwik/piwik pull request #19381
Opened 2022-06-21 23:16 UTC by diosmosis

### Description:

Changes:
* Make the Sparkline.vue component work more like the sparkline macro (adding width/height params, allow supplying a string URL + make sure loading attribute is set the same).
* Move getDistinctCountries.twig and adminIndex.twig contents to two new Vue components.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-07-27 14:19 UTC, sgiehl requested changes
Left a comment. Otherwise looks good.

2022-07-27 14:19 UTC, sgiehl commented on plugins/CoreHome/vue/src/Sparkline/Sparkline.vue
> +    height: Number,
The sparkline on the reporting page is displayed too big.
The twig template used `width=200`, `height=50`. Not sure if we should use those as default values here, or pass them through for each sparkline.

2022-07-28 08:28 UTC, diosmosis commented on plugins/CoreHome/vue/src/Sparkline/Sparkline.vue
> +    height: Number,
:+1: added explicit width/height. width=200/height=50 turned out to be too big though, I checked demo.matomo.cloud and it seems to be 100x25, so I used that. Not sure where that came from before though.

2022-07-28 09:49 UTC, sgiehl approved these changes

2022-07-28 09:49 UTC, merged