[Vue] remove angularjs from marketplace
piwik/piwik pull request #19416
Opened 2022-06-27 21:22 UTC by diosmosis

### Description:

Changes:
* Convert twig templates/macros in CorePluginsAdmin that use angularjs directives to Vue.
* Move PluginName.ts vue directive to CorePluginsAdmin to solve circular dependency issue.
* Convert twig templates in Marketplace to Vue components.
* Remove angularjs => vue adapters.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-08-10 15:48 UTC, sgiehl requested changes
Not yet finished with the review, but already want to leave the stuff I've found. Might add more comments if anything else doesn't work.

Edit: Review finished. haven't found anything else.

2022-08-10 15:48 UTC, sgiehl commented on plugins/Marketplace/templates/uploadPluginDialog.twig
> +    vue-entry="CorePluginsAdmin.UploadPluginDialog"
Looks like this template isn't in use anymore and can be removed...

2022-08-10 15:48 UTC, sgiehl commented on plugins/CorePluginsAdmin/vue/src/PluginsIntro/PluginsIntro.vue
> +        v-html="$sanitize(teaserExtendPiwikByPluginText)"
We should try to avoid `Piwik` in new variable names and use `Matomo` instead.

2022-08-10 15:48 UTC, sgiehl commented on plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTableWithUpdates.vue
> +    :content-title="`${Object.keys(pluginsHavingUpdate).length } Update(s) available`"
Looks like this could be made translatable

2022-08-10 15:48 UTC, sgiehl commented on plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTableWithUpdates.vue
> +        || Object.values(this.pluginsSelected).some((s) => !!s);
This might be incorrect. Currently the update button is disabled initially, selecting a plugin keeps it disabled, but as soon as you disable one plugin the button becomes active 🤔

2022-08-10 15:48 UTC, sgiehl commented on plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTable.vue
> +                    v-if="plugin.info?.donate.flattr"
Shouldn't that also be
```suggestion
                    v-if="plugin.info?.donate?.flattr"
```

2022-08-10 15:48 UTC, sgiehl commented on plugins/Marketplace/vue/src/GetNewPluginsAdmin/GetNewPluginsAdmin.vue
> +            width="100%"
Seems the images are currently rendered with `width="0"`, causing them to be hidden

2022-08-16 01:21 UTC, diosmosis commented on plugins/Marketplace/templates/uploadPluginDialog.twig
> +    vue-entry="CorePluginsAdmin.UploadPluginDialog"
👍

2022-08-16 01:23 UTC, diosmosis commented on plugins/CorePluginsAdmin/vue/src/PluginsIntro/PluginsIntro.vue
> +        v-html="$sanitize(teaserExtendPiwikByPluginText)"
👍

2022-08-16 01:26 UTC, diosmosis commented on plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTableWithUpdates.vue
> +    :content-title="`${Object.keys(pluginsHavingUpdate).length } Update(s) available`"
👍

2022-08-16 02:31 UTC, diosmosis commented on plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTableWithUpdates.vue
> +        || Object.values(this.pluginsSelected).some((s) => !!s);
👍

2022-08-16 02:31 UTC, diosmosis commented on plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTable.vue
> +                    v-if="plugin.info?.donate.flattr"
👍

2022-08-16 02:31 UTC, diosmosis commented on plugins/Marketplace/vue/src/GetNewPluginsAdmin/GetNewPluginsAdmin.vue
> +            width="100%"
👍

2022-08-16 02:31 UTC, diosmosis commented
@sgiehl applied more fixes

2022-08-16 10:03 UTC, sgiehl approved these changes
couldn't find any further issues...

2022-08-16 10:03 UTC, merged