[Vue] remove angularjs from Installation plugin
piwik/piwik pull request #19425
Opened 2022-06-28 22:48 UTC by diosmosis

### Description:

**This PR is based off of #19418.**

Changes:
* Convert twig contents for system check page to Vue components.
* Allow ContentIntro directive to be applied conditionally.
* Make Diagnostic result entities JSON serializable.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-08-25 14:51 UTC, sgiehl requested changes
Left some comments. Clicked through installation process and everything else still seems to work as expected

2022-08-25 14:51 UTC, sgiehl commented on plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php
> +
```suggestion
```

2022-08-25 14:51 UTC, sgiehl commented on plugins/Installation/Controller.php
> +        $result = StaticContainer::get('Piwik\Translation\Translator')->getJavascriptTranslations() . "\n";
We actually can't include the javascript translations here. The problem is, that it is possible to change the language in the drop down. Doing that will change the language, but the string contained in javascript will still be in the initially loaded language, as the javascript is cached.

2022-08-25 17:46 UTC, diosmosis commented
@sgiehl applied fixes

2022-08-26 07:58 UTC, sgiehl approved these changes

2022-08-26 07:59 UTC, merged