[js]Update * to originHost
piwik/piwik pull request #19471
Opened 2022-07-06 03:13 UTC by peterhashair

### Description:
Fixes: #19358 
update * to originHost

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-07-06 03:13 UTC, peterhashair commented
build js

2022-07-10 23:40 UTC, peterhashair commented
build js

2022-07-12 23:12 UTC, peterhashair commented
build js

2022-07-14 08:21 UTC, sgiehl requested changes

2022-07-14 08:21 UTC, sgiehl commented on js/piwik.js
> +                        iframe.contentWindow.postMessage(jsonMessage, originHost);
Guess you didn't have a deeper look at the code. It's correct that `e.origin` contains the protocol, but `originHost` is set to `getHostName(e.origin)`, which removes everything, but the hostname.

2022-07-15 01:41 UTC, peterhashair commented
build js

2022-07-15 08:44 UTC, sgiehl commented on js/piwik.js
> +        se);
Guess you added this line break by accident:

```suggestion
        }, false);
```

2022-07-17 23:24 UTC, peterhashair commented
build js

2022-07-18 08:31 UTC, sgiehl commented
The code changes are looking ok.
@peterhashair what exactly did you do to test the changes locally? I did not yet have a look for what exactly the changed code is used, would be helpful if you could provide some insights, so I don't need to spent too much time to find some code that allows testing it.

2022-08-09 21:20 UTC, justinvelluppillai commented
ping @peterhashair this is waiting for your reply to @sgiehl to help him review this effectively.

2022-08-10 01:01 UTC, peterhashair commented
@sgiehl @justinvelluppillai ops, sorry, I think there is js test for it, which is that one. https://github.com/matomo-org/matomo/blob/a8dec66081fa5cd671a668ef248c36e9d3285ffc/tests/javascript/index.php#L5219-5244 

But to tests locally. I add this to my 
```javascript
     addEventListener('load', (event) => {
                const targetFrame = window.top.frames[0];
                const targetOrigin = 'https://yourtrackingsite';
                targetFrame.postMessage('{"d":"hello there","maq_initial_value":true}', targetOrigin);
            });

```

2022-08-12 11:43 UTC, sgiehl commented
@peterhashair the PR contains two added files, that shouldn't exist.

2022-08-14 22:39 UTC, peterhashair commented
@sgiehl ops, that was accidentally added, removed.

2022-08-16 09:30 UTC, sgiehl approved these changes

2022-08-16 09:30 UTC, merged