[Vue] remove angularjs libraries from matomo
piwik/piwik pull request #19502
Opened 2022-07-09 21:05 UTC by diosmosis

### Description:

**This PR is based off of #19496.**

Changes:
* Remove angularjs libs from git and from inclusion in CoreHome.php/other controllers.
* Some code changes to get everything to build w/o angularjs.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-10-03 21:17 UTC, peterhashair commented
@diosmosis this PR is stated for a while, but when I checked this PR, somewhere got else tag error.

2022-10-04 00:23 UTC, diosmosis commented
@peterhashair #19496 should be reviewed and merged first

2022-10-10 14:42 UTC, sgiehl requested changes
I've merged in the latest changes and applied a couple of fixes.
In general this looks good now.
@diosmosis The AngularJS tests are now failing on travis. Could you check if we can simply remove that? Not sure if it still executes some other tests...

2022-10-14 08:03 UTC, sgiehl requested changes
clicked through the UI for a while and wasn't able to find any issues in core or with the submodule plugins. UI tests also seem to pass.
I've searched the code for occurrences of `angular` and there are still a lot matches. Could you check those and remove it where no longer needed, rename variables, ...
Also it seems this file was left over and can be removed: https://github.com/matomo-org/matomo/blob/40afe8b101537e1ca4c28d345b756a22cbaeac21/plugins/CorePluginsAdmin/vue/src/Form/Form.adapter.ts

2022-10-17 04:24 UTC, diosmosis commented
@sgiehl updated. requires a travis-scripts pr to be merged too

2022-10-17 09:42 UTC, sgiehl requested changes
Looks good so far. Let's see if the tests are passing.
The travis PR might need another change though.
Last thing we need to do is to mention the removal of angularjs in the changelog.

2022-10-17 09:42 UTC, sgiehl commented on core/Common.php
> -    public static function fixLbrace($string)
We should mention in the changelog that this method has been removed.

2022-10-20 17:01 UTC, diosmosis commented
@sgiehl updated

2022-11-07 20:57 UTC, merged