Proof of Concept: allow scoping composer dependencies
piwik/piwik pull request #19712
Opened 2022-09-07 13:45 UTC by diosmosis

Refs #16905

In environments when Matomo runs alongside other PHP software, such as in Matomo for WordPress, hard to debug issues caused
by conflicting dependencies can arise. Given there is no way to know exactly which other versions of dependencies might
end up being used in a user's setup, dealing with them on a version-by-version basis can be undesirable.

This PR provides a proof of concept workflow for optionally prefixing dependencies with a custom namespace making sure the
dependencies we use do not conflict with different versions in other software. It supports prefixing twig only at the moment.

To test it:

- check out the branch
- run `./console development:prefix-dependency twig/twig --composer-path=/path/to/composer --remove-original`
- use matomo

Some notes before explaining:

* This proof of concept does not add the prefixing to the composer workflow. It can be added if desired, though.
* It also allows using no prefixed dependencies, so Matomo can be distributed normally and any side effects of prefixing
  can be limited to Matomo for WordPress, where the benefits of prefixing outweigh any potential issues.
* I attempted to minimize changes to core.

### How prefixing is accomplished

Prefixing is accomplished using the php-scoper project. php-scoper processes a folder, adding a prefix to all namespace/use
statements, and anything else it recognizes. It works pretty well, but doesn't replace more dynamic usages. Those can be
replaced manually, however, by adding code to a scoper.inc.php file.

This PR introduces a command `development:prefix-dependency` that automates the process of running php-scoper. It will
download php-scoper from github if not already present, and run it. Afterwards, it uses composer to generate an autoloader
for the newly prefixed dependencies.

Prefixed dependencies are stored in a `./vendor/prefixed` folder.

### Changes to autoloading

The autoloader generated by `development:prefix-dependency` is not enough to ensure Matomo works with prefixed dependencies. php-scoper will change the dependency itself, but won't change the original composer autoloader. So there is still a chance it will try to handle an unprefixed dependency.

For example, if we prefix twig with `Matomo\Dependencies\`, the original composer autoloader that handles all our other
dependencies will still try to resolve classes like `Twig\...`. So if another piece of software tries to load `Twig\TwigFilter`,
it's possible the original composer autoloader will try to load a file that no longer exists.

So this PR also includes `Piwik\Dependency\PrefixedSkippingAutoloader` which handles cases like this. If it encounters a class that the original composer autoloader resolves to a prefixed dependency, we skip handling it.

There is also another autoloader `\Piwik\Dependency\PrefixIgnoringAutoloader` that is used if no prefixed folder is found.
This autoloader makes sure class aliases are created for any encountered Matomo\Dependencies\... class names. This makes it
possible to reference dependencies in core w/ `Matomo\Dependencies\...` without actually prefixing a dependency.

So Matomo can still be distributed normally, without prefixing dependencies. And environments that can benefit from prefixing them,
can do so. This way any side effects that might occur from prefixing will not affect most users, and we don't need to alter
the composer install workflow to something non-standard, or prefix every dependency (which increases the risk of a lot of things
going wrong at once).

### The workflow for supporting a prefix for a dependency

* Locally, run `development:prefix-dependency` on the dependency.
* Modify core/plugin uses of the dependency.
* Get Matomo to work with the prefixed dependency. It may not work without adding to scoper.inc.php.
* Get tests to pass with the prefixed dependency.
* In the automation workflow for the distribution channel that needs it, prefix the dependency before distributing it.

### Notes

* the code works regardless of whether any composer dependencies are actually prefixed or not
* the code requires either that all dependencies whose references in core are changed are prefixed, or none are. So, if we add support to prefix twig and monolog, it will not be possible to just prefix twig and use it. Not at present anyway, it would be simple to add that if needed.

### Todo

* [ ] get tests to pass with prefixed dependencies (since the prefixing is optional, travis-ci currently doesn't do any prefixing)
* [ ] prefix monolog
* [ ] determine if every dependency should be prefixed or if distribution channels should determine whether dependencies are distributed prefixed or not

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-09-07 13:45 UTC, diosmosis commented
FYI @tsteur. Not sure if there's anyone else I should ping, apologies if I missed someone.

2022-09-08 00:02 UTC, tsteur commented
Nice, I just checked out the branch and ran the command and it renamed things nicely. 

Ideally, when running composer in the future then it would indeed need to run php-scoper directly as part of the composer command.

> It also allows using no prefixed dependencies, so Matomo can be distributed normally and any side effects of prefixing
can be limited to Matomo for WordPress, where the benefits of prefixing outweigh any potential issues.

Not fully understanding what is meant by this one @diosmosis ? 

Would that mean that if someone uses Matomo for WordPress, and they install another Matomo plugin from the Marketplace in their WordPress, and this marketplace doesn't use the prefixed version, then it may cause issues that it could use a wrong vendor version from a completely different WordPress plugin? 

I guess if we were to only replace Twig and Monolog this could be fine potentially as it's maybe usually not expected that these libraries would be used too often directly.

I guess from my perspective I just want to keep On-Premise and Matomo for WordPress as similar as possible to not have any unnoticed possible regressions in Matomo for WordPress because they run different code. Looking at the PR I think that doesn't seem to be the case though if I understand it right and would only apply to plugins.

2022-09-08 01:10 UTC, diosmosis commented
@tsteur 

> Would that mean that if someone uses Matomo for WordPress, and they install another Matomo plugin from the Marketplace in their WordPress, and this marketplace doesn't use the prefixed version, then it may cause issues that it could use a wrong vendor version from a completely different WordPress plugin?

Yes, that could be an issue. If scoping in the composer workflow, then I guess the plugin developer would be forced to use the prefixed namespace otherwise it wouldn't work for a normal Matomo, so this wouldn't happen.

> I guess from my perspective I just want to keep On-Premise and Matomo for WordPress as similar as possible to not have any unnoticed possible regressions in Matomo for WordPress because they run different code. Looking at the PR I think that doesn't seem to be the case though if I understand it right and would only apply to plugins.

I understand. For a proof of concept I wanted to provide a solution the was as minimal as possible and show that if it turns out to be more complicated to prefix a dependency correctly and predictably, there was an easy way to go back. I also wanted to show its possible to externalize the mechanism and not have it in core if desired. All of this mostly because there was a lot of manual replacing required for twig, though it's probably an exception given it defines so many functions and generates php code that uses them.

Regardless, I can make it part of the composer workflow if desired, should I move forward with that? (I don't have a big opinion here, I think it's workable either way.)

2022-09-08 09:24 UTC, diosmosis commented
@tsteur I'm going to assume adding to the compost workflow is required. Can you tell me what release this is intended to be a part of or point me to someone who can?

2022-09-08 12:20 UTC, sgiehl commented
We shouldn't do that before Matomo 5. As plugin developers should adjust their code, that imho shouldn't be done in a minor release. Also using the scoped classes in plugins would make those incompatible with older Matomo releases...

2022-09-12 08:34 UTC, diosmosis commented
Clarified on slack this should be targeting 5.x-dev.

2022-09-13 00:07 UTC, tsteur commented
Sorry about the late reply

> Regardless, I can make it part of the composer workflow if desired, should I move forward with that? (I don't have a big opinion here, I think it's workable either way.)

Yes, that be great

2022-10-11 14:47 UTC, sgiehl requested changes
Had a rough first look through the changes and left some comments.
@diosmosis Do we need to increase the PHP requirement to PHP 7.4? Looks like php scoper requires at least 7.4
Also I was wondering if we should prefix all usage of vendor libs. We could let the autoloader remove the prefix if it can't be found prefixed. That would allow us to easily prefix other libs later if they cause trouble, without having another breaking change 🤔

2022-10-11 14:47 UTC, sgiehl commented on core/ExceptionHandler.php
> +                    try {
What are those additional try/catch good for? Doesn't the try/catch around the switch catch enough?

2022-10-11 14:47 UTC, sgiehl commented on core/FrontController.php
> +            echo get_class($e);exit;
Guess this is left over debugging code

2022-10-11 14:47 UTC, sgiehl commented on core/Validators/Login.php
> +namespace Piwik\Validators;
That file seems unrelated. Is it left over from a merge, or did you introduce it on purpose?

2022-10-11 17:35 UTC, diosmosis commented on core/ExceptionHandler.php
> +                    try {
This is related to prefixing monolog. `StaticContainer::get(LoggerInterface::class)` can fail if the prefixed files do not exist. In this case, a new exception is thrown hiding the original, which makes debugging harder.

2022-10-11 17:35 UTC, diosmosis commented on core/FrontController.php
> +            echo get_class($e);exit;
:+1:

2022-10-11 17:36 UTC, diosmosis commented on core/Validators/Login.php
> +namespace Piwik\Validators;
Yes it shouldn't be here. I'm not sure how it got here actually. I'll remove it.

2022-10-11 18:52 UTC, diosmosis commented
@sgiehl 

> Do we need to increase the PHP requirement to PHP 7.4? Looks like php scoper requires at least 7.4

Just for development/git installs.

> Also I was wondering if we should prefix all usage of vendor libs. We could let the autoloader remove the prefix if it can't be found prefixed. That would allow us to easily prefix other libs later if they cause trouble, without having another breaking change thinking

Only issue I can think of regarding this is that it would break PHPStorm's ability to explore the code. Otherwise it seems doable (assuming it will be ok to prefix libraries in minor releases). @tsteur can you comment on this?

2022-10-11 19:01 UTC, tsteur commented
>> Also I was wondering if we should prefix all usage of vendor libs. We could let the autoloader remove the prefix if it can't be found prefixed. That would allow us to easily prefix other libs later if they cause trouble, without having another breaking change thinking

> Only issue I can think of regarding this is that it would break PHPStorm's ability to explore the code. Otherwise it seems doable (assuming it will be ok to prefix libraries in minor releases). @tsteur can you comment on this?

I don't have any thoughts on this. What be the benefits and value of autoloading it for all libs, and what would be the risks and possible problems in the future? @sgiehl 

> We could let the autoloader remove the prefix if it can't be found prefixed. 

Would that mean it could still cause incompatible plugins on WordPress? Like other plugins in WordPress wouldn't use the prefix so checking if that would then trigger the autoloading of our libs with a different version instead of their lib?

2022-10-11 19:07 UTC, diosmosis commented
@tsteur 
> Would that mean it could still cause incompatible plugins on WordPress? Like other plugins in WordPress wouldn't use the prefix so checking if that would then trigger the autoloading of our libs with a different version instead of their lib?

I think in this case it's just doing a class alias of `Matomo\Dependencies\A\B\C` => `A\B\C`, but ONLY if `Matomo\Dependencies\A\B\C` isn't found. wordpress plugins wouldn't use the `Matomo\Dependencies\...` format.

2022-10-11 19:11 UTC, tsteur commented
I see 👍  All good

2022-10-12 08:28 UTC, diosmosis commented
@sgiehl @tsteur I implemented this locally, and it definitely makes PHPStorm useless in this area:

![image](https://user-images.githubusercontent.com/125140/195291128-c18944d2-bcbc-49a1-b2bb-158915066df6.png)

Can I confirm it's worth the trade off? (To reiterate, if we prefix all references to dependencies (not the vendor files themselves), then require in matomo docs that plugins always use `Matomo\Dependencies\` even if the dependency itself isn't prefixed, then we can prefix vendor files in the future w/o a BC break. Though if a plugin didn't use `Matomo\Dependencies\` it would still work even though our docs tell them not to.)

2022-10-16 16:10 UTC, diosmosis commented
@tsteur can you provide guidance on https://github.com/matomo-org/matomo/pull/19712#issuecomment-1275786630?

2022-10-17 02:07 UTC, tsteur commented
As long as we don't use them it should be fine 👍  It could reduce possible upgrade issues if we were to prefix more libraries in the future maybe?

2022-10-17 02:07 UTC, tsteur commented
@sgiehl any thoughts otherwise?

2022-10-17 15:05 UTC, sgiehl commented
That was actually just a random thought that came to my mind. I didn't think about code completion...
Not having class auto completion for dependencies might make the development a bit harder / slower for some cases.
Guess the only way to circumvent that would be to create class aliases for development at least for those classes we are using, so PHPStorm would be able to find them. 
Nevertheless we would need to ensure that we can't accidentally use the original class names, as this could even cause more trouble.

Another random thought:

Not being able to develop and run our tests on PHP 7.2/7.3 anymore will make it hard to detect possible regressions on older PHP versions early. So I would suggest not do this for core, unless we increase the requirements. Renaming the dependencies in the build process only and maybe some tests, would change that maybe...

Overall I'm still not convinced that renaming composer package namespaces will solve more issues for wordpress users than we might end up having issues for on premise users caused by that in the end.

2022-10-17 23:44 UTC, diosmosis commented
> Not having class auto completion for dependencies might make the development a bit harder / slower for some cases.
Guess the only way to circumvent that would be to create class aliases for development at least for those classes we are using, so PHPStorm would be able to find them

I'll see if I can find a solution here.

> Not being able to develop and run our tests on PHP 7.2/7.3 anymore will make it hard to detect possible regressions on older PHP versions early. So I would suggest not do this for core, unless we increase the requirements. Renaming the dependencies in the build process only and maybe some tests, would change that maybe...

We're currently using a fork of php-scoper. It's possible we might be able to just downgrade the minimum required version there.

> Overall I'm still not convinced that renaming composer package namespaces will solve more issues for wordpress users than we might end up having issues for on premise users caused by that in the end.

I suspect the value here is in lowering churn and increasing adoption, not (entirely) in reducing bug reports.

2022-10-18 04:10 UTC, diosmosis commented
tests running on 7.2 again, haven't figured out the other item yet

2022-10-18 04:30 UTC, tsteur commented
> I suspect the value here is in lowering churn and increasing adoption, not (entirely) in reducing bug reports.

Indeed . Ideally it also reduces additionally the bug reports. If we're wanting to get few million WordPress installs for example then it will be only possible if we're compatible with most plugins. Currently, we're for example not compatible with WP-Rocket meaning a few million possible installs are already lost as an opportunity. And that's only one incompatibility with one plugin. There may be many more. The more we reduce these, the more installs we can get.

> Not having class auto completion for dependencies might make the development a bit harder / slower for some cases.
Guess the only way to circumvent that would be to create class aliases for development at least for those classes we are using, so PHPStorm would be able to find them

I assumed we have auto completion for the renamed classes, but not for classes that aren't prefixed anyway. In that case we would still use the regular class name. Having the class names work for other namespaces too may be helpful few years into the future if we decide to prefix more libraries and then it can reduce issues when someone upgrades maybe. We could also remove it though if we don't find value in it and only have the prefixed classnames that we are actually going to use.

> Overall I'm still not convinced that renaming composer package namespaces will solve more issues for wordpress users than we might end up having issues for on premise users caused by that in the end.

Not sure if I missed it. It's great you're bringing this up. We definitely don't want to make other things too worse but make a balanced decision. Can you outline the possible issues/risks again and when they might occur? So we can make a decision if we are going to merge this or not.

2022-10-18 08:16 UTC, sgiehl commented
> Not sure if I missed it. It's great you're bringing this up. We definitely don't want to make other things too worse but make a balanced decision. Can you outline the possible issues/risks again and when they might occur? So we can make a decision if we are going to merge this or not.

* Prefixing dependencies will always contain the risk, that we might not be able to update the dependency in the future, if a newer version contains code, that can't be processed correctly by php-scoper.
* I'm not able to say if renaming such basic dependencies might cause any issues during an update
* Requiring Matomo in another composer projects might no longer be possible, if the project shares the (renamed) dependencies

Assuming we find a way to fix the auto-completion, when using all vendors prefixed (even if they aren't). Couldn't we only do the prefixing for the wordpress version then?
This would have the benefit, that we could even manually apply adjustments to the vendor libs if needed, as those libs are even commited to git there.
And it would fully remove any risk for on premise users.

2022-10-19 21:31 UTC, tsteur commented
@sgiehl could think about only prefixing them in Matomo for WordPress.

If we were to prefix libraries in WordPress, how would we deal with plugins that access these properties? Maybe if it's only twig and monolog then it would work as maybe most plugins wouldn't use it directly but maybe our plugins would or someone else's. Would this be fixable? 

If we were to prefix PHP-DI then for sure I would expect some issues as most plugins use it for example.

Although it could have side effects if we only prefix it in Matomo for WordPress meaning we would need to maintain a fork of Matomo and run Matomo + all plugin tests each also on forks to guarantee Matomo works nicely on Matomo for WordPress when they are prefixed there?

2022-10-24 02:11 UTC, tsteur commented
Any thoughts @sgiehl ? If we could prefix in the WordPress library generally that be great since we ideally also need to prefix PHP-DI as we get reports about incompatibility more regularly recently.

Generally, to increase adoption and reach our targets we need ideally some solution to vendor conflicts problem.

2022-11-03 17:41 UTC, diosmosis commented
@tsteur @sgiehl fyi, updated to detect if being installed as a composer dependency, and if so, skips prefixing

2022-11-04 00:28 UTC, tsteur commented
@sgiehl assuming installing Matomo via composer, do you still see any issue there?

There's obviously the problem that if php-scoper can't replace it automatically that we need to patch composer.json or php-scoper to make this work. This we would need to do though either way whether we do it only for Matomo for WordPress or also for Matomo.

Any further thoughts, risks, problems or requirements we should consider? Or any other solutions in mind we should consider? 

From my perspective the only other vendor lib we should eventually look at also would be PHP-DI. This could potentially wait though for Matomo 6. Abstracting `DI` to use `\Matomo\DI` or something can already be a first start towards this maybe.

2022-11-04 07:46 UTC, diosmosis commented
> There's obviously the problem that if php-scoper can't replace it automatically that we need to patch composer.json or php-scoper to make this work. This we would need to do though either way whether we do it only for Matomo for WordPress or also for Matomo.

I'm not sure exactly what this means, but I think it's not worth worrying about whether php-scoper won't work with a package. In this case, you would define a patcher in scoper.inc.php, and all those do is take a file's string contents and modify them. Essentially, if you can fork a repo and change the namespace by hand, php-scoper will work as all it does is automate that process. The only 'downside' is that you'd have to have at least some knowledge of the internals of a dependency, and users of php-scoper not being the authors of the dependencies they want to prefix, that knowledge would not be perfect. Which is why I did the GoogleAnalyticsImporter proof of concept.

2022-11-04 14:57 UTC, TheRealMisterFix commented
Not sure if this is related, but I'm assuming so... I have WP-Matomo installed on a wordpress site, and had it configured as "Self-Hosted (PHP API)", worked fine, connected to our local Matomo instance.

I installed the WP-Rocket plugin, and the site stopped working, with the following error:
```
[04-Nov-2022 14:31:39 UTC] PHP Fatal error:  Declaration of Piwik\Plugins\Monolog\Handler\FileHandler::write(array $record) must be compatible with Monolog\Handler\StreamHandler::write(array $record): void in /var/www/analytics.SITENAME.com/html/plugins/Monolog/Handler/FileHandler.php on line 22
```

I removed the WP-Rocket plugin manually, and switched WP-Matomo to "Self-Hosted (HTTP API), default", reinstalled the WP-Rocket plugin, and it worked fine.

2022-11-17 00:04 UTC, diosmosis commented
@tsteur @sgiehl prefixed php-di as well now. Also added a UI test for a composer installed matomo (similar to LatestStableInstall + the OneClickUpdate test), and fixed a couple issues to get it to work.

Regarding updating, updating from 4.X will work for some versions as long as it has the one click updater code that initiates CliMulti right after updating the downloaded files (there's a hack in CliMulti's constructor that gets this to work). For all other versions however, the one click update will probably fail. In these cases, the update path would be manual install via core:update, or updating to the latest 4.x release, then updating to 5.0. Can the latter be something that's forced via release channels?

2022-11-17 23:17 UTC, tsteur commented
> however, the one click update will probably fail. In these cases, the update path would be manual install via core:update, or updating to the latest 4.x release, then updating to 5.0. Can the latter be something that's forced via release channels?

That's something that we should be able to enforce. If they are eg currently on a 2.X release, then we could force them to update first to a 4.X release. I've never even thought about this but that may be in the future even a great strategy that allows us to make more changes there when people are like 2 versions behind. 
fyi 67% are already on Matomo 4. 92% are on Matomo 3 or newer.
In 3.13 we added added this https://github.com/matomo-org/matomo/pull/15770 with the redirect so I'm thinking anyone on that version (without testing, just a guess) would be maybe fine and not run into any problems which is 78%. Others we could force to update to Matomo 4.x first.

@sgiehl can you review this PR and test it?

2022-11-24 07:22 UTC, sgiehl commented
@tsteur I've added the review to my todo list. But it might take some time till I'm able to do it. I've got a lot other tasks to do atm.

2022-12-01 16:05 UTC, sgiehl commented
@diosmosis how much effort would it be to get php scoper supporting PHP 7.2?
Currently it's not possible to checkout Matomo and run a composer install on PHP 7.2.
As we still officially support this version, I think this might be a mandatory requirement. Otherwise even developing with PHP 7.2 would no longer be possible.
@tsteur what are your thoughts on that?

2022-12-01 18:47 UTC, diosmosis commented
@sgiehl 

> how much effort would it be to get php scoper supporting PHP 7.2?

Too much. It would be a major fork, especially considering their main branch has already moved on from php 7 altogether.

You can still develop on php 7.2, you just have to run php-scoper w/ php 7.4. It's not easy but it's do-able. travis-ci does this.

2022-12-01 18:53 UTC, sgiehl commented
But this won't allow to install matomo from a git checkout on PHP 7.2 anymore. 
If that isn't possible anymore we might need to discuss with @tsteur how to proceed with this.

2022-12-01 19:03 UTC, diosmosis commented
> But this won't allow to install matomo from a git checkout on PHP 7.2 anymore.

AFAIK this isn't a supported workflow for production installs.

2022-12-02 03:09 UTC, tsteur commented
We could always deprecate this specific one for PHP 7.2 and PHP 7.3 if that helps?

Or is there a chance to run PHP-scoper only for PHP 7.4 and newer similar to as if it was installed as a composer package?

2022-12-02 05:37 UTC, diosmosis commented
@tsteur 

> Or is there a chance to run PHP-scoper only for PHP 7.4 and newer similar to as if it was installed as a composer package?

this is doable I think. Is this the preferred solution?

2022-12-02 05:43 UTC, tsteur commented
any thoughts @sgiehl ?

2022-12-02 17:01 UTC, sgiehl commented
Doing the renaming depending on the PHP version doesn't sound like a good solution.
If we officially support using Matomo prefixed and unprefixed, we are again back to the problem, that we would actually need to run all our tests with both solutions. Same applies for all plugins, as we otherwise can't ensure that everything runs smoothly.
If we gonna do that, we can also let Matomo by default not rename the dependencies and only do that for wordpress.

The other solution we could go with is imho drop support for PHP <7.4 (at least for git checkout) and also drop support for using Matomo as a composer package. Meaning that we always prefix everything. Everything else might imho be too much effort or too risky.

2022-12-06 01:50 UTC, tsteur commented
We can remove the support of installing Matomo via Git for PHP 7.2 and PHP 7.3. We only need to make sure to mention this clearly in the changelog and also we can update https://matomo.org/faq/how-to-install/faq_18271/ . If people do try to install it via Git, ideally they get a good error message mentioning the problem and how they can fix it (by upgrading PHP) if possible. If it's not possible then please let me know and I'll create an FAQ with the error message people would get in such a case so that people can at least easily find the solution to the problem.

Regarding installing Matomo via composer: When someone is trying to install Matomo via composer is it only a problem if they also use one of our dependencies that we prefix? Or is it generally a problem and not working?

2022-12-06 10:39 UTC, sgiehl commented
For composer it should only be an issue if the same packages would be used. But our composer.json would actually be "broken" for PHP <7.4 with the changes on this branch. On the one side we define to require PHP > 7.2, but then try to execute a command on install that requires a library that needs PHP 7.4. So that would fail on PHP <7.4.
But changing the requirement to PHP 7.4 in composer.json also isn't possible, as Matomo should still run with PHP 7.2 and otherwise other dependencies might get updated and require PHP 7.4.

Installing via git on PHP <7.4 would result in a PHP Scoper error message when running a composer install.

It will also no longer be possible to easily develop with PHP 7.2, as you would also require PHP 7.4, which is kind of useless.

In general we could maybe announce that Matomo 5 will require PHP 7.4, but provides a limited support for PHP 7.2 & PHP 7.3.

2022-12-07 02:32 UTC, tsteur commented
Is there a chance we can hook into one of the events and check for the PHP version and accordingly adjust the error message for certain PHP installs? https://getcomposer.org/doc/articles/scripts.md#command-events

Generally, we still want to fully support PHP 7.2+ for people who install it via our build.zip. Limiting support could otherwise break it for 19% of our users. Or I'm not sure what would change if we "limit support" because to support it we'd still need to effectively run the tests on Travis for 7.2 and we'd need to be able to test it locally if needed (eg by running composer with PHP 7.4 and then switching to PHP 7.2).

People installing it via git/composer and using PHP 7.2/7.3 should be a very small minority (<= 1%) and it be acceptable to break it/ removing support for it. We only need to make the experience as nice as we can and have 1 or 2 FAQs for it and we can mention that for these people we effectively remove the support 👍 .

We can also break it for installs where they embed Matomo in a project via composer and they have one of the same dependencies that we are prefixing. That should be a very small number where this happens.

A completely different way could be to push dependencies into vendor directory but I'm assuming that's not something we want :-)

2022-12-07 10:02 UTC, sgiehl commented
With limited support I didn't mean to change anything in the code. We should still support 7.2 and run tests on it.
But we could maybe list PHP 7.4 as requirement (or at least as recommendation) for Matomo 5 e.g. here: https://matomo.org/faq/on-premise/matomo-requirements/
And maybe add a note, that Matomo 5 is still working and tested on PHP 7.2 & PHP 7.3 (when installed with the package), but that we might drop support for it in the near future.

2022-12-08 02:03 UTC, tsteur commented
👍  we could add a sentence that for installing via git/composer certain special requirements apply and can also mention it on the dedicated pages for installing via git etc 💯 

Could also generally add a sentence that we don't recommend using PHP versions that no longer receive security updates 👍

2023-03-22 18:16 UTC, sgiehl commented
Hey @diosmosis. I've tried merging in the latest changes from `5.x-dev`. While the conflicts were solvable, I think there is now a problem with the prefixing command. As you can see in the tests it fatals after it is actually already finished. Seems like the new version of smyfony console that is now used, tries to trigger some logging that ends up in a missing class.
Could you maybe have a look at that? I'm not sure how to solve it. My assumption would be that it tries to load a class with an old name, after the files were already updated.

2023-03-23 11:11 UTC, diosmosis commented
@sgiehl (cc @tsteur) the update to symfony/console now has a shared dependency w/ the monolog bridge package, so now it has an unprefixed reference to a prefixed file. I applied the easiest fix which was to prefix symfony/console as well. The more complicated fix would be to run php-scoper again, after the initial prefixing, on all remaining dependencies to prefix just the references to the now prefixed classes. Assuming it's doable, it would also increase the size of the initial change, so I'm guessing it's less desirable.

2023-03-31 15:30 UTC, sgiehl commented
@diosmosis The test case for installing Matomo as a composer dependency started to fail after updating the branch when it triggers the archiving with this message: `PHP Fatal error: Cannot use ::class with dynamic class name in /home/runner/work/matomo/matomo/matomo/composerInstall/vendor/symfony/var-dumper/Cloner/VarCloner.php on line 129`
To me that message doesn't make much sense as there is not even a `::class` usage on that line. Not sure if it would be worth to fix that or if it would be better to simply drop support for Matomo as composer dependency. Guess we need to decide that once we know whether we will go with this solution or not.

Unfortunately also the normal updating UI tests started to fail with a memory limit error. Not sure what exactly is causing that, but that's something we need to investigate. Increasing the memory limit wouldn't be a problem though, but it sounds strange that updating should consume so much memory.

2023-03-31 16:34 UTC, diosmosis commented
@sgiehl I'll take a look.

2023-03-31 17:14 UTC, diosmosis commented
@sgiehl Just a guess, but I think the update test is failing due to: https://github.com/matomo-org/matomo-package/blob/master/Makefile#L97 since there is an autoload.php file in vendor/prefixed/vendor w/ this change.

EDIT: could fix that by adding ` -not -path "*/prefixed/vendor/*"` to the find command.

2023-03-31 17:41 UTC, diosmosis commented
@sgiehl the composer install test fails because var-dumper v6 is used when installing from composer which I guess fails on php 7.4. I tried locking in the version to 5.0 but it didn't work. It's a dev dependency, though, so it might work to just only install production dependencies for that test.

2023-04-03 08:40 UTC, sgiehl commented
@diosmosis Regarding the composer install test:
`symfony/var-dumper` is no longer a dev dependency. It's required by `symfony/error-handler`, which is required by `symfony/http-kernel`. So it's always installed. So maybe it installed the wrong version as the test does it with `no-dev`. I've moved the requirement in composer.json, which seems to fix it.

Regarding the updater test I'm not sure what you mean. The matomo-package repo is no longer used within Matomo tests. It should now use the script used in our github action. https://github.com/matomo-org/matomo/blob/12ebda87d93a7fab54ebda4883be815757028f6f/.github/scripts/build-package.sh
I'll try to investigate why the test is still failing... Maybe it is also related to prefixing some classes during a running process.

2023-04-03 21:25 UTC, sgiehl commented
@diosmosis I've tried to find a fix for the failing updater test, but wasn't able to yet. I have added some additional debug stuff to our github action, so it now includes the output from matomo log and php error log in the end. But they don't include any further details. Running the updater tests locally doesn't work in my current set up. Are you maybe able to have a look at that?

2023-04-04 13:16 UTC, diosmosis commented
@sgieh fyil I started working on this again in the "ignore" pr

2023-04-05 16:07 UTC, diosmosis commented
@sgiehl OneClickUpdate tests are passing. The other failures look unrelated, let me know if otherwise.

2023-09-10 04:16 UTC, closed without merging