Adding plugin name checks with 60 characters limit
piwik/piwik pull request #19795
Opened 2022-09-30 00:23 UTC by peterhashair

### Description:

Fixes: #18727
adding plugin name checks with 60 characters limit

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-10-04 08:25 UTC, sgiehl requested changes
@peterhashair Did you check the other code for required changes? There is at least
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/CoreConsole/Commands/GeneratePlugin.php#L137-L139
which needs to be removed. Not sure if there are other places where similar stuff is checked.

2022-10-04 08:25 UTC, sgiehl commented on tests/PHPUnit/Integration/Plugin/ManagerTest.php
> +   private function generateRandomString($length = 10) {
We already have a method that does mostly the same: `Common::getRandomString()`

2022-10-05 08:20 UTC, peterhashair commented on tests/PHPUnit/Integration/Plugin/ManagerTest.php
> +   private function generateRandomString($length = 10) {
@sgiehl ops, my bad, update it. :)

2022-10-05 23:29 UTC, peterhashair commented
@sgiehl I could find anywhere else that has a 40 char limit, anywhere I need to be aware?

2022-10-06 04:59 UTC, sgiehl requested changes

2022-10-06 04:59 UTC, sgiehl commented on CHANGELOG.md
> +* Limited plugin name to 60 characters.
Might be better to write something more descriptive and helpful:
```suggestion
* Plugin names are now limited to 60 characters. If you used to have a plugin with a longer name, you might need to rename it.
```

2022-10-06 04:59 UTC, sgiehl commented on tests/PHPUnit/Integration/Plugin/ManagerTest.php
> +            array(true, 'PluginNameTest'.$this->generateRandomString()),
Guess this needs to be changed as well, after removing the method...

2022-10-26 23:06 UTC, peterhashair commented
This PR maybe require other docs to update.

2022-10-28 12:56 UTC, sgiehl approved these changes

2022-10-28 12:57 UTC, merged