update status code to 401 when invalid token in API
piwik/piwik pull request #19813
Opened 2022-10-04 22:14 UTC by peterhashair

### Description:

update status code to 401 when invalid token in API 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-10-07 02:05 UTC, peterhashair commented
Maybe the changeLog wording needs an update.

2022-10-17 01:24 UTC, peterhashair commented
Maybe we don't need this change. 

```php
   if ($referrer && $matomoUrl && Url::isValidHost(Url::getHostFromUrl($referrer)) &&
                strpos($referrer, $matomoUrl) === 0
            ) {
                Common::sendResponseCode(440);
```

2022-10-28 13:20 UTC, sgiehl requested changes
Maybe better give this one a new try. It can't / doesn't work the way it's implemented.
* On the login page, the CSS fails to load, as it results in a 401 response
* The 440 response code is actually a special IIS code, not sure if we should use it, as no one might expect it
* Currently any method using one of the `Access::check*` methods might end up in a 401 response, which also affects the UI and not only API
* You should not adjust the response code in Access class, as you can't know if exceptions thrown there, are not caught and ignored.

2022-10-31 22:39 UTC, peterhashair commented
@sgiehl yeah, removed from `access.php`.  I tried another place that only affects API. I don't believe this is a perfect way, any suggestions?

2022-11-02 10:30 UTC, sgiehl commented
Checking the trace for a certain method doesn't seem to be something we should consider doing. Isn't the method throwing a certain exception that can be checked for?

In general I guess my approach would have been to convert `HttpCodeException` to an interface, and let the `NoAccessException` implement it, so we can simply use the http code check that already exists.

2022-11-03 00:47 UTC, peterhashair commented
@sgiehl it seems like the `HttpCodeException` used a couple of places, convert to an interface maybe broken some other code. I saw we have used `HttpCodeException` this way, could we  `NoAccessException` extend  `HttpCodeException` but has 401 in the __construct, like the current PR?

https://github.com/matomo-org/matomo/blob/6b1fca27df7d96c316e60a2c4b45456cb0544809/core/Http/BadRequestException.php#L12-18

2022-11-03 09:22 UTC, sgiehl commented
I described my approach that way on purpose. You can't simply change the `NoAccessException` to extend from `HttpCodeException` instead of `InvalidRequestParameterException`. The problem is, that we are catching `InvalidRequestParameterException` in some places. Currently that indirectly also catches any `NoAccessException`, as it inherits from it. This won't work now anymore.

2022-11-03 09:39 UTC, peterhashair commented
@sgiehl right, that makes sense.

2022-11-10 01:20 UTC, peterhashair commented
ping @sgiehl

2022-11-10 14:59 UTC, sgiehl commented
Guess we need to convert this into another exception that implements the new interface. Guess the `NoAccessException` might work there.

2022-11-15 11:39 UTC, sgiehl requested changes

2022-11-15 11:39 UTC, sgiehl commented on core/Http/BadRequestException.php
> +class BadRequestException extends NoAccessException
That is logically wrong. A Bad request is not an access problem. This one should be a `implements HttpCodeException`

2022-11-15 11:39 UTC, sgiehl commented on core/NoAccessException.php
> +class NoAccessException extends Exception implements HttpCodeException
this one should still extend `InvalidRequestParameterException`

2022-11-15 20:22 UTC, peterhashair commented on core/NoAccessException.php
> +class NoAccessException extends Exception implements HttpCodeException
@sgiehl ah, I thought the whole point is made `NoAccessException ` a type of `HttpCodeException` so it run into the `getResponseException`  return 403. Should I make InvalidRequestParameterException implements HttpCodeException?

2022-11-15 21:28 UTC, peterhashair commented
@sgiehl just checking instead of interface etc. how about just checking if ` if ($e instanceof NoAccessException) {` then return 403 in API request.

2022-11-21 16:49 UTC, sgiehl commented
That works for sure as well. But we are actually not using exceptions in a useful way. Moving the HttpCodeException to an interface, would have been a first step to improve that mess of exception handling. We should try to improve things when we are already working on it. And changing that exception stuff is a matter of half an hour or so. I'm actually not sure where the problem is, wasn't that almost finished?

2022-12-19 10:52 UTC, sgiehl requested changes

2022-12-19 10:52 UTC, sgiehl commented on CHANGELOG.md
> +* When invalid token provided in the API request, the response code changed from 200 to 401.
So this says it changed to `401`, but the code below looks like it returns a `403` 🤔

2023-01-16 00:00 UTC, bx80 commented
@sgiehl Was the update to the changelog the only outstanding issue you had with this PR?

2023-01-16 13:35 UTC, sgiehl commented
I think so. But we might still need to ensure that this change only affects those parts is was meant for.

2023-02-01 22:25 UTC, bx80 commented
@sgiehl I've fixed the integration test which now correctly checks for a 401 if an invalid token is used. All other access tests are passing. Can you give this a (hopefully) final review when you get a chance?

2023-02-02 13:29 UTC, sgiehl requested changes
There are some more changes needed

2023-02-02 13:29 UTC, sgiehl commented on core/Exception/InvalidRequestParameterException.php
> +class InvalidRequestParameterException extends Exception implements HttpCodeException
I don't think this on should implement `HttpCodeException`, as it actually doesn't define a correct response code.
Otherwise this will cause all exceptions that inherit from this one to also be handled as `HttpCodeException`

2023-02-02 13:29 UTC, sgiehl commented on core/NoAccessException.php
>  class NoAccessException extends InvalidRequestParameterException
This one should directly implement `HttpCodeException`

2023-02-02 13:29 UTC, sgiehl commented on core/NoAccessException.php
> +    }
As this Exception is now used like this 
```
$ex = new NoAccessException(Piwik::translate('Login_LoginNotAllowedBecauseUserLoginBlocked'), 403);
```

We need to handle the code correctly:
```suggestion
    public function __construct($message, $code = 401)
    {
        parent::__construct($message, $code);
    }
```

2023-02-02 13:29 UTC, sgiehl commented on core/Http/BadRequestException.php
>      }
We could also improve that one, so it's possible to overwrite the code if needed.
```suggestion
    public function __construct($message, $code = 400)
    {
        parent::__construct($message, $code);
    }
```

2023-02-03 08:06 UTC, sgiehl approved these changes

2023-02-03 08:41 UTC, merged