allow empty excludedReferrers on the global setting
piwik/piwik pull request #19834
Opened 2022-10-09 21:48 UTC by peterhashair

### Description:

Fixes: #19833 

allow empty excludedReferrers on the global setting

Also, I notice when the setting changed successfully, there is no notification popup, should we add one?

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-10-10 08:35 UTC, sgiehl requested changes
Might maybe be worth adding a test case for storing an empty value, to ensure the solution really works.

2022-10-10 08:35 UTC, sgiehl commented on plugins/SitesManager/API.php
> +        }
That solution actually can't work. It means that the option is actually only updated if a value was provided. So storing an empty value is only skipped and the old value remains.

2022-10-10 08:35 UTC, sgiehl commented on plugins/SitesManager/API.php
> -        foreach (explode(',', $excludedUrls) ?: [] as $url) {
I guess the `?: []` check was already meant to catch empty values, but was implemented incorrectly.
Simply using this here, should already fix everything:
```
foreach (!empty($excludedUrls) ? explode(',', $excludedUrls) : [] as $url) {
```

2022-10-10 20:59 UTC, peterhashair commented
@sgiehl that makes more sense, add a couple of tests, it seems like the `isLookLikeUrl` is always working as well. Add `filter_var($url, FILTER_VALIDATE_URL)` checks as well if that's ok.

2022-10-11 07:53 UTC, sgiehl requested changes
@peterhashair `example a` might not be a valid record but we need to take care to be not too restrictive, as this might produce new problems.

2022-10-11 07:53 UTC, sgiehl commented on plugins/SitesManager/API.php
> +                        FILTER_VALIDATE_URL) === false || !UrlHelper::isLookLikeUrl($prefixedUrl)) {
Are you aware that `FILTER_VALIDATE_URL` only allows ascii domains and might fail for internationalized domains?

2022-10-14 11:28 UTC, sgiehl approved these changes
I've fixed the code indent, that was wrong after your changes. Looks good now.

2022-10-14 11:28 UTC, merged