Allow reports to specify a column/metadata other than "label" that uniquely identifies a row
piwik/piwik pull request #20009
Opened 2022-11-14 23:51 UTC by diosmosis

### Description:

Problem: TODO

How this PR works:

TODO

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-12-02 10:24 UTC, diosmosis commented
Moving this out of draft, but at present the only way to test it would be via crash analytics reports, where some reports have non-unique labels.

2023-04-04 02:17 UTC, tsteur commented
That's a nice new addition @diosmosis that will likely come in handy also for other use cases in the future.
Is there a possibility to add some test maybe?
FYI there's now also a merge conflict and a "unused use statement".

@sgiehl did you have otherwise any thoughts there?

2023-04-06 04:35 UTC, diosmosis commented
Was able to add a test for the LabelFilter test. I don't think it's easily doable to add a test for the UI changes, but they will be covered in the crash analytics UI tests.

2023-05-10 04:37 UTC, tsteur commented
Any chance we could get this reviewed soon?

2023-05-10 13:20 UTC, sgiehl requested changes
Left some suggestions for code improvements, otherwise this looks good to me.

2023-05-10 13:20 UTC, sgiehl commented on config/global.php
> +    'DocumentationGenerator.customParameters' => [],
Might be worth adding a comment above what this can actually be used for.

2023-05-10 13:20 UTC, sgiehl commented on core/API/DataTableManipulator/LabelFilter.php
> +            return [$row, $labelColumn];
What's the purpose of returning the labelColumn here? This method is only called once within this class and as the labelColumn is also a class property I guess this could be used instead as well and we don't need to return it here.

2023-05-11 00:18 UTC, diosmosis commented on config/global.php
> +    'DocumentationGenerator.customParameters' => [],
:+1:

2023-05-11 00:18 UTC, diosmosis commented on core/API/DataTableManipulator/LabelFilter.php
> +            return [$row, $labelColumn];
removed

2023-05-11 12:03 UTC, sgiehl approved these changes

2023-05-11 12:04 UTC, merged