Add allow self singed in mail setting
piwik/piwik pull request #20046
Opened 2022-11-24 00:16 UTC by peterhashair

### Description:

add allow self singed in mail setting

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-11-28 13:09 UTC, sgiehl commented
@peterhashair Weren't @mattab's requirements defined in https://github.com/matomo-org/matomo/issues/18563#issuecomment-1312830954 clear enough? Wondering why you implemented only one ini setting instead of the three settings he requested 🤔

2022-11-28 15:29 UTC, Findus23 commented
I would also change the wording of the setting. `allow_self_signed` implies this allows an additional mode of operation and something that has a limited impact of security (it feels like "only one more thing to support").
But what the setting in fact does is completely remove all TLS verification, allowing anyone in-between Matomo and the mail server to intercept, read and modify e-mails without any issues. (and the fact this also makes self signed certs work is just a side-effect)
So the setting should make it clear that this has strong security implications and should only be set if the person exactly understands what it means and that it is fine in their environment (e.g. the mail server is on localhost)

2022-11-28 20:08 UTC, peterhashair commented
@sgiehl ops update it.

2022-11-29 22:20 UTC, justinvelluppillai commented on CHANGELOG.md
> +## Matomo 4.12.5
This would actually be 4.13.0 if this is merged before the next release. Otherwise potentially 4.13.1

2022-12-01 10:53 UTC, sgiehl requested changes
Added some suggestions for text improvements. Otherwise guess this should work as expected.

2022-12-01 10:53 UTC, sgiehl commented on config/global.ini.php
> +ssl_verify_peer = 1 ; set to 0 to ...
```suggestion
ssl_verify_peer = 1 ; set to 0 to disable verifying the authenticity of the peer's certificate (not recommended)
```

2022-12-01 10:53 UTC, sgiehl commented on config/global.ini.php
> +ssl_verify_peer_name = 1 ; set to 0 to ... (not recommended)
```suggestion
ssl_verify_peer_name = 1 ; set to 0 to disable verifying the authenticity of the peer's name (not recommended)
```

2022-12-01 10:53 UTC, sgiehl commented on config/global.ini.php
> +ssl_disallow_self_signed = 1 ; set to 0 to allow email server with self signed cert
```suggestion
ssl_disallow_self_signed = 1 ; set to 0 to allow email server with self signed cert (not recommended)
```

2022-12-01 10:53 UTC, sgiehl commented on CHANGELOG.md
> +
```suggestion
```

2022-12-01 10:53 UTC, sgiehl commented on CHANGELOG.md
> +* Three new config settings `ssl_disallow_self_signed` ,`ssl_verify_peer`, `ssl_verify_peer_name` under [mail] to allow self-signed SMTP request.
```suggestion
## Matomo 4.13.1

### New config.ini.php settings
* Three new config settings `ssl_disallow_self_signed` ,`ssl_verify_peer`, `ssl_verify_peer_name` under [mail] to allow modifying the SSL handling in SMTP request.
```

2022-12-07 10:36 UTC, sgiehl approved these changes
Looks good to me now.

2022-12-07 21:25 UTC, merged

2022-12-08 05:12 UTC, mattab commented
Sorry i forgot to mention, but here I would expect that we surface the existence of these settings to the user when they get the error, say change the message from:

> SMTP Error: Could not connect to SMTP host.

(as found in the original issue)

to something helpful to users to find it directly like:

> SMTP Error: Could not connect to SMTP host. If you use a SMTP server with a self-signed certificate, see this FAQ: LINK_TO_FAQ

and additionally create a new short FAQ to document the settings.

Note: Just seeing i had mentioned it in https://github.com/matomo-org/matomo/issues/18563#issuecomment-1312830954

2022-12-08 07:35 UTC, sgiehl commented
@mattab That might be not that easy to implement. The error message is coming from PHPMailer, which throws a normal `\Exception`. We could look at the error message, but PHPMailer has messages that are translated to the requested language. Also those messages might change with every release of PHPMailer, so if we look for a certain message, that might start failing with each release of PHPMailer in any language.
What we could do is provide some sort of fake language file for PHPMailer, that will be used. That will ensure that we always get the same error messages. But it would mean, that we would need to do the translation manually afterwards, or even provide all of them through our translation system.
Not sure if that's worth the effort. If you think that's important enough to spent the time on it, feel free to reopen the related issue or create a new one for it.

2022-12-09 04:31 UTC, mattab commented
Sounds good - then we just need to Create a FAQ that mentions the console error message + the solution with the new INI setting (so that people searching for the error will find it) eg. "How do I configure Matomo to send emails when a self-served certificate is used, or SSL doesn't work?"