Always warn about unprocessed segments even if no data exists
piwik/piwik pull request #20226
Opened 2023-01-17 22:34 UTC by bx80

### Description:

Fixes #20060 

When displaying a newly created segment that has not yet been archived, a check is performed to see if there are any visits that match the segment criteria and selected period, if there are no matching visits then the normal 'no data' report is displayed and the unprocessed segment message is not shown.

This results in inconsistent behavior as the same unprocessed segment may show as unprocessed or not depending on the period selected.

This PR removes the check so that the unprocessed segment message will always be shown when viewing a new segment that has not yet been processed irrespective of whether data exists or not.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-01-18 10:35 UTC, sgiehl requested changes
The code changes are looking fine in general.
But there might be some edge cases where the notification might now be shown even if it shouldn't.
If there hadn't been any visits at all for the currently viewed range (e.g. yesterday), the archiver might have fully skipped archiving. Which also means there can't be any archives for any segments. So the message might be shown in this case even if the archiver might have had run.

To prevent that we might need to keep the check for existing visits, but remove the segment from the query. Imho it doesn't make sense to show the message if there hadn't been any visits in the period at all.

In addition we need to hide the notification when displaying live reports. With this PRs changes the notification might be shown when viewing the visits log, which doesn't make sense.

2023-01-18 22:57 UTC, bx80 commented
Thanks for the feedback @sgiehl, looks like removing the visits check is going to create a number of edge cases. I;m thinking even if we reinstate the visits check but just for any visits in the period this would mean that we'd still have the same inconsistency if a new segment is created and a period with no visits at all was selected vs a period with visits but not for the segment. Also if there was a period that never had any visits (like a single day on very low traffic sites)  then the unprocessed message would always be shown. It seems that the previous behavior (before this PR) might have been the best logic to show the unprocessed message.

Since the real issue here is user uncertainty caused by a brand new segment showing 'no data' before it could have been archived, could we perhaps take a different approach, revert these changes and instead add a new message to be shown if there is no data for a segment and archiving hasn't been run since the segment was created?

Something like: 

```php
// SegmentEditor
public function onNoData(...) 
{
    ...
    if  ($segment->ts_created > $lastArchivedTime) {
        $view->isNewSegmentWithNoData = true;
    } 
    ...
}

//_unprocessedSegmentMessage.twig
{% if isNewSegmentWithNoData %}
    "This is a recently created segment and has not been fully processed yet, however there are no visits that 
    match this segment for the currently selected time period."
{% else %}
    // Normal unprocessed segment message
{% endif %}
```

This would remove the uncertainty by confirming to the user that there really isn't any data for the new segment and time period. Once archiving has happened then the message would disappear.

Not archived yet + visits exist for segment = Unprocessed message.
Not archived yet + no visits exist for segment = No data message + New segment no data confirmation.
Archived + visits exist for segment = Normal data.
Archived + no visits exist for segment = No data message.

2023-01-19 10:09 UTC, sgiehl commented
@bx80 Checking if the archiving has run might produce edge cases as well. One could e.g. skip archiving segments when archiving runs and have a separate archive run for segments (which might e.g. run less often). In that case archiving might have run, but without archiving segments.

Actually I think that the current implementation is the correct one. If there hadn't been any visits in the current period, it's fine to not show the message, as even if archiving will run, there will be no data shown.

With our current archiving implementation I'm actually not sure if we can solve this properly. If I'm not wrong, the archiver will not create any records in the archive tables if no visits can be found for a certain day or segment. So we actually can never clearly say if archiving did run or not if there were no visits.
We though could change the archiving, so it at least creates a done flag record when archiving can't find visits. That way it would be possible to say, that archiving did run. But that's fully out of scope for this issue, as touching the archiving can easily consume a couple of days to ensure everything still works as expected.

Maybe we need to discuss this with @mattab again.

2023-01-20 01:22 UTC, bx80 commented
> Actually I think that the current implementation is the correct one. 

Agreed, without some sort of done flag when there are no visits then there is no reliable way to know if the archiving was done for a segment but there were no visits or archiving hasn't happened at all for the segment.

I suppose the question is whether it's worth the time and effort right now to make a significant change to the way archiving flags work in order to address this message consistency issue?

2023-01-23 20:40 UTC, mattab commented
Closing as it's not as easy as we thought and therefore not worth the trouble at this time

2023-01-23 20:40 UTC, closed without merging