proof of concept one blob table row at a time method of aggregating w…
piwik/piwik pull request #20332
Opened 2023-02-07 19:26 UTC by diosmosis

…eek, month, year, range data

### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-03-02 04:39 UTC, tsteur reviewed
FYI haven't fully reviewed it yet but did some profiling.

Here's the result for this PR . The peak memory was 163MB

<img width="866" alt="image" src="https://user-images.githubusercontent.com/273120/222332130-f6073968-d926-4aa6-beea-f544edf6ed03.png">
<img width="1886" alt="image" src="https://user-images.githubusercontent.com/273120/222332154-d6977aaa-642a-45e5-8212-31689effaf68.png">

And here the result for the `4.x-dev` branch where it used 347MB peak.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/273120/222332188-ab5f5a89-3684-4c54-8ae5-a4d73982df9b.png">
<img width="1851" alt="image" src="https://user-images.githubusercontent.com/273120/222332247-7cad87b4-2757-49c4-b3db-05fe9041d52f.png">

It also executes slightly faster with this PR 👍 🎉 
This was for a date range of `2022-09-06,2022-11-26`

I can't test it yet over a longer period but I think that would be a similar result.

> The new method of querying archive data is only used for aggregating data. This is to avoid unintended performance regressions when just querying data from the API. Additionally, using a cursor would only be more memory efficient when aggregating datatables together, not when just querying them.

Looking at the test result there, maybe it could also be used in the API? That's where we're currently having problems. Or was the new implementation slower for you?

2023-03-03 00:02 UTC, diosmosis commented
@tsteur 

> Looking at the test result there, maybe it could also be used in the API? That's where we're currently having problems. Or was the new implementation slower for you?

I didn't actually test it, but it shouldn't make a difference, it should only make a difference when aggregating (browser triggered or core:archive triggered). In this case, we fetch datatables for multiple dates and combine them, so the peak memory use can be lowered to one datatable tree. For just querying through the API, though, all the data is necessary to be returned, so it should make no difference if we use a cursor or fetch them all at once. Everything has to be in memory no matter what (unless we modify matomo renderers to stream data out instead of writing all at once, which would be an enormous change). Anyway, the SELECT query is far more complicated now and I don't know what that would do under load so I thought it was better to constrain the effects of this change for now.

2023-03-08 04:25 UTC, tsteur commented
@diosmosis can you maybe send a link where this different behaviour is implemented? Looking at the PR I can't find different behaviour for API vs others. Or maybe I don't fully understand what is meant by API and how we need to fetch all records there anyway.

2023-03-08 05:28 UTC, diosmosis commented
@tsteur https://github.com/matomo-org/matomo/blob/46679d1300bfc8b7f551afb2b860ebee7081ed7f/core/DataAccess/ArchiveSelector.php#L142-L244 (querying for archives to just return them) vs. https://github.com/matomo-org/matomo/blob/46679d1300bfc8b7f551afb2b860ebee7081ed7f/core/DataAccess/ArchiveSelector.php#L452-L519 (querying for a single blob to aggregate them). The difference in the generated SQL is determined by https://github.com/matomo-org/matomo/blob/46679d1300bfc8b7f551afb2b860ebee7081ed7f/core/DataAccess/ArchiveSelector.php#L559-L565

2023-03-14 20:47 UTC, tsteur commented
Hi @diosmosis . I understand now. Debugged the code and seeing now what's happening and understanding the extra queries. Also understanding the many more queries you mean. I was actually hoping there could be only one query but then in the generator itself we only call `$cursor->fetch()` to get the next data result. I don't actually know if that would reduce memory or if in the background PHP would still hold everything in memory. Just thinking that this could improve the speed and reduce the amount of DB queries quite signficantly as these queries can get slow in production (although we improved their speed recently with a different index).

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/273120/225132217-b8356c44-1b88-4a38-bedf-8a3e215cdbc2.png">

2023-03-14 22:16 UTC, diosmosis commented
@tsteur 

> I was actually hoping there could be only one query but then in the generator itself we only call $cursor->fetch() to get the next data result. 

This should be what happens? There should only be one query per archive table. Can you elaborate?

2023-03-14 22:34 UTC, tsteur commented
@diosmosis I'm so sorry. It actually does work like that indeed. It only looked that way as for one of the date ranges it had no data and then it would always start again at the top of the function and issue the query again but this is actually not the case when there are matching rows. I completely missed it. From my perspective this looks all good 💯 

Not sure if @matomo-org/core-reviewers  have any other thoughts otherwise? Ideally, we could even merge this into a 4.14.0 release as it would be great to have this change on the Cloud already earlier as I believe there isn't a breaking change.

2023-03-14 23:35 UTC, diosmosis commented
> It only looked that way as for one of the date ranges it had no data and then it would always start again at the top of the function and issue the query again but this is actually not the case when there are matching rows.

Interesting, I think that probably shouldn't happen, I'll take a look there.

2023-03-15 00:57 UTC, tsteur commented
@diosmosis it doesn't. It's all good. It was just querying it for different record names which be expected. I didn't realise the record names changed while debugging 👍

2023-03-17 14:42 UTC, sgiehl requested changes
Had a look through the code. To me the changes are looking reasonable.
@tsteur I didn't debug the code or checked any memory usage yet, as you already did that. Or shall I invest some additional time to do that as well?

2023-03-17 14:42 UTC, sgiehl commented on tests/PHPUnit/System/expected/test_reportLimiting__Resolution.getConfiguration_month.xml
>  		<nb_visits_converted>0</nb_visits_converted>
Any specific reason why that test result changed? To me it looks incorrect, as there hadn't been any changes to the fixture. If the change is valid, I'm actually wondering if the changes in this PR have fixed something we weren't aware of 🤔

2023-03-17 14:42 UTC, sgiehl commented on core/ArchiveProcessor.php
> +use Piwik\DataAccess\ArchiveSelector;
Unused use statement here:
```suggestion
```

2023-03-18 01:53 UTC, diosmosis commented on tests/PHPUnit/System/expected/test_reportLimiting__Resolution.getConfiguration_month.xml
>  		<nb_visits_converted>0</nb_visits_converted>
The change is random, the record is not sorted before truncation (see https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Resolution/Archiver.php#L47), so the order in which blobs are aggregated determines what rows show up in this test result. Before blobs were queried w/o an ORDER BY, now they are sorted by idsubtable.

2023-03-19 18:44 UTC, diosmosis commented on tests/PHPUnit/System/expected/test_reportLimiting__Resolution.getConfiguration_month.xml
>  		<nb_visits_converted>0</nb_visits_converted>
Actually, thats not entirely correct, apparently I added a default sort column before truncating so this test result wouldnt randomly change. The change is listed in the PR description.

2023-03-20 02:44 UTC, tsteur commented
> @tsteur I didn't debug the code or checked any memory usage yet, as you already did that. Or shall I invest some additional time to do that as well?

I did check memory usage and it definitely improved and went down and also debugged the code etc.

2023-03-20 09:13 UTC, sgiehl commented on tests/PHPUnit/System/expected/test_reportLimiting__Resolution.getConfiguration_month.xml
>  		<nb_visits_converted>0</nb_visits_converted>
Ah ok. That makes sense. So the result is now actually "more correct", as before it truncated records that actually had more visits.

2023-03-20 09:13 UTC, sgiehl approved these changes

2023-03-20 09:32 UTC, merged