Delete log table data in chunks to prevent possible performance issues
piwik/piwik pull request #20424
Opened 2023-03-06 09:05 UTC by tsteur

### Description:

refs https://github.com/matomo-org/matomo/issues/20221

This won't fully solve the issue but it will fix it for the tables that cause the biggest issues.

After this is merged, we could maybe deprioritise #20221 as it potentially can't even be fixed maybe and it'll be less of a problem then.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-03-07 14:16 UTC, sgiehl approved these changes

2023-03-07 14:26 UTC, sgiehl requested changes
Actually it looks like some tests are failing that are related to the changes of this PR. Seems the SQL syntax generated by `deleteAllRows` is invalid for some reason.

2023-03-08 02:35 UTC, tsteur commented
@sgiehl tests are now passing. That MySQL version had an issue with `DELETE FROM log_visit log_visit where logvisit... limit 1`. It didn't like the table alias when there is also a limit defined. 

While debugging I noticed that only the `log_visit` table will actually use this logic. All other tables, even though most of them have an `idsite` table, would still use a join and therefore won't delete the data in chunks. If we merge this PR, then I would update the original issue to clarify that we need to further optimise this.

2023-03-09 13:47 UTC, sgiehl approved these changes
Looks good to me now. @tsteur feel free to merge if that still improves what it was intended to.

2023-03-10 05:06 UTC, merged