fix two issues with handling of processing dependent archives
piwik/piwik pull request #20555
Opened 2023-04-04 01:05 UTC by diosmosis

### Description:

Bugs fixed:

1) setting whether an archiving request is the root one or not as an instance property of Parameters does not work because when querying archive data for child periods, we will create entirely new instances (in CoreAdminHome\API::prepareArchive()). So instead, use a static variable. This properly prevents recursion here.

2) fix edge case where Goals initiates archiving far more than necessary when there are no conversions (so no data in goals reports) but there are visits (so archiving will still be executed). This was always an issue, but is is far more visible now since we aggregate one blob at a time, and thus query archive IDs once per report. So for every Goals report, we'd archive and try to process dependent archives, even though there are no conversions. And since there is no report data, nothing will be inserted, and we'll try to archive again when we move on to the next report.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-04-05 09:14 UTC, sgiehl commented
@diosmosis looks like various tests started to fail. Might be good having those fixed before a review.

2023-04-06 01:31 UTC, diosmosis commented
php tests should be passing, UI test failures seem unrelated

2023-05-08 11:56 UTC, sgiehl requested changes
Left a minor comment. Besides that the code looks fine.

2023-05-08 11:56 UTC, sgiehl commented on core/ArchiveProcessor/Parameters.php
> -        return $this->isRootArchiveRequest;
The class property still exists, but could be removed now.

2023-05-11 12:46 UTC, sgiehl approved these changes

2023-05-11 12:47 UTC, merged