use RecordBuilders in CustomDimensions plugin
piwik/piwik pull request #20720
Opened 2023-05-15 00:46 UTC by diosmosis

### Description:

**This PR is based off of #20705.**

Changes:
* Move archiving code in CustomDimensions to RecordBuilder that aggregates for a single dimension.
* Create CustomDimensions RecordBuilders for each custom dimension via an event.
* Remove now unused DataArray instance.

Note: if you are reviewing this PR you may notice a redundancy in other RecordBuilders, namely the addRowToReport/addRowToSubtableReport methods. After RecordBuilders are implemented I'll be creating a PoC for a simpler log aggregation API that should remove the need for them. So for now I'm not moving them to a single place.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-06-23 12:17 UTC, sgiehl requested changes
Overall looks fine. Left a couple of comments for improvements.

2023-06-23 12:17 UTC, sgiehl commented on core/Metrics.php
> +    public static function makeGoalColumnsRow(int $idGoal, array $goals): array
This one could have a comment what it should/can be used for.

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +                                              array $dimensions, string $where)
```suggestion
                                              array $dimensions, string $where): void
```

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +    protected function aggregateFromActions(DataTable $report, LogAggregator $logAggregator, $valueField)
```suggestion
    protected function aggregateFromActions(DataTable $report, LogAggregator $logAggregator, $valueField): void
```

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +    private function addMetricsToSelect($select, $metricsConfig)
```suggestion
    private function addMetricsToSelect(string $select, array $metricsConfig): string
```

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +        );
```suggestion
        $from = [
            "log_link_visit_action",
            [
                "table"  => "log_visit",
                "joinOn" => "log_visit.idvisit = log_link_visit_action.idvisit"
            ],
            [
                "table"  => "log_action",
                "joinOn" => "log_link_visit_action.idaction_url = log_action.idaction"
            ]
        ];
```

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +            $rankingQuery->addLabelColumn(array($valueField, 'url'));
```suggestion
            $rankingQuery->addLabelColumn([$valueField, 'url']);
```

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +        $dimensions = array($valueField);
```suggestion
        $dimensions = [$valueField];
```

2023-06-23 12:17 UTC, sgiehl commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +        $defaultColumns = DataArray::makeEmptyRow();
Aren't we tryng to get rid of the DataArray stuff? Wondering if there's already another method that could be used instead.

2023-06-23 12:17 UTC, sgiehl commented on core/DataTable/Filter/EnrichRecordWithGoalMetricSums.php
> +    public static function enrichWithConversions(&$values)
```suggestion
    public static function enrichWithConversions(&$values): void
```

2023-06-23 19:46 UTC, diosmosis commented on plugins/CustomDimensions/RecordBuilders/CustomDimension.php
> +        $defaultColumns = DataArray::makeEmptyRow();
Currently there isn't. There might be if the simpler log aggregation poc is accepted. That won't be discussed for a while though. Replaced with just setting the column values to 0 directly.

2023-06-26 08:25 UTC, sgiehl approved these changes

2023-06-26 08:25 UTC, merged