use RecordBuilders in the Referrers plugin
piwik/piwik pull request #20740
Opened 2023-05-17 04:40 UTC by diosmosis

### Description:

Changes:
* Add RecordBuilder for Referrers.
* Add 'transform' property to Record that's only used for numeric records that are counts of blob records. This is to keep the logic in Referrers that does `$counts['recursive'] - $counts['level0']`. It doesn't seem like an ideal solution, and will be rarely used, but I couldn't come up with another.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-07-10 12:19 UTC, sgiehl requested changes
Left some minor comments. Otherwise it seems some related test are failing...

2023-07-10 12:19 UTC, sgiehl commented on plugins/Referrers/RecordBuilders/Referrers.php
> +    protected function aggregateVisitRow($row, array $reports, array &$distinctUrls)
```suggestion
    protected function aggregateVisitRow($row, array $reports, array &$distinctUrls): void
```

2023-07-10 12:19 UTC, sgiehl commented on plugins/Referrers/RecordBuilders/Referrers.php
> +    protected function makeReferrerTypeNonEmpty(&$row)
```suggestion
    protected function makeReferrerTypeNonEmpty(&$row): void
```

2023-07-10 12:19 UTC, sgiehl commented on plugins/Referrers/RecordBuilders/Referrers.php
> +                    return $counts['recursive'] - $counts['level0'];
Might be good to add a comment here, so is easier to understand what exactly this is good for.

2023-07-10 20:49 UTC, diosmosis commented
@sgiehl updated

2023-07-11 09:49 UTC, sgiehl commented
@diosmosis The ReportExporting UI tests are still failing. Seems some value changed from int to string or so. See https://github.com/matomo-org/matomo/actions/runs/5512669036/jobs/10049800824?pr=20740#step:3:1022

2023-07-11 12:55 UTC, diosmosis commented
@sgiehl should be fixed

2023-07-11 13:06 UTC, sgiehl approved these changes
Looks good now 🎉

2023-07-11 13:06 UTC, merged