Single click copy button for code snippets
piwik/piwik pull request #20915
Opened 2023-06-21 00:32 UTC by bx80

### Description:

This is backport of https://github.com/matomo-org/matomo/pull/20876 

It adds a single click copy-to-clipboard button to the following code snippets:
- Tracker code during installation.
- All tracker code snippets on the site 'no data' screen, incl. Image tracking, GTM, MTM, React and Vue tabs.
- Matomo Tag Manager install code function
- User token creation (copy token after creation)
- Privacy manager user opt out code
- Campaign URL builder URLs
- Custom dimensions shell commands 
- The UI demo at `/index.php?module=Morpheus&action=demo`

A new Vue directive `CopyToClipboard` adds the button to any `<pre>` element wrapped in blank div and decorated with `<pre v-copy-to-clipboard>`. For this 4.x PR an angular adapter is included (`matomo-copy-to-clipboard`) and is used in a few places for older templates which have been replaced with Vue components in 5.x

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-06-21 07:52 UTC, sgiehl requested changes

2023-06-21 07:52 UTC, sgiehl commented on plugins/Morpheus/templates/demo.twig
> +            &lt;pre matomo-copy-to-clipboard&gt;...&lt;/pre&gt;
The surround div is actually missing here. Not sure if that also was the case in he 5.x-dev PR. If so we should fix that there as well.
```suggestion
            &lt;div&gt;&lt;pre matomo-copy-to-clipboard&gt;...&lt;/pre&gt;&lt;/div&gt;
```

2023-06-21 07:52 UTC, sgiehl commented on plugins/TagManager
This needs to be reverted, before merging the PR. Targeting a branch for a submodule can break the checkout when the branch in the submodule gets deleted. This should only be commited if it's required for tests to pass.

2023-06-21 22:31 UTC, bx80 commented on plugins/Morpheus/templates/demo.twig
> +            &lt;pre matomo-copy-to-clipboard&gt;...&lt;/pre&gt;
Good spot, I've updated it :+1: 

The 5.x-dev version does have the surround div - it's a little different there as it's been updated for vue and moved to the controller, whereas 4.x-dev is still using the angular adapter and everything is the the twig template.

2023-06-21 22:33 UTC, bx80 commented on plugins/TagManager
Unfortunately it is required for the tests, even though the UI test screenshots are not under the TagManager plugin. Thanks for the reminder to revert the submodule reference back to 4.x-dev once the TagManager PR has been merged, easy to miss :+1:

2023-06-22 08:05 UTC, sgiehl commented on plugins/TagManager
We can't do it that way. If we merge the PR in core having the submodule pointing to the TagManager branch, this would break the checkout of submodules if the TagManager branch gets deleted. We can then for sure simply update it to 4.x-dev again, but that still means that we have a reference in the history that isn't valid anymore. 
The changes in this PR should actually not require a submodule update. If some UI tests in core needs to updated when the TagManager changes, we should either investigate if it makes more sense to move that specific test to the TagManager, or keep the old results and update them together with the submodule once the TagManager PR has been merged.

2023-06-22 09:27 UTC, merged