Make links underlined everywhere
piwik/piwik pull request #20940
Opened 2023-06-27 10:18 UTC by sgiehl

### Description:

fixes #20706 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-07-04 21:08 UTC, sgiehl commented
@bx80 @michalkleiner If you have some time, feel free to already have a look at that one. I hop all links should be underlined by now, but I'm still looking a bit through the changed screenshots to check if I see a link that might still not be underlined. If you spot anything that still needs to be adjusted, let me know.

2023-07-05 15:55 UTC, sgiehl commented on plugins/Goals/Reports/Get.php
> +            if (!empty($idSite) && Piwik::isUserHasWriteAccess($idSite) && $idGoal > GoalManager::IDGOAL_ORDER) {
This fixes a "bug", where the ecommerce goal title was clickable, referring to an invalid page, as the ecommerce goal isn't editable.

2023-07-07 13:38 UTC, sgiehl commented on plugins/Marketplace/stylesheets/marketplace.less
> +                white-space: nowrap;
This is actually a small improvement so that the link content `› more` isn't split onto two lines.

2023-07-10 01:19 UTC, bx80 requested changes
I've looked through every config and dashboard page in the UI and it generally all look really good.

The only things I noticed:

`<a>` buttons without the `btn` class shown an underline on hover, whereas `<a>` buttons with the `btn` class do not. For example Admin > Personal > Security 'Create new Token' vs 'Turn on two-factor authentication'. Changing `.tableActionBar a &:hover` to `text-decorated: none` seemed to resolve this but I'm not sure if this is used elsewhere for non-buttons?
![Screenshot_20230710_130445](https://github.com/matomo-org/matomo/assets/88810029/392edd95-a3d8-4cdb-a53f-86ca498e16e3)

The site selector and period selector buttons don't underline on hover as expected, but the check for update button does, it seems to be the span not the button that has the underline.
![Screenshot_20230710_130535](https://github.com/matomo-org/matomo/assets/88810029/5dd20da5-3b1c-4ac4-8522-063181fabc23)

The Admin > Measurables > MTM panel bottom links have the icons underlined along with the link. This is quite a minor thing, so feel free to ignore :slightly_smiling_face: 
![Screenshot_20230710_130404](https://github.com/matomo-org/matomo/assets/88810029/5b87958a-2c89-42ce-9afc-f23d2c9316ab)

2023-07-10 07:53 UTC, sgiehl commented
@bx80 All of those misplaced underlines where actually already the case before this PR, but I'll try to push some fixes.

2023-07-10 14:08 UTC, sgiehl commented
Everything should be updated now.

2023-07-10 20:53 UTC, michalkleiner commented
I'll have a quick look today as well

2023-07-10 23:50 UTC, bx80 approved these changes
I've checked through page in both admin and dashboard, it's all looking good :+1:

2023-07-11 02:33 UTC, michalkleiner commented
We shouldn't be underlying the space between the icon and the text of the link, it should use margin-right to create the space.

![space underline](https://github.com/matomo-org/matomo/assets/233342/0ab506c0-f31f-43a9-94f4-7d03a9e0e202)
![space underline in MTM buttons](https://github.com/matomo-org/matomo/assets/233342/742de641-1398-417c-81bc-c6c95a8dfbf4)

2023-07-11 02:34 UTC, michalkleiner commented
The cancel button in MTM install code shouldn't be underlined, but that could be that plugin's issue to resolve.

![mtm install code cancel button](https://github.com/matomo-org/matomo/assets/233342/cce02f8e-5bdd-4f0c-baeb-d5c9618eb53a)

2023-07-11 02:39 UTC, michalkleiner commented
Everything else looked ok, I couldn't find anything that would otherwise look out of place.

Though the fact we don't have any hover interaction on most text links and majority of button links is a step back IMO, and I see that possibly as equal or worse accessibility issue than not having all links underlined (while being different, usually blue colour).

For links, the rule of thumb is usually to have two degrees of visual differentiation and one of them should be changing on hover, so if we have a colour and an underline, on hover we can change colour and/or the underline style, but at the moment, with this change, we're doing (mostly) nothing. Some links are black in black text with only an underline (so only one differentiation) and they look like underlined text, not like a link.

2023-07-11 02:41 UTC, michalkleiner requested changes
I'd like to discuss the hover states, I think we might be throwing the baby out with the bath water.

2023-07-11 10:26 UTC, michalkleiner commented
> I'd like to discuss the hover states, I think we might be throwing the baby out with the bath water.

Doesn't have to be a lenghty convo, just basically what we think about it and how we address it. The work here is great and moves things forward, but at the same time, at least from my perspective, makes it slightly worse in a different way.

2023-07-11 11:27 UTC, sgiehl commented
I agree that we should at least consider changing those links that still have a black color. Links should be visible by having another color and either be underlined or have an icon or similar. 
Should we create follow up items for those links that look different at the moment, so we can get this one merged. Having this open for too long will bring up more and more merge conflicts over time...

2023-07-11 11:58 UTC, bx80 commented
It would definitely be good to look at improving the hover colors :+1: We should do that in another ticket though as it might benefit from some design input and this 400 file change can be merged in the meantime :slightly_smiling_face:

2023-07-11 15:28 UTC, michalkleiner commented
As long as we get this done before 5.0.0 stable is out I'm ok with having improving the hover states as a separate ticket.

2023-07-12 14:40 UTC, merged