No-data screen translations for React.js and SPA/PWA
piwik/piwik pull request #20995
Opened 2023-07-10 10:08 UTC by michalkleiner

### Description:

Contains changes to SiteManager and common lang files.

Reference to MTM will be removed before merging this and updated via the standard modules update once the relevant PR https://github.com/matomo-org/tag-manager/pull/652 there is merged.

The translations were reviewed with internal staff apart from Italian which was review through reverse translation using a different service.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-07-10 11:34 UTC, sgiehl requested changes

2023-07-10 11:34 UTC, sgiehl commented on plugins/SitesManager/lang/de.json
> +        "ReactDetectedEmail": "React.js wurde auf Ihrer Website erkannt. Wussten Sie, dass Sie den \"Matomo Tag Manager\" verwenden können, um die Daten der Website zu verfolgen? Erfahren Sie hier me
```suggestion
        "ReactDetectedEmail": "React.js wurde auf Ihrer Website erkannt. Wussten Sie, dass Sie den \"Matomo Tag Manager\" verwenden können, um die Daten der Website aufzuzeichnen? Erfahren Sie hier mehr: %1$s",
```

2023-07-11 13:51 UTC, sgiehl commented
Looks good to me. Before merging we need to merge the changes in TagManager and update the submodule reference here, so it won't break when the branch is removed in TagManager repo.

2023-07-12 13:03 UTC, michalkleiner commented
Have updated the TagManager submodule reference to use the 5.x-dev version there and waiting for the last UI tests to finish, then this is ready for merge.

2023-07-12 13:38 UTC, merged