[DEV-17076] Change translation key for Tour_AddWebsite and also the english translation
piwik/piwik pull request #21146
Opened 2023-08-16 00:11 UTC by caddoo

### Description:

The language was confusing as it implied you hadn't added one website when in fact you had.

Changed to say 'Add another website'

https://github.com/matomo-org/matomo/issues/21134

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-08-16 08:00 UTC, sgiehl requested changes

2023-08-16 08:00 UTC, sgiehl commented on plugins/Tour/lang/bg.json
> +        "AddAnotherWebsite": "Добавете уебсайт",
Please don't change any translation files other than `en.json`. All other files will be automatically updated by weblate, the translation service we are using. Making changes to other translations files is in theory possible as well, but it can always cause merge conflicts, resulting in additional unnecessary work I need to do...
In this case updating the keys everywhere, would actually cause weblate to insert the provided translations into the new key, which would be incorrect, as the English one has different content now.

2023-08-16 08:00 UTC, sgiehl commented on plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges.png
You may need to revert the changes to the screenshots and do them again. All expected UI files in this repo are stored using git lfs. If you haven't set that up yet, you might need to do so. Using git lfs prevents our repo size from exploding. So it would be good to remove any commit that directly adds such files to the repo.

2023-08-16 22:09 UTC, caddoo commented on plugins/Tour/lang/bg.json
> +        "AddAnotherWebsite": "Добавете уебсайт",
Clear, I've updated this now.

2023-08-16 22:09 UTC, caddoo commented on plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges.png
Does this look better?

2023-08-17 06:30 UTC, sgiehl commented on plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges.png
They are still not using git lfs. Let me know if you need help with that.

2023-08-17 21:46 UTC, caddoo commented on plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges.png
Oops, got some help from @bx80 I missed actually installing LFS in the repo, should be good now.

2023-08-18 01:48 UTC, bx80 requested changes
Hi @caddoo, the UI tests look good now :+1: 

Could you check the following system tests as they appear to be failing due to this change? 

```
Tour\tests\System\APITest
Piwik\Tests\System\OneVisitorTwoVisitsTest
Piwik\Tests\System\NoVisitTest
Piwik\Tests\System\ImportLogsTest
Piwik\Tests\System\BackwardsCompatibility1XTest
```

2023-08-18 04:31 UTC, bx80 commented
@caddoo That's fixed the system tests :+1: 

Some UI tests are still failing because of [outdated icons](https://builds-artifacts.matomo.org/matomo-org/matomo/DEV-17076-change-add-a-website-text/5898247533/Tour_widget_initial.png), the expected screenshots are using the old icons but the processed screenshots are using the new icons. I guess the icon update PR was merged since you branched, so a rebase onto the latest 5.x-dev should fix that.

2023-08-18 10:03 UTC, sgiehl commented
Wow. Only one failing unrelated UI test. Guess we should merge it now. It won't get better 😆

2023-08-18 10:06 UTC, merged