Fix inconsistencies across dropdown elements
piwik/piwik pull request #21199
Opened 2023-08-29 03:03 UTC by bx80

### Description:

Move the main menu dropdown icons to the right.

Affects: 
- Site selector
- Period selector
- Segment selector
- Dashboard selector
- Tag Container selector
- Ab test period selector
- Version info header
- Quick access

Fixes #20475

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-08-29 08:39 UTC, sgiehl requested changes
Left one relevant comment for this PR, that would be good to changed. Otherwise it's looking fine so far

2023-08-29 08:39 UTC, sgiehl commented on tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
@Javi-Ormaechea Actually not relevant for the changes around drop-downs, but do you think that it would look better if the icon in the search input would also be placed right? Especially in this mobile view it looks a bit weird that only the one icon is placed left...

2023-08-29 08:39 UTC, sgiehl commented on plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
@bx80 Would you mind improving the spacing of dropdown arrow in the main menu? The group selection drop down for dashboards doesn't look fine (might be the same for goals as well). Already saw that when the icons were replaced, but thought this might get changed with drop downs anyway, so didn't mention it there...

2023-08-30 02:22 UTC, bx80 commented on plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
Good spot :+1:
 I've adding some extra padding.
![image](https://github.com/matomo-org/matomo/assets/88810029/002ccf8b-a824-48f1-8a97-350f7aabf440)

2023-08-30 02:26 UTC, bx80 commented on tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
I've made this change because the mobile search input now looks awful on the left, here it is after the change.
![image](https://github.com/matomo-org/matomo/assets/88810029/94744b2a-ba8a-4b55-8a12-6243d5de099b)

2023-08-30 02:40 UTC, bx80 commented on tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
and before:
![image](https://github.com/matomo-org/matomo/assets/88810029/18c691ba-2427-426f-97e5-075bbc27e40d)

2023-08-30 03:22 UTC, Javi-Ormaechea commented on tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
I agree that it doesn't look great on this specific screen but it should look consistent on desktop too. If we make this change on mobile it should also happen on desktop.

2023-08-30 04:32 UTC, bx80 commented on tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
Sounds good, if we have some sort of standard across both mobile and desktop then it'll make these sort of changes easier :+1:

2023-08-30 14:45 UTC, sgiehl approved these changes
Changes are looking good now. Merged in the latest changes from 5.x-dev and will wait for the tests to finish before merging...

2023-08-30 15:43 UTC, michalkleiner commented
Apologies for my sometimes annoying sense for tiny details. I can't help it but I think the new chevron icon for the dropdown is too thick for where/how it's used. I reckon we should explore the option of either making it slightly smaller or perhaps lighter, and also push it vertically down a pixel or two to be better aligned on the row, both in the dropdowns and the lefthand menu.

2023-08-30 15:46 UTC, michalkleiner commented
Just compare the line thickness and how it sort of stands out for the chevron compared to the other two icons to the left
<img width="333" alt="Screenshot 2023-08-30 at 5 45 19 PM" src="https://github.com/matomo-org/matomo/assets/233342/da5fa0c9-848f-46ce-be3f-7972eaeaaaa2">

2023-08-30 15:54 UTC, sgiehl commented
@michalkleiner I agree that the icon could maybe be placed slightly better. But that was actually already the case before, as the icons were only moved to the other side. Maybe @Javi-Ormaechea should have a look and give his opinion. 
I will merge this one now anyway, as it won't change anything in terms of effort if it would be added here or changed in a new PR.

2023-08-30 15:54 UTC, merged