Improve "What's new" feature visibility
piwik/piwik pull request #21219
Opened 2023-09-05 00:40 UTC by bx80

### Description:

Fixes #20283 

- Adds a badge overlay to the "What's new" top menu notification icon to show the number of new changes.
- Show the "What's new" dialog as a popup automatically when logging in if there are new changes.

![image](https://github.com/matomo-org/matomo/assets/88810029/6b88f95f-7698-490c-bdc2-3f3cd75cb493)

This is currently a draft PR - badges are done, popup still to do

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-09-11 08:08 UTC, sgiehl requested changes
Left a couple of comments. Besides that it might be good to add some UI tests for that badge count display.

2023-09-11 08:08 UTC, sgiehl commented on core/Plugin/Controller.php
> +        // Set early so it can available for setGeneralVariables method calls
```suggestion
        // Set early so it is available for setGeneralVariables method calls
```

2023-09-11 08:08 UTC, sgiehl commented on core/Plugin/Controller.php
> +        $view->whatisnewTooltip = addslashes(Piwik::translate('CoreAdminHome_WhatIsNewTooltip'));
would be better to do the escaping the in view where needed. Actually the full translation could be done within the view, unless there is a reason to push it from PHP to the view.

2023-09-11 08:08 UTC, sgiehl commented on plugins/CorePluginsAdmin/CorePluginsAdmin.php
> +        $changesModelClass = StaticContainer::get(\Piwik\Changes\Model::class);
The StaticContainer should normally directly return a class instance, so there should be no need to instantiate it below. Parameters for the constructor should be provided automatically if they can be resolved. If not you might need to provide that in config.php

There are a couple of other places, where this is used similar and should be changed.

2023-09-12 01:17 UTC, bx80 commented on core/Plugin/Controller.php
> +        // Set early so it can available for setGeneralVariables method calls
Fixed, need to work on my English as a first language :+1:

2023-09-12 01:18 UTC, bx80 commented on core/Plugin/Controller.php
> +        $view->whatisnewTooltip = addslashes(Piwik::translate('CoreAdminHome_WhatIsNewTooltip'));
I've moved the translation of the tooltip to the view, I couldn't find a suitable twig filter to add slashes for the apostrophe so I did this in the JS to keep it all in the template.

2023-09-12 01:21 UTC, bx80 commented on plugins/CorePluginsAdmin/CorePluginsAdmin.php
> +        $changesModelClass = StaticContainer::get(\Piwik\Changes\Model::class);
Good point, I've now fixed this. The constructors to the model class were unnecessary so I've removed them.

2023-09-18 06:25 UTC, closed without merging