Updated invite user UI, removed readonly email field, #PG-3048
piwik/piwik pull request #21284
Opened 2023-09-20 07:57 UTC by AltamashShaikh

### Description:

Updated invite user UI, removed readonly email field
Fixes: #PG-3048.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-09-20 08:32 UTC, sgiehl commented
@AltamashShaikh As far as I know this should only be changed for the cloud onboarding. Thus this change here won't be needed.
And a general note: Setting the email/login field as hidden, might break password managers from picking it up, which can be avoided by hiding the input using css.

2023-09-20 09:36 UTC, AltamashShaikh commented
> @AltamashShaikh As far as I know this should only be changed for the cloud onboarding. Thus this change here won't be needed. And a general note: Setting the email/login field as hidden, might break password managers from picking it up, which can be avoided by hiding the input using css.

Taking forward to what we discussed on Slack
1. Make the label changes in core
2. Hide the email field via css in Cloud plugin

2023-09-21 02:36 UTC, AltamashShaikh commented on plugins/UsersManager/API.php
> +                'module' => Piwik::getLoginPluginName(),
This fixes the issue of wrong plugin being used while generating the copy invite user link

2023-09-21 08:06 UTC, sgiehl requested changes

2023-09-21 08:06 UTC, sgiehl commented on plugins/Login/templates/invitation.twig
> +                    <div class="col l10 s12 input-field invite-user-pwd-div">
those should be ids, right?

2023-09-21 08:07 UTC, sgiehl commented on plugins/Login/templates/invitation.twig
> +                    <div class="col l10 s12 input-field invite-user-pwd-div">
Ah. doesn't make sense. It's there twice...

2023-09-21 08:08 UTC, sgiehl approved these changes

2023-09-21 08:49 UTC, merged