Cast column label to string to stop magic casting issues.
piwik/piwik pull request #21366
Opened 2023-10-05 02:25 UTC by caddoo

### Description:

Labels can be anything, and PHP likes trying to cast itself. ( see https://3v4l.org/X6v6E#v8.1.24 )

This causes errors, and we can safely assume the key for the array should always be a string.

I didn't modify `Row.getColumn`'s response type or cast within there as there is a lot of code that depends on that and the change would be riskier.

Fixes: https://github.com/matomo-org/matomo/issues/21357

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-10-05 04:58 UTC, michalkleiner approved these changes, later dismissed
Looks ok to me on its own, the failing tests seem to be unrelated, so I'd say good to go for 4.x

2023-10-05 07:25 UTC, sgiehl requested changes
This doesn't look complete to me. You have only changed the place where `rowsIndexByLabel` is filled, but all places where that array is used to find entries are untouched. This will have the effect, that keys won't be found anymore. Methods like `getRowIdFromLabel` imho also needs to be adjusted.

2023-10-09 09:53 UTC, sgiehl approved these changes
Looks good now. Before merging this one, we should ensure that there already is a PR for 5.x-dev, so re don't forget to apply the changes there as well.

2023-10-11 01:16 UTC, caddoo commented
> Looks good now. Before merging this one, we should ensure that there already is a PR for 5.x-dev, so re don't forget to apply the changes there as well.

Good point, here it is https://github.com/matomo-org/matomo/pull/21393

2023-10-11 14:03 UTC, merged