Require password confirmation for giving anonymous user view access
piwik/piwik pull request #21871
Opened 2024-02-02 16:44 UTC by sgiehl

### Description:

With this PR giving view access to the anonymous user through the UI will require a password confirmation.
This will be added to lower the risk that someone makes his Matomo data public accessible by accident.

In addition this PR contains some small usability improvements.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-02-02 16:49 UTC, sgiehl commented on plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
> +                    $event.abort();"
Directly aborting the event causes the select box to directly switch back to the original value. This way the value will remain correct if the confirmation is rejected. In case it is accepted the list will be refreshed anyway and the new value is displayed.

2024-02-02 16:49 UTC, sgiehl commented on plugins/UsersManager/vue/src/UsersManager/UsersManager.vue
> +      );
Moved this to `finally`, as it can e.g. happen that for some reason one of the bulk requests returns an error while others might succeed. So we should reload the list in any case, to ensure we always display the correct values.

2024-02-06 08:54 UTC, michalkleiner requested changes
Local tested and it works fine when using the permissions dropdown directly for the anonymous user. If I have 2 or more users with no access, want to give them view access using the bulk actions and one of the users is the anonymous user, I immediately get the "Please enter your password to confirm this change." red notification without the modal popping up. View access gets added to all selected users apart from the anonymous user. Saying that it is a safer way how to fail compared to just granting the view access, but it breaks the expected behaviour of the bulk actions.

2024-02-06 08:55 UTC, michalkleiner commented on plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
> +      @aborted="userToChange = null; roleToChangeTo = null;"
If this is an already existing approach we use elsewhere to do multiple assignments/expressions in a callback then it's fine, otherwise I would probably marginally prefer to have them in a function and call the function here.

2024-02-06 08:56 UTC, michalkleiner commented on plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
> +            @click.prevent="changeUserRole();"
Was this just added when testing something?

2024-02-06 10:17 UTC, sgiehl commented on plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
> +      @aborted="userToChange = null; roleToChangeTo = null;"
It's used in various places already. But in general I get your point

2024-02-06 12:01 UTC, sgiehl commented
@michalkleiner I've changed the implementation slightly now. The password prompt will now always be shown if the request contains view access for anonymous user. So this also covers bulk requests now. Trying to give admin access to the anonymous user in a bulk request, won't ask for a password, as it won't succeed anyway.
Need to check if some ui tests need to be updated now, otherwise this should be good for another review.

2024-02-06 12:14 UTC, michalkleiner commented
Yep, I now get the password prompt for the bulk action as well if one of the users selected is the anonymous user.

With this update, I would expect that if the password provided is incorrect, then none of the users selected would get updated using the bulk action, however the standard (other than anon) users do still get the change. It's probably quite an edge case so it's ok with me to keep it as is unless it's easy to adjust.

2024-02-06 12:19 UTC, sgiehl commented
Unfortunately it's not easy to adjust. All requests are sent in a bulk request. So one request for each user. The password might be sent with all requests, but the API method only checks the password for anonymous. We could only change that, so the password is always validated if provided, even if not needed. We could maybe tweak the message in the password prompt, so it's clear it's only needed for the anonymous access maybe.

2024-02-06 12:42 UTC, michalkleiner commented
I think it's such an edge case it's probably ok to leave as is. We can think of adding a note to the password modal but it might be even more confusing. Hard to say. Happy to get opinions from others.
For me this achieves the goal of adding the password verification for the anonymous user access being turned on.

2024-02-06 12:42 UTC, michalkleiner approved these changes

2024-02-06 12:43 UTC, michalkleiner commented
Might be worth checking how this behaves with password-less auth plugins like the LDAP one.

2024-02-06 12:59 UTC, sgiehl commented
@michalkleiner As it reuses the existing methods, for password less plugins it should be fine to simply keep the password prompt empty. The API also shouldn't require a password in that case.

2024-02-12 12:23 UTC, merged