Use unique merged assets filenames when requested from UI tests via Proxy
piwik/piwik pull request #22268
Opened 2024-05-31 04:02 UTC by michalkleiner

### Description:

First go at fixing UI test failures when merged assets are not available when requested via the Proxy mechanism.

Ref. DEV-18126

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-05-31 08:57 UTC, sgiehl requested changes
Did you maybe missed to push the latest state or similar? The current code actually does change anything at all. You've added a new parameter to methods like `getMergedStylesheetAsset`, but added passing `true` to `getMergedStylesheet` 🧐 
Also the Proxy is actually always used, not only for UI tests, so there seems also some part missing that ensures that this only happens during testing

2024-06-03 11:45 UTC, michalkleiner commented
Thanks @sgiehl, I tried to cherry pick changes from the draft branch and missed some stuff on Friday. I've added it back now. I also didn't know the Proxy was used all the time which wouldn't be in my change anyway, but have put that info in now.

Is there a better way how to know we are within UI tests other than the DI approach I used?

2024-06-04 10:41 UTC, michalkleiner commented
Hmmm, the 3rd group keeps timing out.. could it be related to the change?

2024-06-04 15:39 UTC, mneudert commented
The timeouts should be related to #22284, not any change done here.

2024-06-05 07:57 UTC, closed without merging

2024-06-05 12:36 UTC, michalkleiner commented
Closed as a more suitable approach to the problem was found in https://github.com/matomo-org/matomo/pull/22285.