Update 1-click trial process to go via Markeplace e-shop
piwik/piwik pull request #22451
Opened 2024-07-29 22:13 UTC by michalkleiner

### Description:

Ref DEV-18349.

The behaviour on narrower screens was tweaked in dev, that may need adjusting, though I'm not sure what other options are there.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-07-29 22:17 UTC, michalkleiner commented on plugins/Marketplace/Marketplace.php
> -        $translationKeys[] = 'Marketplace_CurrentNumPiwikUsers';
This line was duplicated, so removed one instance of it.

2024-07-29 22:18 UTC, michalkleiner commented on plugins/Marketplace/stylesheets/plugin-details.less
> +        margin-top: 1px; // to prevent images overflowing the border
Unrelated to the change, but I notices some of the floating images were overlapping the border, so this fixes it.

2024-08-01 09:03 UTC, sgiehl requested changes
Generally seems to work as expected. Left a minor translation related comment.

Besides that the UI tests for starting a trial are now failing. Those need to be removed and/or adjusted to cover the new flow.

And I came across one thing that seems weird. For a plugin, which is installed, but the license is missing the super user sees a license missing warning, which is correct. But he normal user has a request trial button, while seeing the no license warning in the details modal.  It will most likely not be possible at all to start a new trial in that case, as if the plugin is already installed, there most likely had been a trial or purchase before, so maybe we should simply not show the trial button in that case.

![image](https://github.com/user-attachments/assets/25ce26fc-1ae2-443d-89af-2031236f3c40)

2024-08-01 09:03 UTC, sgiehl commented on plugins/Marketplace/lang/en.json
> +        "Free30DayTrialThen": "Free 30-day trial, then",
Any reason for not reusing the existing `TryFreeTrialTitle`. The text might be slightly different, but already has translations to various languages.
If we stick to this new one, we should remove `TryFreeTrialTitle` from the translation file.

2024-08-01 11:39 UTC, michalkleiner commented on plugins/Marketplace/lang/en.json
> +        "Free30DayTrialThen": "Free 30-day trial, then",
The new title is a middle ground between what it was before and what Javi had in his designs in a way where it reads as a sentence with the dropdown and makes it clear that it's free first AND after the trial you pay XYZ euros or dollars, so basically accessibility reasons.
I can revert it to the old one, or remove the old one and keep new one 🤷 
I get the point with the translations though.

2024-08-01 13:17 UTC, michalkleiner commented on plugins/Marketplace/lang/en.json
> +        "Free30DayTrialThen": "Free 30-day trial, then",
Used the old one for the benefit of the existing translations.

2024-08-01 23:24 UTC, michalkleiner commented
> And I came across one thing that seems weird. For a plugin, which is installed, but the license is missing the super user sees a license missing warning, which is correct. But he normal user has a request trial button, while seeing the no license warning in the details modal. It will most likely not be possible at all to start a new trial in that case, as if the plugin is already installed, there most likely had been a trial or purchase before, so maybe we should simply not show the trial button in that case.
> 
What combination of user access level did you use to get the screenshot? I can't reproduce it. When the plugin is installed and license is removed, a super user gets the notification that there's no license, and a regular user gets "More details" (after a tiny change), but a regular user never sees the notification as it requires "hasSomeAdminAccess" to be true.

2024-08-02 08:17 UTC, michalkleiner commented
> Besides that the UI tests for starting a trial are now failing. Those need to be removed and/or adjusted to cover the new flow.

@sgiehl removed the Start Free Trial UI tests for now.

2024-08-02 08:45 UTC, michalkleiner commented
> And I came across one thing that seems weird. For a plugin, which is installed, but the license is missing the super user sees a license missing warning, which is correct. But he normal user has a request trial button, while seeing the no license warning in the details modal. It will most likely not be possible at all to start a new trial in that case, as if the plugin is already installed, there most likely had been a trial or purchase before, so maybe we should simply not show the trial button in that case.

@sgiehl I've confirmed this was happening for a user that had admin access to another site ("some admin access"). After a change they see 'More details' on the plugin card, no license notification in the modal, but no 'Request trial' within the modal.

2024-08-02 10:23 UTC, sgiehl approved these changes
The previously reported things all seem fixed.
But I came across something else, but as that most likely was already the case before, it might not need to be fixed here.

When running Matomo on PHP 7.2, without a license for premium plugins, as super user it shows the `More Details` button for `LoginSaml`. I guess the `Start Trial` isn't shown, as it requires PHP 7.3. But the modal shows this:

![image](https://github.com/user-attachments/assets/35f43a13-2e43-442e-9e8e-fc7b57642bc9)

So it shows that it can't be installed, but the warning with the reason is missing.

2024-08-02 18:57 UTC, michalkleiner commented
I've checked how this behaved on 5.0.0 before the on-prem marketplace changes and the warning wasn't shown either for premium plugins. I'll create an internal ticket to follow that up.

2024-08-05 13:27 UTC, merged