Ensure LatestStable release channel uses the version provided from API
piwik/piwik pull request #22603
Opened 2024-09-19 15:10 UTC by sgiehl

### Description:

fixes #21894

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-09-19 18:03 UTC, mneudert requested changes

2024-09-19 18:03 UTC, mneudert commented on plugins/CoreUpdater/ReleaseChannel.php
> -        return sprintf('://builds.matomo.org/piwik-%s.zip', $version);
This needs to reflected in the failing `ReleaseChannelTest::testGetDownloadUrlWithoutScheme...` expectation.

2024-09-19 18:03 UTC, mneudert commented on plugins/CoreUpdater/ReleaseChannel/LatestStable.php
> -        return '://builds.matomo.org/matomo.zip';
We need an update to our `OneClickUpdate` UI test:

>      Error: Failed to setup fixture Piwik\Tests\Fixtures\LatestStableInstall (error code = 1)

The [fixture](https://github.com/matomo-org/matomo/blob/9a3ef94df61682e7d543f3f8b438c368f6eb71a6/tests/PHPUnit/Fixtures/LatestStableInstall.php#L98) currently passes `null` as the version, and creates a URL that won't be available.

2024-09-20 13:11 UTC, michalkleiner approved these changes
Looks good, all tests are green

2024-09-20 13:42 UTC, mneudert approved these changes

2024-09-20 13:58 UTC, merged