Introduce compact number formatting and use it for MultiSites KPIs
piwik/piwik pull request #22768
Opened 2024-11-18 10:16 UTC by sgiehl

### Description:

* Implements compact number and currency formatting for PHP and JavaScript
* Imports the required formats from CLDR
* Use new compact formatting for Marketplace plugin cards
* Use new compact formatting for All Websites Dashboard KPIs

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-11-22 14:45 UTC, mneudert requested changes

2024-11-22 14:45 UTC, mneudert commented on core/NumberFormatter.php
> +                round($value / $factor) === 1
```suggestion
                round($value / $factor) === 1.0
```

Otherwise this will never match.

Could only find one pattern where this actually matters, but we should add that to both the JS and PHP tests:

```
# difference only for currency translations
# the spaces are `&nbsp;` so just copying from here might not work
['ro', 1000, '1 mie $'],
['ro', 2000, '2 mii $'],
```

2024-11-22 16:11 UTC, sgiehl commented on core/NumberFormatter.php
> +                round($value / $factor) === 1
good catch 👍

2024-11-22 17:01 UTC, mneudert submitted a review, later dismissed

2024-11-24 21:52 UTC, michalkleiner commented on core/NumberFormatter.php
> +     * Formats a given number in compact format
```suggestion
     * Formats a given currency value in compact format
```

2024-11-25 09:30 UTC, mneudert approved these changes

2024-11-25 09:30 UTC, merged