Integration tests for visitor id vs user id scenarios
piwik/piwik pull request #22776
Opened 2024-11-19 09:52 UTC by michalkleiner

### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-11-22 17:02 UTC, mneudert commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $tracker->setForceVisitDateTime($attrDT);
Settig the visit date time has no effect as it will be overwritten in `trackPageview`.

Replacing it with a modification to `this->trackerEventTsIterator += 3600` is probably not an alternative, as that would move past the default `visit_standard_length` of `1800`. That would create a second visit, but it would also create a new visitor id.

We can just remove those calls.

2024-11-22 17:02 UTC, mneudert commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->assertCounts(2, 2, 1); // TODO - find out why this fails to create 2nd visit
This test will work as expected by switching from `attributionInfo` to passing campaign info as URL parameters:

```
$tracker->setUrl('http://www.example.com/?utm_campaign=first');
$this->trackPageview();

$tracker->setUrl('http://www.example.com/?utm_campaign=second');
$this->trackPageview();
```

The attribution info is not used by `Piwik\Plugins\Referrers\Columns\Campaign` to check for a new visit.

2024-11-22 17:02 UTC, mneudert commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->trackAction($tracker, 'log-out', false);
For completeness I would suggest we also create all these tests WITHOUT using actions to change the user id. They should all yield the same results.

2024-11-22 17:02 UTC, mneudert commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        }
A stilistic choice, but the tests may be easier to read by explicitly calling `tracker->setUserId`, instead of having to know what that third optional parameter does:

```
# current
trackPageview()
trackPageview('user')
trackPageview()

# suggested
trackPageview()
setUserId('user')
trackPageview()
trackPageview()

# or more verbose but really explicit
trackPageview()
logInUser()
trackPageview()
logOutUser()
```

2024-11-22 17:33 UTC, mneudert commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->assertVisitorIdsCount(2); // TODO - discuss with product that new device forms a new visit
Just to mention so we don't forget this detail here:

We do not get two visits with four actions each.  The "log-in" action of the second device will be merged into the first visit, so we have one visit with five, and one visit with three actions.

2024-11-25 08:36 UTC, michalkleiner commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->assertCounts(2, 2, 1); // TODO - find out why this fails to create 2nd visit
Nice, thanks for this.

2024-11-25 08:47 UTC, michalkleiner commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        }
added an explicit log in and log out methods, thanks for the suggestion

2024-11-25 08:48 UTC, michalkleiner commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->trackAction($tracker, 'log-out', false);
I've pushed a few more test cases ending in `withoutActions`, let me know if that's what you had in mind.

2024-11-25 08:48 UTC, michalkleiner commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $tracker->setForceVisitDateTime($attrDT);
Fair call, thanks!

2024-11-28 16:05 UTC, sgiehl requested changes
I had a look through the test cases. In general I think they should reflect the described cases, but we need to improve the checks at some point, so we also test that the actions are assigned to the correct visit.

What is currently completely untested is using the config `enable_userid_overwrites_visitorid = 0`, which we should also test, so we can later document the exact behavior of it.

And the biggest part we might also need to (maybe manually) test is, if the javascript tracker behaves the same. 
I think there are a some edge cases, that are currently not really tested. But I also don't exactly know how the javascript tracker would behave in combination with a user id if e.g.:
* cookies are fully disabled or cookie consent is given after some actions
* browser feature detection is disabled (or activated after some actions)

2024-11-28 16:05 UTC, sgiehl commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +    // user logs in during a visit, custom User ID is only provided for the log in action
Technically the user id is provided (automatically) for every tracking request after it was set (until it is unset).

2024-11-28 16:05 UTC, sgiehl commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->assertVisitorIdsCount(2); // TODO - discuss with product that new device forms a new visit
It could indeed be helpful to extend the count checks a bit in general. So they do not compare the overall count numbers, but per visit counts for action instead.
This is needed to ensure we do not attach actions to the wrong visit as @Marc already mentioned above.

2024-11-28 16:05 UTC, sgiehl commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        // since we forced a new visit, the visitor id after second log out is different
Note: This is actually caused by creating a new tracker instance. If you only call `setForceNewVisit` it should create a new visit with the same visitorId. So the behaviour here is somewhat the same as coming back with cleared cookies.

2024-11-28 16:05 UTC, sgiehl commented on tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
> +        $this->assertVisitorIdsCount(2); // TODO - discuss with product that new device forms a new visit
This might, like above, also not fully test what actually happens. Yes, there are two visits. But `page-6` is actually attributed to the first visit, which might be unexpected and not clear when looking at the test.

2024-12-18 16:28 UTC, sgiehl approved these changes, later dismissed
With my latest changes PHP and UI tests now should behave identical in terms of expected results. So for an initial test set this should be good to merge.
What we at some point could also consider to test are additional UI tests in combination with things like `requireConsent`, `requireCookieConsent` and similar.

In terms of "unexpected" behavior there are these cases we might later need to have a closer look at:

https://github.com/matomo-org/matomo/blob/c963f5cd2723c2a34d5409b16ee613750cc2fc0b/tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php#L367-L399

https://github.com/matomo-org/matomo/blob/c963f5cd2723c2a34d5409b16ee613750cc2fc0b/tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php#L480-L528

2024-12-20 12:37 UTC, sgiehl approved these changes

2024-12-20 12:38 UTC, merged